export {
  IM_ICON_CATALOG,
  IM_ICON_COLORS,
  ImBolt,
  ImCircleCheck,
  ImClipboardChecks,
  ImDecision,
  ImDroplet,
  ImHandsHeart,
  ImRuler,
  ImShieldAlert,
  ImShieldOk,
  ImSpeech,
  ImStar,
  ImStepBadge,
  ImStethoscope,
  ImStop,
  ImSyringeDepths,
  ImTarget,
  ImVialSyringe,
  type ImIconColor,
} from './ImClinicalIcons';
