import { LOGIC_FLOW_POOL, pickRotatedLayoutVariant } from './layoutRotation';
import type { LayoutRotationContext } from './conceptMapLayout';

const LOGIC_FLOW_LAYOUT_OVERRIDES = new Set([
  'vertical',
  'horizontal',
  'cards',
  'oxygen-step-ladder',
  'iv-care-soft-stack',
  'lab-vf-soft-stack',
  'wound-prep-tap-flow',
  'vitals-translate-tap',
  'pni-vf-juggle-tap',
  'pni-calendar-elimination-tap',
  'pni-cold-chain-tap',
  'ist-vf-juggle-tap',
  'dose-calc-tap',
  'sae-decision-tap',
  'sonda-decision-tap',
  'via-vf-juggle-tap',
  'farmaco-vf-juggle-tap',
  'farmaco-protocol-tap-flow',
  'adolescent-vf-weave-tap',
  'adolescent-z-classify-tap',
  'burn-triage-tap-flow',
  'trabalho-vf-juggle-tap',
  'sp-vf-juggle-tap',
  'sp-protocol-tap-flow',
  'respiratorio-vf-juggle-tap',
  'mental-raps-classify-tap',
  'mental-crisis-decision-tap',
  'peri-preop-decision-tap',
  'peri-srpa-decision-tap',
  'peri-protocol-tap-flow',
  'peri-vf-juggle-tap',
  'urgencias-rcp-tap-flow',
  'urgencias-xabcde-tap-flow',
  'urgencias-stroke-elimination-tap',
  'urgencias-shock-tap-flow',
  'urgencias-choking-tap-flow',
  'urgencias-pediatric-tap-flow',
  'etiology-elimination-tap',
  'tb-vf-elimination-tap',
  'itu-exceto-tap',
  'biosseg-vf-juggle-tap',
  'mulher-prenatal-tap-flow',
  'mulher-labor-tap-flow',
  'mulher-screening-tap-flow',
  'mulher-mama-tap-flow',
  'mulher-puerperio-tap-flow',
  'mulher-planejamento-tap-flow',
  'crianca-feeding-tap-flow',
  'crianca-screening-tap-flow',
  'crianca-pediatric-tap-flow',
  'crianca-dehydration-tap-flow',
  'crianca-puericultura-tap-flow',
  'crianca-neonatal-tap-flow',
  'crianca-dev-tap-flow',
  'cam-vf-juggle-tap',
  'cam-alto-risco-elimination-tap',
  'cam-exceto-tap-flow',
  'cam-documentacao-vf-tap',
  'iv-complication-tap-flow',
  'iv-device-tap-flow',
  'iv-exceto-tap-flow',
  'iv-interval-tap-flow',
  'iv-puncture-tap-flow',
  'iv-bundle-tap-flow',
  'pt-crase-funnel-tap-flow',
  'pt-clitic-rail-tap-flow',
  'pt-comma-rail-tap-flow',
  'pt-term-matrix-tap-flow',
  'pt-subject-focus-tap-flow',
]);

const LOGIC_FLOW_MOLD_OVERRIDES = new Set([
  'oxygen-step-ladder',
  'iv-care-soft-stack',
  'lab-vf-soft-stack',
  'wound-prep-tap-flow',
  'vitals-translate-tap',
  'pni-vf-juggle-tap',
  'pni-calendar-elimination-tap',
  'pni-cold-chain-tap',
  'ist-vf-juggle-tap',
  'dose-calc-tap',
  'sae-decision-tap',
  'sonda-decision-tap',
  'via-vf-juggle-tap',
  'farmaco-vf-juggle-tap',
  'farmaco-protocol-tap-flow',
  'adolescent-vf-weave-tap',
  'adolescent-z-classify-tap',
  'burn-triage-tap-flow',
  'trabalho-vf-juggle-tap',
  'sp-vf-juggle-tap',
  'sp-protocol-tap-flow',
  'respiratorio-vf-juggle-tap',
  'mental-raps-classify-tap',
  'mental-crisis-decision-tap',
  'peri-preop-decision-tap',
  'peri-srpa-decision-tap',
  'peri-protocol-tap-flow',
  'peri-vf-juggle-tap',
  'urgencias-rcp-tap-flow',
  'urgencias-xabcde-tap-flow',
  'urgencias-stroke-elimination-tap',
  'urgencias-shock-tap-flow',
  'urgencias-choking-tap-flow',
  'urgencias-pediatric-tap-flow',
  'etiology-elimination-tap',
  'tb-vf-elimination-tap',
  'itu-exceto-tap',
  'biosseg-vf-juggle-tap',
  'mulher-prenatal-tap-flow',
  'mulher-labor-tap-flow',
  'mulher-screening-tap-flow',
  'mulher-mama-tap-flow',
  'mulher-puerperio-tap-flow',
  'mulher-planejamento-tap-flow',
  'crianca-feeding-tap-flow',
  'crianca-screening-tap-flow',
  'crianca-pediatric-tap-flow',
  'crianca-dehydration-tap-flow',
  'crianca-puericultura-tap-flow',
  'crianca-neonatal-tap-flow',
  'crianca-dev-tap-flow',
  'cam-vf-juggle-tap',
  'cam-alto-risco-elimination-tap',
  'cam-exceto-tap-flow',
  'cam-documentacao-vf-tap',
  'iv-complication-tap-flow',
  'iv-device-tap-flow',
  'iv-exceto-tap-flow',
  'iv-interval-tap-flow',
  'iv-puncture-tap-flow',
  'iv-bundle-tap-flow',
  'pt-crase-funnel-tap-flow',
  'pt-clitic-rail-tap-flow',
  'pt-comma-rail-tap-flow',
  'pt-term-matrix-tap-flow',
  'pt-subject-focus-tap-flow',
]);

/**
 * Resolve `layout_variant` do logic_flow.
 * - Com ≥3 passos → rotação horizontal/vertical/cards por slug (salvo override explícito no JSON).
 */
export function resolveLogicFlowLayoutVariant(
  slide: { steps?: unknown[] } | undefined,
  explicitVariant?: string,
  fallbackVariant?: string,
  ctx?: LayoutRotationContext,
): string {
  const stepCount = Array.isArray(slide?.steps) ? slide.steps.length : 0;

  if (stepCount >= 3) {
    if (explicitVariant) {
      return explicitVariant;
    }
    if (fallbackVariant && LOGIC_FLOW_MOLD_OVERRIDES.has(fallbackVariant)) {
      return fallbackVariant;
    }
    if (ctx?.slug) {
      return pickRotatedLayoutVariant(
        LOGIC_FLOW_POOL,
        fallbackVariant ?? 'cards',
        ctx.slug,
        ctx.slideIndex ?? 0,
        'logic_flow',
      );
    }
    return fallbackVariant ?? 'cards';
  }

  return explicitVariant || fallbackVariant || 'vertical';
}
