import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Terminologia anatômica padronizada — posição anatômica.
 * Referência: Terminologia Anatômica (FCAT/IFAA) — conceitos estáveis; sem doses clínicas.
 */
export const ANATOMIA_TERMINOLOGIA: GuidelineTable = {
  id: 'anatomia-terminologia',
  snapshot: 'Terminologia Anatômica — planos, eixos e sinônimos',
  issuer: 'Terminologia Anatômica (IFAA/FCAT)',
  title: 'Noções de Anatomia',
  year: 1998,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z',
  entries: [
    {
      id: 'anterior-ventral',
      label: 'Anterior',
      value: 'sinônimo de ventral — parte da frente do corpo',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'posterior-dorsal',
      label: 'Posterior',
      value: 'sinônimo de dorsal — parte de trás do corpo',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'superior-cranial',
      label: 'Superior',
      value: 'sinônimo de cranial — em direção à cabeça',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'inferior-caudal',
      label: 'Inferior',
      value: 'sinônimo de caudal — em direção aos pés',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'medial',
      label: 'Medial',
      value: 'próximo da linha média do corpo',
      detail: 'Lateral é afastado da linha média.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'proximal-distal',
      label: 'Proximal / distal',
      value: 'proximal = próximo da origem do membro; distal = distante',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'pegadinha-posterior-cranial',
      label: 'Pegadinha',
      value: 'posterior não é sinônimo de cranial',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'plano-sagital',
      label: 'Plano sagital',
      value: 'divide o corpo em partes direita e esquerda',
      detail: 'Plano sagital mediano passa pela linha média; parasagital é paralelo.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'plano-frontal',
      label: 'Plano frontal (coronal)',
      value: 'divide o corpo em partes anterior e posterior',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'plano-transverso',
      label: 'Plano transverso (horizontal)',
      value: 'divide o corpo em partes superior e inferior',
      detail: 'Também chamado axial — perpendicular aos planos sagital e frontal.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'cavidade-craniana',
      label: 'Cavidade craniana',
      value: 'hospeda o encéfalo e meninges',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'cavidade-toracica',
      label: 'Cavidade torácica',
      value: 'coração, pulmões, traqueia e grandes vasos',
      detail: 'Limitada pelo diafragma inferiormente — separa tórax do abdome.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'cavidade-abdominal',
      label: 'Cavidade abdominal',
      value: 'fígado, estômago, intestinos, baço, pâncreas e rins',
      detail: 'Cavidade pélvica inferior continua a região abdominal inferior.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'sistema-cardiovascular',
      label: 'Sistema cardiovascular',
      value: 'coração + vasos sanguíneos — transporte de O₂, nutrientes e hormônios',
      detail: 'Artérias conduzem sangue do coração; veias retornam ao coração (geralmente).',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'sistema-respiratorio',
      label: 'Sistema respiratório',
      value: 'vias aéreas + pulmões — hematose (troca gasosa)',
      detail: 'Faringe, laringe, traqueia, brônquios e alvéolos; diafragma é músculo principal da inspiração.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'orgaos-sistemas',
      label: 'Níveis de organização',
      value: 'células → tecidos → órgãos → sistemas → organismo',
      detail: 'Órgão = estrutura com função específica; sistema = conjunto de órgãos inter-relacionados.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'sistema-digestorio',
      label: 'Sistema digestório',
      value: 'boca, faringe, esôfago, estômago, intestinos, fígado e pâncreas',
      detail: 'Função: ingestão, digestão, absorção de nutrientes e eliminação de resíduos.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'sistema-urinario',
      label: 'Sistema urinário',
      value: 'rins, ureteres, bexiga e uretra',
      detail: 'Filtração sanguínea, formação da urina e eliminação — regula volume e eletrólitos.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'sistema-nervoso',
      label: 'Sistema nervoso',
      value: 'encéfalo, medula espinhal e nervos periféricos',
      detail: 'Sistema nervoso central (SNC) e periférico (SNP) — integração e resposta a estímulos.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'sistema-endocrino',
      label: 'Sistema endócrino',
      value: 'glândulas que secretam hormônios na corrente sanguínea',
      detail: 'Hipófise, tireoide, adrenais, pâncreas endócrino — regulação metabólica e homeostase.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'cavidades-corpo',
      label: 'Cavidades do corpo',
      value: 'craniana, torácica, abdominal e pélvica',
      detail: 'Cavidades ventrais protegidas por parede musculoesquelética; mediastino divide o tórax.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'quadrantes-abdominais',
      label: 'Quadrantes abdominais',
      value: 'QD, QE, HD e HE — linhas média sagital e transpyloric',
      detail: 'QD: fígado e vesícula; QE: baço e estômago; HD: apêndice; HE: sigmoide — referência clínica.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'localizacao-orgaos',
      label: 'Localização de órgãos',
      value: 'coração no mediastino; fígado no QD; baço no QE (hipocôndrio esquerdo)',
      detail: 'Coração inclinado à esquerda; fígado é o maior órgão sólido abdominal.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'pegadinha-medial-lateral',
      label: 'Pegadinha medial × lateral',
      value: 'medial = próximo da linha média; lateral = afastado da linha média',
      detail: 'Não confundir com proximal/distal (membros) nem anterior/posterior.',
      sourceId: 'anatomia-terminologia',
    },
    {
      id: 'sistema-musculoesqueletico',
      label: 'Sistema musculoesquelético',
      value: 'ossos, articulações e músculos — sustentação e movimento',
      detail: 'Eixo do corpo: crânio, coluna vertebral, tórax e pelve — base para termos direito/esquerdo.',
      sourceId: 'anatomia-terminologia',
    },
  ],
};
