import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Atenção Básica / Saúde da Família.
 * Fonte: PNAB 2017 (MS) + Cadernos de Atenção Básica.
 */
export const ATENCAO_BASICA_PNAB: GuidelineTable = {
  id: 'atencao-basica-pnab',
  snapshot: 'PNAB — princípios e atributos da APS',
  issuer: 'Ministério da Saúde',
  title: 'Atenção Básica / Saúde da Família',
  year: 2017,
  url: 'https://bvsms.saude.gov.br/bvs/publicacoes/politica_nacional_atencao_basica.pdf',
  entries: [
    {
      id: 'aps-porta-entrada',
      label: 'Porta de entrada',
      value: 'Atenção Básica é porta de entrada preferencial do SUS',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'aps-esf',
      label: 'Estratégia Saúde da Família',
      value: 'equipe multiprofissional com médico, enfermeiro, técnico e ACS',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'aps-territorialidade',
      label: 'Territorialidade e adscrição',
      value: 'cuidado vinculado ao território e à população adscrita',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'aps-longitudinalidade',
      label: 'Longitudinalidade',
      value: 'acompanhamento contínuo ao longo do tempo',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'aps-acolhimento',
      label: 'Acolhimento',
      value: 'primeiro contato humanizado e resolutivo',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'aps-coordenacao',
      label: 'Coordenação do cuidado',
      value: 'integrar usuário na rede de atenção à saúde',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'aps-intersetorialidade',
      label: 'Intersetorialidade',
      value: 'articulação com proteção social e outros setores',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'violencia-manejo',
      label: 'Violência na APS',
      value: 'avaliar vulnerabilidade + notificar + encaminhar multiprofissional',
      detail: 'Manejo integral — não restringir a lesões visíveis.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'violencia-notificacao',
      label: 'Notificação violência',
      value: 'registro sistemático e encaminhamento à rede de proteção',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'esf-composicao-minima',
      label: 'ESF — composição mínima',
      value: 'médico, enfermeiro, técnico/auxiliar de enfermagem e ACS',
      detail: 'PNAB 2017 — equipe multiprofissional com atribuições definidas por categoria.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'esf-acs-cobertura',
      label: 'ACS — parâmetro de cobertura',
      value: '1 ACS para cada 750 a 1.000 famílias (ou até 2.000 hab.)',
      detail: 'Agente vinculado ao território — visita domiciliar e vínculo longitudinal.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'nasf-emulti',
      label: 'NASF-AB / eMulti',
      value: 'apoio matricial especializado às equipes de Saúde da Família',
      detail: 'Psicólogo, nutricionista, fisioterapeuta, entre outros — cuidado compartilhado.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'matriciamento-def',
      label: 'Matriciamento',
      value: 'suporte especializado à equipe de referência — não é encaminhamento unilateral',
      detail: 'Discussão de casos, capacitação e cuidado compartilhado no território.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'territorializacao-mapa',
      label: 'Territorialização',
      value: 'delimitar área geográfica e mapear determinantes de saúde',
      detail: 'Base do planejamento local — diagnóstico situacional do território.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'adscricao-populacao',
      label: 'Adscrição',
      value: 'vincular população a uma equipe de Saúde da Família',
      detail: 'Responsabilização sanitária — usuário sabe qual UBS/equipe é sua referência.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'acolhimento-classificacao-risco',
      label: 'Acolhimento com classificação de risco',
      value: 'escuta qualificada + priorização conforme gravidade',
      detail: 'Protocolo de Manchester ou fluxo local — não é ordem estrita de chegada.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'acolhimento-primeiro-contato',
      label: 'Acolhimento — primeiro contato',
      value: 'responsabilização imediata — resolver ou agendar no mesmo dia quando possível',
      detail: 'PNAB — acolhimento é atributo essencial da APS, não apenas recepção administrativa.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'pacto-saude-familia',
      label: 'Pacto pela Saúde',
      value: 'compromisso entre equipe e família para cuidado compartilhado',
      detail: 'Instrumento de vínculo — metas de cuidado acordadas com o usuário.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'atributo-primeiro-contato',
      label: 'Atributo APS — primeiro contato',
      value: 'acesso e resolutividade no primeiro contato com o serviço',
      detail: 'Starfield — APS como porta de entrada preferencial do SUS.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'atributo-longitudinalidade',
      label: 'Atributo APS — longitudinalidade',
      value: 'relação terapêutica contínua ao longo do tempo',
      detail: 'Mesma equipe acompanha o usuário — não apenas consulta pontual.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'atributo-integralidade',
      label: 'Atributo APS — integralidade',
      value: 'atenção às necessidades biopsicossociais do indivíduo e família',
      detail: 'Prevenção, promoção, tratamento e reabilitação no mesmo serviço.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'atributo-coordenacao',
      label: 'Atributo APS — coordenação do cuidado',
      value: 'integrar o usuário na rede de atenção à saúde',
      detail: 'Referência e contrarreferência — equipe acompanha encaminhamentos.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'atributo-orientacao-familia',
      label: 'Atributo APS — orientação familiar',
      value: 'cuidado centrado na família e contexto de vida',
      detail: 'Família como unidade de cuidado — não apenas o indivíduo isolado.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'atributo-competencia-cultural',
      label: 'Atributo APS — competência cultural',
      value: 'respeitar valores, crenças e contexto sociocultural do território',
      detail: 'Cuidado sensível à diversidade — reduz barreiras de acesso.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'esf-microarea',
      label: 'ESF — microárea',
      value: 'subdivisão do território da equipe (cerca de 150 a 200 famílias por ACS)',
      detail: 'ACS responsável por microárea — base da territorialização e adscrição.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'acs-visita-domiciliar',
      label: 'ACS — visita domiciliar',
      value: 'prioridade para gestantes, crianças, idosos e pessoas com vulnerabilidade',
      detail: 'Cadastro e acompanhamento longitudinal — não é visita apenas administrativa.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'manchester-cores',
      label: 'Manchester — classificação de risco',
      value: 'azul, verde, amarelo, laranja e vermelho (gravidade crescente)',
      detail: 'Acolhimento com escuta qualificada — priorizar por risco, não ordem de chegada.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'manchester-tempo-maximo',
      label: 'Manchester — tempo de espera',
      value: 'vermelho imediato; laranja até 10 min; amarelo até 60 min (referência)',
      detail: 'Protocolo de acolhimento na UBS/UPA — fluxo local pode adaptar tempos.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'emulti-composicao',
      label: 'eMulti — composição',
      value: 'equipe multiprofissional de apoio matricial às equipes de SF',
      detail: 'Nutricionista, psicólogo, fisioterapeuta, assistente social, entre outros.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'matriciamento-discussao-caso',
      label: 'Matriciamento — discussão de caso',
      value: 'reunião entre equipe de referência e equipe de apoio',
      detail: 'Cuidado compartilhado no território — não substitui encaminhamento quando necessário.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'violencia-tipos',
      label: 'Violência — tipos na APS',
      value: 'física, psicológica, sexual, patrimonial e negligência',
      detail: 'Avaliar sinais de alerta em todas as faixas etárias — criança, mulher e idoso.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'violencia-rede-protecao',
      label: 'Violência — rede de proteção',
      value: 'encaminhar CRAS, CREAS, Conselho Tutelar ou delegacia especializada',
      detail: 'Notificação compulsória quando aplicável — manejo multiprofissional.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'pacto-metas-cuidado',
      label: 'Pacto pela saúde — metas',
      value: 'objetivos de cuidado acordados entre profissional, usuário e família',
      detail: 'Instrumento de corresponsabilização — adesão ao tratamento e mudança de hábitos.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'territorializacao-diagnostico',
      label: 'Territorialização — diagnóstico situacional',
      value: 'mapear determinantes, vulnerabilidades e recursos do território',
      detail: 'Base do planejamento local — informa prioridades da equipe.',
      sourceId: 'atencao-basica-pnab',
    },
    {
      id: 'adscricao-cadastro',
      label: 'Adscrição — cadastro',
      value: 'vincular família à equipe de referência da UBS',
      detail: 'Usuário identifica sua equipe — responsabilização sanitária.',
      sourceId: 'atencao-basica-pnab',
    },
  ],
};
