import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Biossegurança, IRAS e precauções.
 * Fontes: Anvisa Protocolo 5 (Precauções e Isolamento) + NT GVIMS 11/2025;
 * higiene das mãos NT 05/2024; RSS RDC 222/2018.
 * @see https://www.gov.br/anvisa/pt-br/centraisdeconteudo/publicacoes/servicosdesaude/publicacoes/Protocolo5MedidasdePrecauoeIsolamentoFINAL.pdf
 */
export const BIOSSEGURANCA_ANVISA: GuidelineTable = {
  id: 'biosseguranca-anvisa',
  snapshot: 'Anvisa Protocolo precauções/isolamento + NT 11/2025 IRAS',
  issuer: 'Anvisa / Ministério da Saúde',
  title: 'Biossegurança e prevenção de IRAS',
  year: 2025,
  url: 'https://www.gov.br/anvisa/pt-br/centraisdeconteudo/publicacoes/servicosdesaude/publicacoes/Protocolo5MedidasdePrecauoeIsolamentoFINAL.pdf',
  entries: [
    {
      id: 'cadeia-infeccao',
      label: 'Cadeia de infecção',
      value: '6 elos: agente, reservatório, porta de saída, transmissão, porta de entrada, hospedeiro',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'iras-def',
      label: 'IRAS',
      value: 'infecção relacionada à assistência à saúde',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'epi-risco',
      label: 'EPI',
      value: 'selecionado conforme risco da exposição',
      detail: 'Não é kit único para todos os procedimentos.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'perfurocortante',
      label: 'Perfurocortante',
      value: 'descarte em coletor rígido e específico',
      detail: 'Nunca em lixo comum — capa protetora não autoriza descarte inadequado.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'nao-recapear',
      label: 'Agulhas',
      value: 'não recapear agulhas',
      detail: 'Risco de perfuração acidental.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'precaucoes-padrao',
      label: 'Precauções padrão',
      value: 'higiene das mãos + EPI conforme risco — todos os pacientes',
      detail:
        'Anvisa Protocolo 5: mínimo obrigatório em todo atendimento, com ou sem infecção suspeita. Precauções por via de transmissão são adicionais e nunca substituem o padrão.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'precaucao-contato',
      label: 'Precaução por contato',
      value: 'luvas e avental — MDRO, C. difficile',
      detail: 'Associar sempre às precauções padrão (Anvisa Protocolo 5).',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'precaucao-goticulas',
      label: 'Precaução por gotículas',
      value: 'máscara cirúrgica — distância ≤1 m',
      detail: 'Influenza, meningite meningocócica, coqueluche. Gotícula >5 µm (Protocolo 5 Anvisa).',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'precaucao-aerossol',
      label: 'Precaução por aerossóis',
      value: 'respirador N95/PFF2 + ventilação adequada',
      detail:
        'TB pulmonar/laríngea, sarampo, varicela. Paciente em transporte: máscara cirúrgica; profissional: N95/PFF2 no quarto (Protocolo 5).',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'higiene-maos',
      label: 'Higiene das mãos',
      value: 'momento 1 a 5 da OMS',
      detail: 'NT GVIMS/Anvisa 05/2024 — medida mais eficaz contra IRAS.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'residuos-perfuro',
      label: 'Resíduos perfurocortantes',
      value: 'grupo E — recipiente rígido e punctura-resistente',
      detail: 'RDC 222/2018 — grupo E (não grupo A).',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'lavagem-maos-40s',
      label: 'Lavagem das mãos (água e sabão)',
      value: 'friccionar por 40 a 60 segundos',
      detail: 'Guia MS/Anvisa — cobrir todas as superfícies; enxaguar e secar com toalha descartável.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'alcool-gel-70',
      label: 'Álcool gel 70%',
      value: 'friccionar até secar — cerca de 20 a 30 segundos',
      detail: 'Indicado quando as mãos não estão visivelmente sujas; não substitui lavagem após contato com fluidos corporais.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'residuos-grupo-a-infect',
      label: 'Resíduos grupo A (RDC 222/2018)',
      value: 'resíduos com risco biológico — infectantes',
      detail: 'Sangue, secreções, culturas, peças anatômicas — acondicionamento e tratamento específicos.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'residuos-grupo-b-comum',
      label: 'Resíduos grupo B (RDC 222/2018)',
      value: 'resíduos químicos — inflamáveis, corrosivos, reativos ou tóxicos',
      detail:
        'RDC 222/2018: grupo B = químicos (medicamentos vencidos, solventes, reveladores). Não confundir com comuns (grupo D).',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'residuos-grupo-e-perfuro',
      label: 'Resíduos grupo E',
      value: 'perfurocortantes — coletor rígido, inquebrável e identificado',
      detail: 'Agulhas, lâminas, ampolas — nunca recapear nem compactar. RDC 222/2018.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'epi-descarte-contaminado',
      label: 'Descarte de EPI',
      value: 'EPI contaminado → resíduo infectante (grupo A)',
      detail: 'Retirar na área de cuidado; luvas por último; descartar em saco branco leitoso ou conforme fluxo institucional.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'quarto-isolamento-contato',
      label: 'Quarto de isolamento — contato',
      value: 'quarto individual ou cohort — precauções de contato',
      detail: 'MDRO, C. difficile — equipamentos dedicados; higiene das mãos reforçada.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'quarto-isolamento-aerossol',
      label: 'Quarto de isolamento — aerossóis',
      value: 'quarto com pressão negativa e ventilação adequada',
      detail: 'TB pulmonar bacilífera, sarampo, varicela — porta fechada; PFF2/N95 para entrada.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'vacinacao-trabalhador-saude',
      label: 'Vacinação do trabalhador da saúde',
      value: 'esquema completo conforme PNI — hepatite B, dT, influenza, COVID-19',
      detail: 'Portaria MS / calendário nacional — atualizar carteira vacinal; exigência institucional de biossegurança.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'higiene-maos-5-momentos-oms',
      label: 'Higiene das mãos — 5 momentos OMS',
      value: '1) antes do contato; 2) antes de procedimento asséptico; 3) após risco de fluidos; 4) após contato com paciente; 5) após contato com entorno',
      detail: 'Medida mais eficaz contra IRAS — álcool 70% ou lavagem com água e sabão conforme indicação.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'residuos-grupo-c-quimico',
      label: 'Resíduos grupo C (RDC 222/2018)',
      value: 'rejeitos radioativos — medicina nuclear / radioterapia (CNEN)',
      detail: 'RDC 222/2018: grupo C = radioativos. Não confundir com químicos (grupo B).',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'residuos-grupo-d-radioativo',
      label: 'Resíduos grupo D (RDC 222/2018)',
      value: 'resíduos comuns — sem risco biológico, químico ou radiológico',
      detail:
        'Equiparáveis ao lixo domiciliar (papel, embalagens limpas, restos alimentares quando permitido). ID do entry mantido por estabilidade de sourceId.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'residuos-classificacao-abcde',
      label: 'Classificação de resíduos A–E',
      value: 'A infectantes; B químicos; C radioativos; D comuns; E perfurocortantes',
      detail: 'RDC Anvisa 222/2018 — segregação na fonte; identificação por cor e recipiente adequado.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'protocolos-iras-minimos-nt11-2025',
      label: 'Protocolos IRAS mínimos (NT 11/2025)',
      value: 'IPCS + ITU-CV + PAV + ISC + precauções/isolamento',
      detail:
        'NT GVIMS/Anvisa 11/2025: serviços devem implementar, no mínimo, esses cinco protocolos adaptados ao contexto local.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'acidente-exposicao-biologica',
      label: 'Acidente de exposição biológica',
      value: 'notificar imediatamente — lavar ferida, avaliar profilaxia e registrar boletim de ocorrência',
      detail: 'Perfurocortante, splash em mucosa ou pele não íntegra — seguir fluxo institucional e MS.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'epi-sequencia-vestir',
      label: 'EPI — ordem de vestir (donning)',
      value: 'avental → máscara → óculos/protetor facial → gorro → luvas',
      detail: 'Ajustar máscara antes das luvas; EPI conforme precaução (contato, gotículas ou aerossóis).',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'epi-sequencia-retirar',
      label: 'EPI — ordem de retirar (doffing)',
      value: 'luvas → óculos/protetor → avental → máscara → higiene das mãos',
      detail: 'Retirar na área de cuidado sem contaminar pele ou roupa; descartar EPI contaminado como resíduo infectante.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'assepsia-cirurgica',
      label: 'Assepsia cirúrgica',
      value: 'campo estéril, técnica sem toque e barreira estéril em procedimentos invasivos',
      detail: 'Antissepsia da pele, material estéril e movimentos dentro do campo — previne infecção de sítio cirúrgico.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'hh-reducao-70',
      label: 'Redução de transmissão — higiene das mãos',
      value: 'até 70% de redução na transmissão de microrganismos com HH adequada',
      detail: 'OMS/MS — HH nos 5 momentos é a medida mais eficaz contra IRAS.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'sf-09-periferico',
      label: 'SF 0,9% — cateter periférico',
      value: 'solução salina 0,9% para flushing e lock de cateter venoso periférico',
      detail: 'Não usar água estéril no lugar do SF 0,9% para manutenção do acesso periférico.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'pegadinha-recapear-agulha',
      label: 'Pegadinha — recapear agulha',
      value: 'nunca recapear agulha usada — risco de perfuração acidental',
      detail: 'Descarte direto no coletor grupo E; capa protetora não autoriza recapeamento.',
      sourceId: 'biosseguranca-anvisa',
    },
    {
      id: 'isolamento-pressao-negativa',
      label: 'Isolamento — pressão negativa (aerossóis)',
      value: '≥6–12 trocas de ar/h com pressão negativa em relação ao corredor',
      detail: 'TB bacilífera, sarampo, varicela — porta fechada; PFF2/N95; ar não retorna ao sistema geral sem filtro.',
      sourceId: 'biosseguranca-anvisa',
    },
  ],
};
