import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Equivalências e fórmulas de cálculo — padrão brasileiro de prova técnica.
 * Referência: COFEN (administração de medicamentos) + prática consagrada em bancas.
 */
export const CALCULO_EQUIVALENCIAS_BR: GuidelineTable = {
  id: 'calc-equivalencias-br',
  snapshot: 'Equivalências gts/mL e infusão — padrão BR',
  issuer: 'COFEN / referência técnica enfermagem',
  title: 'Cálculo de administração de medicamentos e infusões',
  year: 2021,
  url: 'https://www.cofen.gov.br/',
  entries: [
    {
      id: 'equiv-ml-gotas',
      label: 'Macrogotas por mL',
      value: '1 mL = 20 gotas',
      detail: 'Equipo de macrogotas — constante padrão em provas brasileiras.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'equiv-ml-microgotas',
      label: 'Microgotas por mL',
      value: '1 mL = 60 microgotas',
      detail: 'Equipo de microgotas.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'equiv-gota-micro',
      label: 'Gota × microgota',
      value: '1 gota = 3 microgotas',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'insulina-u100',
      label: 'Insulina U-100',
      value: '100 UI em 1 mL',
      detail: 'Seringa graduada em unidades — não confundir com 10 UI/mL.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'fator-macrogotas',
      label: 'Fator macrogotas (gts/min)',
      value: 'fator 20',
      detail: 'gts/min = (volume × 20) ÷ tempo em minutos.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'fator-microgotas',
      label: 'Fator microgotas (gts/min)',
      value: 'fator 60',
      detail: 'gts/min = (volume × 60) ÷ tempo em minutos.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'regra-tres-dose',
      label: 'Regra de três — dose',
      value: 'dose prescrita × disponível ÷ prescrito',
      detail: 'Conferir unidade: mg com mg, mL com mL.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'pegadinha-30-gotas',
      label: 'Pegadinha clássica',
      value: 'não usar 30 gotas/mL nem 90 microgotas/mL',
      detail: 'Banca troca 20 por 30 e 60 por 90.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'diluicao-c1v1',
      label: 'Diluição — fórmula',
      value: 'C₁ × V₁ = C₂ × V₂',
      detail: 'Manter mesma unidade de concentração (mg/mL) em ambos os lados.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'mcg-mg-conversao',
      label: 'mcg ↔ mg',
      value: '1 mg = 1.000 mcg',
      detail: 'Dose em mcg/kg exige converter peso e unidade antes da regra de três.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'dose-pediatrica-mgkg',
      label: 'Dose pediátrica (mg/kg)',
      value: 'dose (mg) = mg/kg × peso (kg)',
      detail: 'Conferir dose máxima diária do medicamento — mg/kg não dispensa teto terapêutico.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'horario-24h',
      label: 'Horário 24 horas',
      value: '00:00 a 23:59 — evitar confusão AM/PM',
      detail: 'Ex.: 14:00 = 14 h (não 2 h da tarde escrito como 2:00).',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'ampola-fracionada',
      label: 'Ampola fracionada',
      value: 'rotular data/hora de abertura e descartar no prazo de estabilidade',
      detail: 'COFEN: não reutilizar ampola sem conservação adequada — risco de contaminação.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'concentracao-percentual',
      label: 'Concentração percentual (p/v)',
      value: '1% = 1 g em 100 mL = 10 mg/mL',
      detail: 'Padrão clássico de prova técnica — 0,9% SF = 0,9 g/100 mL = 9 mg/mL.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'percentual-regra',
      label: 'Percentual → mg/mL',
      value: 'mg/mL = percentual × 10',
      detail: 'Ex.: 5% = 50 mg/mL; 10% = 100 mg/mL.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'pegadinha-percentual',
      label: 'Pegadinha percentual',
      value: 'não confundir 1% (10 mg/mL) com 1 mg/mL',
      detail: 'Banca troca p/v por mg/mL direto.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'regra-tres-exemplo-comprimido',
      label: 'Regra de três — exemplo comprimido',
      value: '500 mg prescritos, frasco 250 mg → 2 comprimidos',
      detail: '250 mg ── 1 cp | 500 mg ── X → X = (500 × 1) ÷ 250 = 2.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'regra-tres-exemplo-ml',
      label: 'Regra de três — exemplo mL',
      value: 'ampola 500 mg/2 mL, prescrição 250 mg → 1 mL',
      detail: '500 mg ── 2 mL | 250 mg ── X → X = (250 × 2) ÷ 500 = 1 mL.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'regra-tres-exemplo-fracao',
      label: 'Regra de três — exemplo fração',
      value: 'comprimido 40 mg, prescrição 20 mg → ½ comprimido',
      detail: '40 mg ── 1 cp | 20 mg ── X → X = 0,5 cp — conferir se fracionamento é permitido.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'diluicao-c1v1-exemplo',
      label: 'Diluição — exemplo C₁V₁ = C₂V₂',
      value: '10 mL de 20% + SF qsp 100 mL → C₂ = (20 × 10) ÷ 100 = 2%',
      detail: 'Manter mesma unidade (% ou mg/mL) — 2% = 20 mg/mL.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'dose-pediatrica-exemplo',
      label: 'Dose pediátrica — exemplo mg/kg',
      value: '15 mg/kg, criança 20 kg → 300 mg/dose',
      detail: '15 × 20 = 300 mg — conferir dose máxima diária antes de administrar.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'mcg-exemplo-dose',
      label: 'mcg — exemplo de conversão',
      value: '0,25 mg = 250 mcg — dose 5 mcg/kg em 10 kg = 50 mcg',
      detail: 'Converter mg → mcg (× 1.000) antes da regra de três; não misturar unidades.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'percentual-exemplo-1pct',
      label: 'Percentual — exemplo 1%',
      value: 'SF 0,9% = 0,9 g/100 mL = 9 mg/mL — lidocaína 2% = 20 mg/mL',
      detail: 'Regra rápida: mg/mL = percentual × 10.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'infusao-mlh-formula',
      label: 'Velocidade de infusão — mL/h',
      value: 'mL/h = volume total (mL) ÷ tempo (h)',
      detail: 'Bomba de infusão — diferente de gts/min (equipo macrogotas/microgotas).',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'infusao-mlh-exemplo',
      label: 'Infusão — exemplo mL/h',
      value: '500 mL SF em 8 h → 500 ÷ 8 = 62,5 mL/h',
      detail: 'Arredondar conforme graduação da bomba — conferir volume restante a cada turno.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'heparina-ui',
      label: 'Heparina — unidades (UI)',
      value: '500 UI/mL ou 5.000 UI/0,5 mL — dose em UI, não mg',
      detail: 'Não usar regra de três mg/kg — heparina é prescrita e calculada em UI.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'heparina-exemplo-bolus',
      label: 'Heparina — exemplo bolus',
      value: 'prescrição 5.000 UI, ampola 5.000 UI/1 mL → 1 mL',
      detail: 'Conferir via (EV) e tempo de administração — alto risco, dupla checagem.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'kcl-diluicao-max',
      label: 'KCl — diluição máxima periférica',
      value: 'máximo 40 mEq/L em veia periférica — acima disso, via central',
      detail: 'Referência técnica de prova — concentração alta causa flebite e arritmia.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'kcl-velocidade-max',
      label: 'KCl — velocidade máxima de infusão',
      value: 'máximo 10–20 mEq/h em adulto — nunca em bolus',
      detail: 'Monitorar ECG e níveis séricos — diluir antes de infundir.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'ampola-fracionada-exemplo',
      label: 'Ampola fracionada — exemplo',
      value: 'ampola 1 g/10 mL, usar 2 g → 20 mL + rotular frasco com data/hora',
      detail: 'Descartar no prazo de estabilidade — não reutilizar sem conservação adequada.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'horario-24h-exemplo',
      label: 'Horário 24 h — exemplo de intervalo',
      value: '8/8 h iniciando 06:00 → 06:00, 14:00, 22:00',
      detail: 'Intervalo entre doses conta a partir da administração, não do horário de prescrição.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'pegadinha-30-90-detalhe',
      label: 'Pegadinha 30 gotas / 90 microgotas',
      value: 'padrão BR: 20 gts/mL (macro) e 60 microgts/mL — não 30 nem 90',
      detail: 'Banca dobra o fator — sempre confirmar tipo de equipo antes de calcular.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'pegadinha-30-90-exemplo',
      label: 'Pegadinha gotas — exemplo numérico',
      value: '500 mL em 4 h, macro (fator 20) → gts/min = (500 × 20) ÷ 240 = 41,6 ≈ 42',
      detail: 'Com fator 30 (pegadinha): 62,5 gts/min — resposta errada se usar 30.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'polifarmacia-calculo-horarios',
      label: 'Polifarmácia — cálculo de horários',
      value: 'reconciliar prescrições e calcular próximo horário sem sobreposição',
      detail: 'Ex.: A 6/6 h às 08:00 → 14:00; B 8/8 h às 06:00 → 14:00 — escalonar se necessário.',
      sourceId: 'calc-equivalencias-br',
    },
    {
      id: 'polifarmacia-intervalo-minimo',
      label: 'Polifarmácia — intervalo mínimo',
      value: 'respeitar intervalo de cada fármaco — não unificar horários sem checar compatibilidade',
      detail: 'Antibiótico 6/6 h ≠ analgésico 8/8 h — calcular cada esquema separadamente.',
      sourceId: 'calc-equivalencias-br',
    },
  ],
};
