import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Central de Material e Esterilização (CME).
 * Fonte: Anvisa RDC 15/2012 e normas de processamento.
 */
export const CME_ANVISA: GuidelineTable = {
  id: 'cme-anvisa-rdc15',
  snapshot: 'CME — áreas, indicadores e validade',
  issuer: 'Anvisa',
  title: 'Central de Material e Esterilização',
  year: 2012,
  url: 'https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude/servicos',
  entries: [
    {
      id: 'cme-area-suja',
      label: 'Área suja',
      value: 'recepção do material contaminado',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-area-limpa',
      label: 'Área limpa',
      value: 'processamento, embalagem e esterilização',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-area-estéril',
      label: 'Área estéril',
      value: 'armazenamento e distribuição',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-fluxo',
      label: 'Fluxo unidirecional',
      value: 'suja → limpa → estéril',
      detail: 'Proibido retorno de material ao fluxo anterior.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-indicador-quimico',
      label: 'Indicador químico interno',
      value: 'confirma exposição ao processo no ciclo',
      detail: 'Não substitui indicador biológico quando exigido.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-indicador-biologico',
      label: 'Indicador biológico',
      value: 'confirma eficácia microbicida do ciclo',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-validade',
      label: 'Validade material estéril',
      value: 'possui prazo definido — não armazenar indefinidamente',
      detail: 'Embalagem íntegra não significa validade eterna.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-validade-nao-tecido',
      label: 'Embalagem não tecido (autoclave)',
      value: '30 dias',
      detail: 'Prazo usual após esterilização — conferir protocolo institucional.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-esterilizacao-vapor',
      label: 'Autoclave — vapor saturado',
      value: '121 °C por 15 minutos',
      detail: 'Ciclo padrão de referência em prova.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-limpeza',
      label: 'Limpeza',
      value: 'remoção de sujidade visível e matéria orgânica',
      detail: 'Primeira etapa do processamento — não elimina todos os microrganismos.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-desinfeccao',
      label: 'Desinfecção',
      value: 'redução do número de microrganismos — não elimina esporos',
      detail: 'Intermediária entre limpeza e esterilização; níveis alto, intermediário ou baixo.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-esterilizacao-def',
      label: 'Esterilização',
      value: 'destruição de todos os microrganismos, inclusive esporos',
      detail: 'Produto final deve atingir SAL 10⁻⁶ — só após limpeza e inspeção adequadas.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-autoclave-parametros',
      label: 'Autoclave — parâmetros de referência',
      value: '121 °C, 1 atm de pressão, 15 minutos de exposição',
      detail: 'Pré-vácuo ou gravidade — validar ciclo conforme carga e indicadores.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-biologico-esporos',
      label: 'Indicador biológico — esporos',
      value: 'Geobacillus stearothermophilus (vapor) ou Bacillus atrophaeus (ETO)',
      detail: 'Maior resistência microbiana — confirma eficácia do ciclo de esterilização.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-biologico-frequencia',
      label: 'Indicador biológico — periodicidade',
      value: 'semanal em autoclaves em uso diário — e a cada ciclo com implantes',
      detail: 'RDC 15/2012 — registrar resultados; material do ciclo reprovado não liberar.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-validade-embalagem-tecido',
      label: 'Validade — embalagem têxtil',
      value: '30 dias em armazenamento adequado',
      detail: 'Ambiente seco, temperatura controlada, embalagem íntegra — etiquetar data da esterilização.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-area-restrita',
      label: 'Área restrita',
      value: 'acesso somente a profissionais autorizados e paramentados',
      detail: 'Área limpa e estéril — traje conforme risco; proibida circulação desnecessária.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-pre-descontaminacao',
      label: 'Pré-descontaminação',
      value: 'umidificar e limpar material no local de uso antes do transporte',
      detail: 'Evitar secagem de matéria orgânica — realizar na área suja da CME ao receber.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-limpeza-desinfeccao-esterilizacao',
      label: 'Limpeza × desinfecção × esterilização',
      value: 'etapas distintas e sequenciais — não são sinônimos',
      detail: 'Limpeza remove sujidade; desinfecção reduz microrganismos (sem esporos); esterilização elimina todos, inclusive esporos.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-lavadora-desinfectadora',
      label: 'Lavadora-desinfectadora',
      value: 'equipamento que lava e desinfeta termicamente ou quimicamente',
      detail: 'Substitui lavagem manual quando validada — ciclo documentado; material deve ser compatível com o processo.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-oxido-etileno',
      label: 'Esterilização — óxido de etileno (ETO)',
      value: 'gás para materiais termossensíveis',
      detail: 'Ciclo longo com aeramento obrigatório — indicador biológico Bacillus atrophaeus; toxicidade residual exige ventilação.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-plasma-peroxido',
      label: 'Esterilização — plasma de peróxido de hidrogênio',
      value: 'baixa temperatura para instrumentos sensíveis',
      detail: 'Alternativa ao ETO para materiais que não suportam autoclave — validar compatibilidade do material com o ciclo.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-embalagem-tipos',
      label: 'Tipos de embalagem',
      value: 'papel grau cirúrgico, têxtil, invólucro e embalagem rígida',
      detail: 'Deve permitir penetração do agente esterilizante e manter barreira microbiana — indicador químico interno obrigatório.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-armazenamento-umidade',
      label: 'Armazenamento — umidade e temperatura',
      value: 'ambiente seco, limpo e com temperatura controlada',
      detail: 'Umidade excessiva compromete barreira da embalagem — prateleiras distantes do chão e do teto; rotacionar estoque (PEPS).',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-rastreabilidade-recall',
      label: 'Rastreabilidade e recall',
      value: 'registrar lote, ciclo, operador e destino de cada carga esterilizada',
      detail: 'Permite recall rápido se indicador biológico falhar — etiqueta com data, autoclave e número do ciclo.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'cme-seguranca-ocupacional',
      label: 'Segurança ocupacional na CME',
      value: 'EPI, capote, luvas, óculos e proteção contra produtos químicos',
      detail: 'NR-32 e RDC 15 — área suja tem maior risco biológico; treinamento periódico e vacinação conforme risco.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'pegadinha-cme-limpeza-esteriliza',
      label: 'Pegadinha — pular limpeza',
      value: 'material sujo não pode ser esterilizado — limpeza é etapa obrigatória',
      detail: 'Matéria orgânica protege microrganismos no ciclo; desinfecção alta não substitui esterilização para uso invasivo.',
      sourceId: 'cme-anvisa-rdc15',
    },
    {
      id: 'pegadinha-cme-indicador-quimico',
      label: 'Pegadinha — indicador químico',
      value: 'indicador químico interno não substitui indicador biológico',
      detail: 'Químico confirma exposição ao processo; biológico confirma eficácia microbicida — prova cobra a diferença.',
      sourceId: 'cme-anvisa-rdc15',
    },
  ],
};
