import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Coleta venosa e pré-analítica.
 * Fonte principal: SBPC/ML — Recomendações para Coleta de Sangue Venoso (2ª ed., 2010; ainda referência nacional).
 * Resíduos: Anvisa RDC 222/2018 (perfurocortantes = grupo E).
 */
export const COLETA_EXAMES_SBPC: GuidelineTable = {
  id: 'coleta-exames-sbpc-ml',
  snapshot: 'Coleta venosa — SBPC/ML 2ª ed. + RDC 222',
  issuer: 'SBPC/ML (tier B) / Anvisa',
  title: 'Coleta de exames laboratoriais',
  year: 2010,
  url: 'https://controllab.com/wp-content/uploads/guia_coleta_sangue.pdf',
  entries: [
    {
      id: 'veia-mediana-cubital',
      label: 'Sítio venoso preferido',
      value: 'veia mediana cubital',
      detail: 'Cefálica e basílica também usadas; cefálica mais propensa a hematoma.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'transporte-refrigerado',
      label: 'Transporte refrigerado',
      value: '2 °C a 8 °C',
      detail: 'SBPC: amostras refrigeradas em geral 4 °C a 8 °C.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'torniquete-max',
      label: 'Torniquete — tempo máximo',
      value: '1 minuto',
      detail: 'Não usar continuamente por mais de 1 minuto.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'torniquete-reposo',
      label: 'Torniquete — intervalo',
      value: '2 minutos',
      detail: 'Após afrouxar para seleção de veia, esperar 2 minutos antes de reaplicar.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'jejum-rotina',
      label: 'Jejum rotina',
      value: '8 horas',
      detail: 'Pode ser reduzido a 4 horas para maioria dos exames; evitar >16 horas.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'ordem-tubos-plastico',
      label: 'Ordem de coleta (tubos plástico)',
      value: 'hemocultura → citrato → soro → heparina → EDTA → fluoreto',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'hemocultura-primeiro',
      label: 'Primeiro tubo',
      value: 'frascos para hemocultura',
      detail: 'Sempre o primeiro na coleta múltipla a vácuo.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'segregacao-perfurocortante',
      label: 'Descarte perfurocortantes',
      value: 'recipiente próprio — não misturar com gaze ou luvas',
      detail:
        'Anvisa RDC 222/2018 — grupo E (perfurocortantes); não misturar com resíduos comuns/infectantes sem segregação.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'coagulacao-soro',
      label: 'Obtenção de soro',
      value: '30 a 60 minutos',
      detail: 'Coagulação à temperatura ambiente antes da centrifugação.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'jejum-glicemia',
      label: 'Jejum — glicemia',
      value: '8 a 12 horas',
      detail: 'Água permitida; evitar jejum >16 h (pode falsear glicemia e perfil lipídico).',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'hemograma-edta',
      label: 'Hemograma — tubo',
      value: 'EDTA (tampa roxa/lilás)',
      detail: 'Homogeneizar com 8 a 10 inversões suaves — hemólise invalida a amostra.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'coagulacao-citrato',
      label: 'Coagulação — citrato',
      value: 'tubo com tampa azul — proporção sangue:citrato 9:1',
      detail: 'Encher até a marca de vácuo; subenchimento altera TP/TTPa.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'citrato-inversao',
      label: 'Citrato — homogeneização',
      value: '3 a 4 inversões suaves',
      detail: 'Não agitar vigorosamente — evita hemólise e ativação plaquetária.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'agitacao-amostra',
      label: 'Agitação da amostra',
      value: 'inversão suave conforme anticoagulante — nunca chacoalhar',
      detail: 'SBPC: mistura inadequada falseia coagulação; excesso de agitação hemolisa.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'identificacao-tubo',
      label: 'Identificação do tubo',
      value: 'rotular imediatamente após coleta no leito',
      detail: 'Nome completo, data de nascimento, data/hora da coleta — antes de transportar.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'glicemia-tubo',
      label: 'Glicemia — tubo',
      value: 'fluoreto/oxalato (tampa cinza) ou soro com jejum',
      detail: 'Fluoreto inibe glicólise — ideal para glicemia de jejum.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'pegadinha-citrato-subenchido',
      label: 'Pegadinha coagulação',
      value: 'tubo citrato subenchido invalida TP/TTPa',
      detail: 'Proporção sangue:anticoagulante é crítica — coletar até a linha de vácuo.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'gel-separador-tubo',
      label: 'Gel separador — tubo',
      value: 'tampa amarela ou vermelha (soro com gel)',
      detail: 'Centrifugação separa soro — bioquímica, hormônios e sorologias de rotina.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'ordem-tubos-completa',
      label: 'Ordem de coleta — sequência completa',
      value: 'hemocultura → citrato → gel/soro → heparina → EDTA → fluoreto',
      detail: 'SBPC/ML — evita contaminação por anticoagulante do tubo anterior.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'edta-inversao',
      label: 'EDTA — homogeneização',
      value: '8 a 10 inversões suaves imediatamente após coleta',
      detail: 'Hemólise ou coágulos invalidam hemograma e reticulócitos.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'jejum-lipidios',
      label: 'Jejum — perfil lipídico',
      value: '12 horas (água permitida)',
      detail: 'Evitar álcool 72 h antes; jejum >16 h pode falsear triglicerídeos e LDL.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'hemocultura-esteril',
      label: 'Hemocultura — técnica estéril',
      value: 'higienizar sítio com clorexidina alcoólica; não repalpitar veia após antissepsia',
      detail: 'Primeiro tubo na coleta múltipla; 2 frascos (aeróbio + anaeróbio) quando indicado.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'hemocultura-volume',
      label: 'Hemocultura — volume',
      value: '8 a 10 mL por frasco (adulto)',
      detail: 'Volume inadequado reduz sensibilidade — seguir marca do frasco.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'transporte-temperatura-ambiente',
      label: 'Transporte — temperatura ambiente',
      value: 'coagulação e alguns bioquímicos: temperatura ambiente (18–25 °C)',
      detail: 'Nem todos os tubos vão à geladeira — seguir manual do laboratório destino.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'transporte-prazo',
      label: 'Transporte — prazo',
      value: 'processar o mais rápido possível (ideal <2 h para hemograma)',
      detail: 'Atraso altera resultados — registrar hora da coleta no tubo.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'identificacao-dois-identificadores',
      label: 'Identificação — dois identificadores',
      value: 'nome completo + data de nascimento (ou prontuário)',
      detail: 'Conferir com paciente antes da punção — reduz erro de troca.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'puncao-antebraco',
      label: 'Punção — antebraço',
      value: 'veia mediana cubital no antebraço é sítio preferencial',
      detail: 'Evitar punção repetida no mesmo sítio; alternar membros quando possível.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'puncao-angulo',
      label: 'Punção venosa — ângulo',
      value: '15° a 30° com bisel voltado para cima',
      detail: 'Introduzir agulha suavemente — não aspirar se fluxo livre em vácuo.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'agitacao-edta-suave',
      label: 'Agitação EDTA',
      value: 'inversão suave 8–10× — nunca chacoalhar',
      detail: 'Hemólise por agitação vigorosa invalida a amostra.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'soro-sem-anticoagulante',
      label: 'Soro — tubo sem anticoagulante',
      value: 'tampa vermelha (sem gel) ou amarela (com gel separador)',
      detail: 'Aguardar coagulação 30–60 min antes da centrifugação.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'heparina-tubo',
      label: 'Heparina — tubo',
      value: 'tampa verde — plasma para gases e alguns bioquímicos',
      detail: 'Posição na ordem de coleta: após citrato e soro, antes de EDTA.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'jejum-hba1c',
      label: 'Jejum — HbA1c',
      value: 'não exige jejum',
      detail: 'Pegadinha de prova — glicemia de jejum sim exige 8–12 h.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'ordem-tubos-vidro',
      label: 'Ordem de coleta — tubos de vidro',
      value: 'citrato → sem anticoagulante → heparina → EDTA → oxalato/fluoreto',
      detail: 'Se misturar vidro e plástico, seguir ordem do material predominante.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'seguranca-paciente-coleta',
      label: 'Segurança do paciente',
      value: 'identificar, explicar procedimento e posicionar adequadamente',
      detail: 'Descarte imediato de perfurocortantes em recipiente — não reencapar agulha.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'pegadinha-ordem-tubos',
      label: 'Pegadinha ordem de tubos',
      value: 'hemocultura sempre primeiro — EDTA nunca antes de citrato',
      detail: 'Contaminação cruzada falseia coagulação e hemograma.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'fezes-refrigeracao-24h',
      label: 'Fezes — refrigeração máxima',
      value: '24 horas',
      detail: 'MS Manual — refrigerar se atraso na entrega; máximo 24 h após coleta.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'fezes-quantidade-minima',
      label: 'Fezes — quantidade mínima',
      value: '10 g',
      detail: 'Amostra mínima para exames parasitológicos e coprocultura.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'urina-jato-medio',
      label: 'Urina — técnica de coleta',
      value: 'jato médio após higiene íntima',
      detail: 'Desprezar primeiro jato — reduz contaminação uretral.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'coprocultura-refrigeracao',
      label: 'Coprocultura — refrigeração',
      value: '4 °C',
      detail: 'MS — geladeira 4 °C se atraso; máximo 24 h após coleta.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'urocultura-transporte-1h',
      label: 'Urocultura — transporte',
      value: '1 hora',
      detail: 'Encaminhar urina coletada ao laboratório em até 1 hora.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
    {
      id: 'cateter-urina-seringa',
      label: 'Urina de cateter — seringa',
      value: '3 mL',
      detail: 'Seringa Luer-Lok 3 mL na porta de amostra — técnica asséptica.',
      sourceId: 'coleta-exames-sbpc-ml',
    },
  ],
};
