import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Administração segura de medicamentos — 5 e 9 certos.
 * Fontes: COFEN (Lei 7.498/86, Res. 801/2026, pareceres) + ANVISA (segurança do paciente).
 * TE administra sob supervisão; prescrição é ato do enfermeiro com protocolo (Res. 801/2026).
 */
export const CUIDADOS_ADMIN_COFEN: GuidelineTable = {
  id: 'cuidados-admin-cofen',
  snapshot: '5/9 certos + Res. COFEN 801/2026 (prescrição enfermeiro)',
  issuer: 'COFEN / ANVISA',
  title: 'Cuidados na administração de medicamentos',
  year: 2026,
  url: 'https://www.cofen.gov.br/resolucao-cofen-no-801-de-14-de-janeiro-de-2026/',
  entries: [
    {
      id: 'certo-paciente',
      label: 'Paciente certo',
      value: 'dois identificadores (nome + data de nascimento ou pulseira)',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-medicamento',
      label: 'Medicamento certo',
      value: 'conferir rótulo com prescrição',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-dose',
      label: 'Dose certa',
      value: 'quantidade exata prescrita — recalcular se necessário',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-via',
      label: 'Via certa',
      value: 'via de administração conforme prescrição (VO, IV, IM, SC, tópica)',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-hora',
      label: 'Hora certa',
      value: 'horário e intervalo prescritos',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-registro',
      label: 'Registro certo',
      value: 'registrar imediatamente após administração',
      detail: 'Não postergar para o fim do plantão.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-acao',
      label: 'Ação certa',
      value: 'verificar indicação e contraindicação',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-forma',
      label: 'Forma certa',
      value: 'apresentação e integridade da embalagem',
      detail: 'Checar validade, coloração e ausência de partículas.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'certo-resposta',
      label: 'Resposta certa',
      value: 'monitorar efeito e reação adversa',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'recusa-segura',
      label: 'Recusa na administração',
      value: 'recusar se faltar informação para prática segura',
      detail: 'Técnico executa sob supervisão do enfermeiro (Lei 7.498/86).',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'interacoes-medicamentosas',
      label: 'Interações medicamentosas',
      value: 'verificar incompatibilidade antes de administrar',
      detail: 'Conferir prescrição, bulário e interações fármaco-fármaco — especialmente polifarmácia.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'horario-terapeutico',
      label: 'Horário terapêutico',
      value: 'respeitar intervalo e horário de pico/ação',
      detail: 'Antibióticos e anti-hipertensivos: regularidade aumenta eficácia e reduz falha terapêutica.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'armazenamento-medicamento',
      label: 'Armazenamento',
      value: 'temperatura, luz e validade conforme bula',
      detail: 'Cadeia fria 2 °C a 8 °C quando indicado; insulina e vacinas fora da geladeira comum.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'medicamento-alto-risco',
      label: 'Medicamentos de alto risco',
      value: 'insulina, anticoagulantes, opioides, quimioterápicos, eletrólitos concentrados',
      detail: 'ANVISA/COFEN: exigem protocolo reforçado — rótulo, dose e via com dupla verificação.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'dupla-checagem',
      label: 'Dupla checagem',
      value: 'dois profissionais qualificados conferem dose e identificação',
      detail: 'Obrigatória para alto risco e infusões de alta vigilância — independente dos 9 certos.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'preparo-assepsia',
      label: 'Preparo asséptico',
      value: 'técnica sem contaminar ampola, seringa ou conexão',
      detail: 'Fracionar e diluir em ambiente limpo; descartar se integridade violada.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'identificacao-paciente-alto-risco',
      label: 'Identificação reforçada',
      value: 'dois identificadores antes de todo medicamento',
      detail: 'Pulseira ativa + confirmar verbalmente — nunca só quarto ou prontuário distante.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'pegadinha-dose-similar',
      label: 'Pegadinha dose',
      value: 'não confundir mg com mL nem UI com mg',
      detail: 'Unidade errada em insulina ou heparina é evento sentinela.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'nove-certos-sequencia',
      label: 'Os 9 certos — sequência de verificação',
      value: 'paciente → medicamento → dose → via → hora → registro → ação → forma → resposta',
      detail: 'Checklist antes, durante e após a administração; todos obrigatórios para prática segura.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'prescricao-enfermeiro-res-801-2026',
      label: 'Prescrição × administração (COFEN 801/2026)',
      value: 'Prescrição: enfermeiro com protocolo institucional; administração: equipe de enfermagem sob supervisão',
      detail:
        'Res. COFEN 801/2026: prescrição na consulta de enfermagem, com protocolos do serviço ou programas de saúde pública. TE administra conforme prescrição e POP — não confunde competências na prova.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'prescricao-801-elementos-minimos',
      label: 'Prescrição enfermeiro — elementos mínimos (801/2026)',
      value: 'protocolo + ano; instituição/CNPJ; identificação COREN; data; paciente; DCB + via + posologia',
      detail:
        'Art. 3º Res. COFEN 801/2026. Medicamento por denominação genérica (substância ativa). Anexo II é rol exemplificativo — estados/serviços podem ampliar via protocolo.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'alto-risco-insulina',
      label: 'Alto risco — insulina',
      value: 'conferir unidade UI, tipo (NPH, regular, análoga) e horário',
      detail: 'Nunca usar seringa de insulina para outro medicamento; dupla checagem em UTI e pediatria.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'alto-risco-heparina',
      label: 'Alto risco — heparina',
      value: 'dose em UI ou mg conforme apresentação; via SC ou IV conforme prescrição',
      detail: 'Confundir UI com mL ou trocar heparina não fracionada por de baixo peso molecular é evento crítico.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'alto-risco-kcl',
      label: 'Alto risco — cloreto de potássio (KCl)',
      value: 'nunca bolus IV em veia periférica; diluir conforme protocolo em acesso central',
      detail: 'ANVISA lista KCl concentrado como medicamento de alta vigilância — morte por arritmia se erro.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'alto-risco-quimioterapia',
      label: 'Alto risco — quimioterápicos',
      value: 'EPI, dupla checagem e preparo em área exclusiva',
      detail: 'Conferir protocolo, ciclo, superfície corporal e via (oral, IV, intratecal) — via intratecal tem protocolo apartado.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'dupla-checagem-obrigatoria',
      label: 'Dupla checagem — quando é obrigatória',
      value: 'insulina, anticoagulantes, opioides, eletrólitos concentrados, quimioterápicos e infusões',
      detail: 'Dois profissionais independentes; um prepara e outro confere — não basta reler sozinho.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'identificadores-dois-ativos',
      label: 'Dois identificadores — exemplos válidos',
      value: 'nome completo + data de nascimento ou número de prontuário/pulseira',
      detail: 'Perguntar ao paciente (se orientado); nunca identificar só pelo leito ou quarto.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'horario-terapeutico-janela',
      label: 'Horário terapêutico — janela de administração',
      value: 'administrar dentro da janela institucional (ex.: ±30 min ou ±1 h conforme protocolo)',
      detail: 'Antibiótico de tempo dependente: manter intervalo regular; não acumular doses atrasadas.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'interacao-farmaco-alimento',
      label: 'Interação medicamentosa — alimentos',
      value: 'verificar jejum, refeição ou separação de horário (ex.: levotiroxina, tetraciclinas)',
      detail: 'Suco de grapefruit e alguns antiarrítmicos — conferir bula e prescrição antes de administrar.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'armazenamento-pos-abertura',
      label: 'Validade após abertura',
      value: 'seguir bula para uso após aberto (ampola, frasco multidose, insulina em uso)',
      detail: 'Anotar data/hora de abertura no rótulo; descartar se prazo ou aspecto alterado.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'validade-aberto-ampola',
      label: 'Ampola aberta — tempo de uso',
      value: 'usar imediatamente ou em até 24 h se refrigerada e protocolo permitir',
      detail: 'Pegadinha: ampola aberta não vale até validade impressa na embalagem fechada.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'recusa-documentada',
      label: 'Recusa documentada',
      value: 'registrar no prontuário: medicamento, motivo, orientação dada e quem recusou',
      detail: 'Comunicar enfermeiro/médico; não administrar sem prescrição válida ou identificação segura.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'erro-medicacao-notificar',
      label: 'Erro de medicação — fluxo',
      value: 'interromper, avaliar paciente, notificar enfermeiro/médico e registrar incidente',
      detail: 'Notificação interna (notivisa institucional) e suporte ao paciente — nunca ocultar.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'erro-medicacao-cultura-justa',
      label: 'Cultura de segurança',
      value: 'reportar near miss e erro sem retaliação ao profissional que notifica',
      detail: 'Foco em falha de sistema, não em punir quem aplicou os 9 certos e identificou o risco.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'preparo-sem-contaminar',
      label: 'Preparo — evitar contaminação',
      value: 'não tocar parte estéril da agulha, seringa ou equipo; técnica asséptica na ampola',
      detail: 'Alcoolizar rolha, secar, usar dispositivo de transferência; descartar se tocar superfície não estéril.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'lavagem-maos-medicacao',
      label: 'Higienização das mãos',
      value: 'lavar ou friccionar com álcool 70% antes e após preparo e administração',
      detail: 'Medida simples que reduz contaminação e infecção associada a cuidados — obrigatória antes do preparo.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'crush-comprimido-liberado',
      label: 'Esmagar comprimido (crush)',
      value: 'somente se prescrição e farmácia liberarem — verificar se formulário permite',
      detail: 'Comprimidos de liberação prolongada, entéricos ou quimioterápicos: nunca esmagar sem validação.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'via-errada-nunca',
      label: 'Via errada — conduta',
      value: 'não administrar; manter medicamento, comunicar enfermeiro e registrar incidente',
      detail: 'Ex.: prescrito IV e preparado IM — descartar preparo se contaminado e refazer após nova conferência.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'pegadinha-via-vo-iv',
      label: 'Pegadinha — via VO para IV',
      value: 'nunca converter via sem nova prescrição médica',
      detail: 'Medicamento VO pode não ser estéril ou ter pH incompatível com IV — erro fatal em prova e prática.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'pegadinha-hora-dose-duplicada',
      label: 'Pegadinha — dose atrasada',
      value: 'não dobrar dose nem adiantar a próxima sem orientação',
      detail: 'Consultar enfermeiro/médico; intervalo mínimo entre doses deve ser respeitado.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'pegadinha-identificacao-quarto',
      label: 'Pegadinha — identificar pelo quarto',
      value: 'quarto ou leito sozinho não identifica o paciente',
      detail: 'Dois identificadores no paciente — troca de leito sem atualizar pulseira é causa clássica de erro.',
      sourceId: 'cuidados-admin-cofen',
    },
    {
      id: 'pegadinha-alto-risco-sem-dupla',
      label: 'Pegadinha — alto risco sem dupla checagem',
      value: '9 certos não dispensam dupla checagem em medicamentos de alta vigilância',
      detail: 'Insulina e heparina exigem os 9 certos e segundo conferente qualificado.',
      sourceId: 'cuidados-admin-cofen',
    },
    // — Valores discretos cobrados em prova (corpus factcheck) —
    {
      id: 'cuidados-prova-doses-intervalos',
      label: 'Doses e intervalos — casos de prova',
      value:
        '8 horas · 12 horas · 24 horas · 6 horas · 30 minutos · 1 hora · 2 horas · 500 mg · 1 g · 10 ml · 5 ml',
      detail: 'Intervalos entre doses, horários e volumes citados literalmente em prova.',
      sourceId: 'cuidados-admin-cofen',
    },
  ],
};
