import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Curativos, LPP e coberturas.
 * Referência: NPUAP/EPUAP (estágios LPP), COFEN, MS.
 */
export const CURATIVOS_LPP_NPUAP: GuidelineTable = {
  id: 'curativos-lpp-npuap',
  snapshot: 'LPP, estágios e coberturas',
  issuer: 'NPUAP/COFEN',
  title: 'Curativos e manejo de feridas',
  year: 2016,
  url: 'https://www.cofen.gov.br/',
  entries: [
    {
      id: 'lpp-prevencao-pele',
      label: 'Prevenção LPP — pele',
      value: 'limpa e seca — não úmida',
      detail: 'Maceração favorece lesão por pressão.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-ph',
      label: 'pH cutâneo',
      value: 'evitar sabonetes e produtos alcalinos',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-massagem',
      label: 'Proeminências ósseas',
      value: 'não massagear áreas hiperemiadas',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-calcanhar',
      label: 'Calcanhar',
      value: 'alívio de pressão — calcanhar livre ou suspensão',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-estagio-i',
      label: 'LPP estágio I',
      value: 'eritema não branqueável — pele íntegra',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-estagio-ii',
      label: 'LPP estágio II',
      value: 'perda parcial da derme — flictena ou leito róseo',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-estagio-iii',
      label: 'LPP estágio III',
      value: 'perda total da espessura cutânea — subcutâneo visível',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-estagio-iv',
      label: 'LPP estágio IV',
      value: 'exposição de osso, tendão ou músculo',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'braden-risco',
      label: 'Escala de Braden — risco',
      value: '≤18 pontos = risco de LPP',
      detail: '≤12 alto risco; ≤9 risco muito alto.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'limpeza-sf',
      label: 'Limpeza do leito',
      value: 'SF 0,9%',
      detail: 'Padrão; evitar antissépticos citotóxicos de rotina no leito.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-exsudato-alto',
      label: 'Exsudato alto',
      value: 'alginato ou espuma',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-exsudato-baixo',
      label: 'Exsudato baixo',
      value: 'hidrocoloide ou filme transparente',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-tipos',
      label: 'Tipos de cobertura',
      value: 'secas (gaze), úmidas (hidrogel), absorventes (alginato/espuma), oclusivas (filme/hidrocoloide)',
      detail: 'Escolha conforme leito, exsudato e objetivo (proteção, desbridamento ou absorção).',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-exsudato-moderado',
      label: 'Exsudato moderado',
      value: 'espuma de poliuretano ou hidrofibra',
      detail: 'Trocar quando saturação visual ou vazamento — manter perilesional íntegro.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'biofilme-leito',
      label: 'Biofilme',
      value: 'colônia bacteriana aderida ao leito — retarda cicatrização',
      detail: 'Desbridamento, limpeza e cobertura adequada; antisséptico de rotina no leito não substitui desbridamento.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'curativo-oclusivo',
      label: 'Curativo oclusivo',
      value: 'mantém ambiente úmido e protege barreira cutânea',
      detail: 'Hidrocoloide e filme transparente — contraindicado em infecção não controlada ou exsudato maciço.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'sinais-infeccao-ferida',
      label: 'Sinais de infecção no leito',
      value: 'exsudato purulento, odor fétido, eritema perilesional, dor aumentada, febre',
      detail: 'Biofilme e necrose também atrasam cicatrização — avaliar cultura e conduta médica.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'desbridamento',
      label: 'Desbridamento',
      value: 'remoção de tecido necrótico ou não viável',
      detail: 'Autolítico (hidrogel), enzimático ou instrumental — prepara leito para granulação.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'leito-granulacao',
      label: 'Leito de granulação',
      value: 'tecido vermelho vivo, úmido e sangrante leve',
      detail: 'Manter úmido (hidrogel/espuma) — evitar desidratação e trauma mecânico.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-necrose',
      label: 'Necrose no leito',
      value: 'esfacelo amarelado ou escara necrótica — exige desbridamento',
      detail: 'Escara negra estável em calcanhar pode ser protegida sem desbridamento agressivo (avaliação individual).',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'braden-subescalas',
      label: 'Braden — subescalas',
      value: 'percepção sensorial, umidade, atividade, mobilidade, nutrição e fricção/cisalhamento',
      detail: 'Cada item 1–4 (exceto fricção 1–3); soma ≤18 indica risco de LPP.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-dti',
      label: 'LPP — lesão de tecido profundo (DTI)',
      value: 'pele íntegra com equimose persistente ou bolha de sangue — suspeita de dano em fascia/músculo',
      detail: 'NPUAP — não subestimar; documentar e aliviar pressão imediatamente.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'lpp-inclassificavel',
      label: 'LPP inclassificável',
      value: 'leito coberto por esfacelo ou escara — estágio não visível até desbridamento',
      detail: 'Registrar como inclassificável; remover necrose para estadiar corretamente.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'dam-umidade',
      label: 'Dermatite associada à umidade (DAU)',
      value: 'maceração por incontinência, transpiração ou exsudato — não é LPP',
      detail: 'Proteção cutânea, barreira e controle da umidade; diferenciar de estágio I de LPP.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-prata',
      label: 'Cobertura com prata',
      value: 'ação antimicrobiana em feridas colonizadas ou com biofilme',
      detail: 'Hidrofibra ou espuma com prata — avaliar toxicidade por absorção em feridas extensas.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-alginato',
      label: 'Cobertura de alginato',
      value: 'absorção de exsudato moderado a alto — forma gel ao contato',
      detail: 'Indicado em leitos com exsudação; trocar quando saturação ou conforme protocolo.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'cobertura-hidrocoloide',
      label: 'Cobertura hidrocoloide',
      value: 'oclusiva, ambiente úmido — exsudato baixo a moderado',
      detail: 'Autólise de esfacelo leve; contraindicada em infecção não controlada ou maceração perilesional.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'terapia-pressao-negativa',
      label: 'Terapia por pressão negativa (TPN)',
      value: 'vácuo contínuo ou intermitente — estimula granulação e reduz edema',
      detail: 'Contraindicada em necrose não desbridada, fístulas não exploradas e malignidade no leito.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'desbridamento-tipos',
      label: 'Desbridamento — tipos',
      value: 'autolítico, enzimático, instrumental (cirúrgico) e biológico',
      detail: 'Escolha conforme leito, dor, vascularização e objetivo terapêutico.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'sinais-infeccao-ferida-detalhe',
      label: 'Sinais de infecção na ferida',
      value: 'eritema perilesional, calor, edema, odor, exsudato purulento e atraso na cicatrização',
      detail: 'Biofilme pode persistir sem pus franco — cultura e conduta médica quando indicado.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'pegadinha-massagem-lpp',
      label: 'Pegadinha — massagem em proeminências',
      value: 'não massagear pele hiperemiada ou sobre proeminências ósseas',
      detail: 'Massagem não previne LPP — alívio de pressão e reposicionamento são as medidas corretas.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'braden-intervencoes',
      label: 'Braden — intervenções por risco',
      value: '≤12 alto risco: reposicionamento 2/2 h, superfície de alívio, nutrição',
      detail: '≤9 risco muito alto — protocolo intensivo; reavaliar a cada mudança clínica.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'maceracao-perilesional',
      label: 'Maceração perilesional',
      value: 'pele saturada por exsudato — aumenta risco de extensão da lesão',
      detail: 'Protetor de barreira, ajuste da cobertura absorvente e controle da umidade.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'biofilme-manejo',
      label: 'Biofilme — manejo',
      value: 'desbridamento + limpeza + cobertura adequada — antisséptico de rotina não elimina biofilme',
      detail: 'Colônia aderida retarda cicatrização; prata ou PHMB podem ser adjuvantes conforme protocolo.',
      sourceId: 'curativos-lpp-npuap',
    },
    {
      id: 'umidade-leito-ferida',
      label: 'Balanço de umidade do leito',
      value: 'leito úmido (granulação) vs excesso de exsudato (maceração)',
      detail: 'Hidrogel/espuma para leito seco; alginato/espuma para exsudato alto — individualizar.',
      sourceId: 'curativos-lpp-npuap',
    },
  ],
};
