import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Conceitos fundamentais de farmacodinâmica e farmacocinética.
 * Referência: Protocolo MS/Anvisa Segurança na prescrição, uso e administração (ainda vigente)
 * + bulário Anvisa / literatura técnica de enfermagem.
 * @see https://www.gov.br/saude/pt-br/composicao/saes/seguranca-do-paciente/protocolos-de-seguranca-do-paciente/protocolo-seguraca-na-prescricao-uso-e-administracao-de-medicamentos.pdf
 */
export const FARMACO_ADME_BR: GuidelineTable = {
  id: 'farmaco-adme-anvisa',
  snapshot: 'ADME + alta vigilância (Protocolo MS/Anvisa medicamentos)',
  issuer: 'Anvisa / Ministério da Saúde',
  title: 'Farmacodinâmica e farmacocinética',
  year: 2026,
  url: 'https://www.gov.br/saude/pt-br/composicao/saes/seguranca-do-paciente/protocolos-de-seguranca-do-paciente/protocolo-seguraca-na-prescricao-uso-e-administracao-de-medicamentos.pdf',
  entries: [
    {
      id: 'adme-absorcao',
      label: 'Absorção',
      value: 'passagem do fármaco ao sangue',
      detail: 'Primeira fase da farmacocinética (ADME).',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'adme-distribuicao',
      label: 'Distribuição',
      value: 'dispersão pelo organismo',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'adme-metabolismo',
      label: 'Metabolismo',
      value: 'biotransformação hepática (fígado)',
      detail: 'Efeito de primeira passagem na via oral.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'adme-excrecao',
      label: 'Excreção',
      value: 'eliminação renal ou biliar',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'biodisponibilidade-ev',
      label: 'Biodisponibilidade EV',
      value: '100%',
      detail: 'Via endovenosa dispensa absorção — ação imediata.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'meia-vida',
      label: 'Meia-vida (t½)',
      value: 'tempo para reduzir concentração plasmática pela metade',
      detail: 'Define intervalo de doses e tempo até estado de equilíbrio.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'farmacodinamica-def',
      label: 'Farmacodinâmica',
      value: 'efeito do fármaco no organismo',
      detail: 'Dose-resposta, agonismo e antagonismo.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'indice-terapeutico',
      label: 'Índice terapêutico estreito',
      value: 'pequena margem entre dose terapêutica e tóxica',
      detail: 'Ex.: digoxina, fenitoína, varfarina — exige monitorização.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'potencia-eficacia',
      label: 'Potência × eficácia',
      value: 'potência = dose necessária; eficácia = efeito máximo',
      detail: 'Pegadinha: fármaco mais potente não é necessariamente mais eficaz.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'agonista',
      label: 'Agonista',
      value: 'liga-se ao receptor e ativa a resposta fisiológica',
      detail: 'Pode ser total (máximo efeito) ou parcial (teto abaixo do endógeno).',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'antagonista',
      label: 'Antagonista',
      value: 'liga-se ao receptor sem ativar — bloqueia o agonista',
      detail: 'Ex.: naloxona (opioides), propranolol (beta-bloqueador).',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'antagonista-competitivo',
      label: 'Antagonista competitivo',
      value: 'compete pelo mesmo sítio — efeito reversível com dose de agonista',
      detail: 'Diferente do não competitivo, que altera afinidade ou via intracelular.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'tolerancia',
      label: 'Tolerância',
      value: 'diminuição da resposta com uso repetido do fármaco',
      detail: 'Exige aumento de dose para manter efeito — comum em opioides e benzodiazepínicos.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'dependencia',
      label: 'Dependência',
      value: 'necessidade de continuar o fármaco para evitar mal-estar ou abstinência',
      detail: 'Pode ser física (síndrome de abstinência) ou psicológica (desejo compulsivo).',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'meia-vida-clinica',
      label: 'Meia-vida clínica',
      value: 'tempo para o efeito farmacológico cair à metade',
      detail: 'Pode diferir da meia-vida plasmática — orienta intervalo entre doses e início de ação.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'primeira-passagem-hepatica',
      label: 'Primeira passagem hepática',
      value: 'metabolismo hepático pré-sistêmico após absorção oral',
      detail: 'Reduz biodisponibilidade na VO — vias sublingual, retal e EV a contornam parcial ou totalmente.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'sindrome-abstinencia',
      label: 'Síndrome de abstinência',
      value: 'surgimento de sintomas ao suspender fármaco de que o organismo depende',
      detail: 'Opioides, benzodiazepínicos e álcool — exige desmame gradual supervisionado.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'receptor-chave-fechadura',
      label: 'Receptor — modelo chave-fechadura',
      value: 'fármaco (chave) liga-se a sítio específico do receptor (fechadura)',
      detail: 'Especificidade determina efeito farmacológico; alterações no receptor mudam a resposta.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'agonista-parcial',
      label: 'Agonista parcial',
      value: 'ativa o receptor, mas o efeito máximo é menor que o agonista total',
      detail: 'Ex.: buprenorfina (opioides) — pode antagonizar agonista pleno no mesmo receptor.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'cyp450-metabolismo',
      label: 'CYP450 (citocromo P450)',
      value: 'enzimas hepáticas que metabolizam a maioria dos fármacos',
      detail: 'Isoformas CYP3A4, CYP2D6, CYP2C9 — polimorfismos e interações medicamentosas.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'ligacao-proteica-plasma',
      label: 'Ligação a proteínas plasmáticas',
      value: 'fármaco ligado à albumina não é farmacologicamente ativo',
      detail: 'Apenas fração livre atravessa membranas e exerce efeito; deslocamento aumenta toxicidade.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'ajuste-dose-renal',
      label: 'Ajuste de dose — função renal',
      value: 'reduzir dose ou aumentar intervalo quando ClCr diminui',
      detail: 'Fármacos de eliminação predominantemente renal (ex.: aminoglicosídeos, metformina) exigem monitorização.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'ajuste-dose-hepatico',
      label: 'Ajuste de dose — função hepática',
      value: 'cautela em hepatopatia — metabolismo hepático comprometido',
      detail: 'Child-Pugh orienta ajuste; evitar hepatotóxicos em insuficiência hepática grave.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'primeira-passagem-exemplos',
      label: 'Primeira passagem — exemplos',
      value: 'morfina VO tem biodisponibilidade ~30%; propranolol ~25%',
      detail: 'Nitroglicerina sublingual evita degradação hepática; comparar VO × sublingual × EV.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'inducao-inibicao-cyp450',
      label: 'Indução × inibição enzimática',
      value: 'indutor acelera metabolismo (↓efeito); inibidor retarda (↑efeito/toxicidade)',
      detail: 'Ex.: rifampicina (indutor CYP3A4); cetoconazol (inibidor) — interações clínicas relevantes.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'faixa-terapeutica-estreita',
      label: 'Faixa terapêutica estreita',
      value: 'dose terapêutica próxima da tóxica — monitorar níveis séricos',
      detail: 'Lítio, digoxina, fenitoína, varfarina: dosagem individualizada e acompanhamento laboratorial.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'pegadinha-generico-similar',
      label: 'Pegadinha genérico × similar',
      value: 'genérico tem mesmo princípio ativo, dose e via; similar pode ter excipientes diferentes',
      detail: 'Intercambialidade biofarmacêutica do genérico; similar exige prescrição pelo nome comercial.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'pegadinha-tolerancia-dependencia',
      label: 'Pegadinha tolerância × dependência',
      value: 'tolerância = perda de efeito; dependência = mal-estar ao suspender',
      detail: 'Podem coexistir (opioides), mas são mecanismos distintos — banca troca definições.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'pegadinha-biodisponibilidade-vo',
      label: 'Pegadinha biodisponibilidade VO',
      value: 'via oral nem sempre equivale à dose EV — primeira passagem reduz fração ativa',
      detail: 'Comparar mg VO × mg EV sem fator de conversão é erro clássico de prova.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'midazolam-metabolitos-ativos',
      label: 'Midazolam — metabólitos ativos',
      value: 'biotransformação hepática; acúmulo em infusão prolongada na UTI',
      detail: 'Despertar tardio pós-suspensão — sedação residual por metabólitos ativos.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'antagonista-inverso',
      label: 'Antagonista inverso',
      value: 'reduz atividade basal do receptor abaixo do repouso',
      detail: 'Diferente do antagonista neutro (bloqueia sem alterar basal) e do agonista inverso.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'alta-vigilancia-ms-anvisa',
      label: 'Medicamentos de alta vigilância',
      value: 'maior potencial de dano grave se erro — lista institucional obrigatória',
      detail:
        'Protocolo MS/Anvisa: destacar anticoagulantes, opioides, insulina e eletrólitos concentrados (ex.: KCl injetável); limitar apresentações e usar dupla checagem.',
      sourceId: 'farmaco-adme-anvisa',
    },
    {
      id: 'biodisponibilidade-def',
      label: 'Biodisponibilidade',
      value: 'fração da dose que alcança a circulação sistêmica inalterada',
      detail: 'EV = 100%; VO reduzida por absorção incompleta e primeira passagem hepática.',
      sourceId: 'farmaco-adme-anvisa',
    },
  ],
};
