import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * História da enfermagem e marcos regulatórios brasileiros.
 * Fonte: COFEN — Código de Ética e historiografia clássica.
 */
export const HISTORIA_ENFERMAGEM_COFEN: GuidelineTable = {
  id: 'historia-enfermagem-cofen',
  snapshot: 'Nightingale, COFEN e ética profissional',
  issuer: 'COFEN',
  title: 'História da Enfermagem',
  year: 2024,
  url: 'https://www.cofen.gov.br/',
  entries: [
    {
      id: 'nightingale',
      label: 'Florence Nightingale',
      value: 'fundadora da enfermagem moderna',
      detail: 'Guerra da Crimeia: higiene, ventilação, registro de mortalidade.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'cofen-papel',
      label: 'COFEN',
      value: 'Conselho Federal de Enfermagem',
      detail: 'Normatiza e fiscaliza o exercício profissional no Brasil.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'coren-papel',
      label: 'COREN',
      value: 'fiscalização estadual do exercício profissional',
      detail: 'Não confundir com COFEN — Código de Ética é norma do COFEN.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'codigo-etica',
      label: 'Código de Ética',
      value: 'norma do COFEN que orienta conduta da categoria',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'enfermagem-brasil-pre-sus',
      label: 'Enfermagem no Brasil',
      value: 'raízes anteriores ao SUS (1988)',
      detail: 'Escolas e regulamentação vêm do século XX — SUS reorganizou o sistema.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'pegadinha-sus',
      label: 'Pegadinha SUS',
      value: 'enfermagem não surgiu apenas após criação do SUS',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'eulalia-paiva-queiroz',
      label: 'Eulália Paiva de Queiroz',
      value: 'pioneira da enfermagem brasileira — Escola Anna Nery (RJ)',
      detail: 'Primeira escola de enfermagem do Brasil (1890); formou gerações de enfermeiras profissionais.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'ana-neri',
      label: 'Ana Néri',
      value: 'heroína da Guerra do Paraguai — símbolo da enfermagem no Brasil',
      detail: 'Voluntária que cuidou de feridos; não foi a primeira enfermeira diplomada, mas marco histórico nacional.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'lei-7498-86',
      label: 'Lei 7.498/86',
      value: 'regulamenta o exercício da enfermagem no Brasil',
      detail: 'Define atribuições de enfermeiro, técnico e auxiliar; base legal junto ao Decreto 94.406/87.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'florence-creditos',
      label: 'Florence Nightingale — legado',
      value: 'enfermagem científica, estatística sanitária e cuidado humanizado',
      detail: 'Reduziu mortalidade no hospital de Scutari; "A Dama da Lâmpada" — fundadora da enfermagem moderna.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'ona-acreditacao',
      label: 'ONA',
      value: 'Organização Nacional de Acreditação — certificação de serviços de saúde',
      detail: 'Acreditação hospitalar (níveis 1 a 3); promove qualidade e segurança do paciente.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'decreto-94406-87',
      label: 'Decreto 94.406/87',
      value: 'regulamenta a Lei 7.498/86 — atividades privativas por categoria',
      detail: 'Diferencia atribuições de enfermeiro, técnico e auxiliar — frequentemente cobrado em prova.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'escola-anna-nery',
      label: 'Escola Anna Nery',
      value: 'primeira escola de enfermagem do Brasil (1890, Rio de Janeiro)',
      detail: 'Fundada por Eulália Paiva de Queiroz — marco da profissionalização nacional.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'pegadinha-ana-eulalia',
      label: 'Pegadinha pioneiras',
      value: 'Ana Néri é símbolo histórico; Eulália Paiva fundou a primeira escola formal',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'getulio-vargas-regulamentacao',
      label: 'Era Getúlio Vargas',
      value: 'Estado Novo e políticas de saúde pública — expansão de formação e serviços',
      detail: 'Década de 1930–40: reorganização sanitária e marcos para profissões da saúde no Brasil.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'ufsc-enfermagem',
      label: 'UFSC — enfermagem no Brasil',
      value: 'Universidade Federal de Santa Catarina — referência na formação superior de enfermagem',
      detail: 'Cursos universitários consolidam a enfermagem como graduação e pesquisa no país.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'dia-internacional-enfermagem',
      label: 'Dia Internacional da Enfermagem',
      value: '12 de maio — aniversário de Florence Nightingale',
      detail: 'Celebrado mundialmente desde 1965 (ICN); homenagem à categoria e à pioneira da Crimeia.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'florence-crimeia-estatisticas',
      label: 'Florence — Guerra da Crimeia',
      value: 'reduziu mortalidade hospitalar de ~40% para ~2% com higiene e saneamento',
      detail: 'Estatísticas e gráficos de Nightingale (coxcomb) — base da enfermagem científica.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'teoria-peplau',
      label: 'Teoria de Peplau',
      value: 'relações interpessoais enfermeiro–paciente — fases: orientação, identificação, exploração e resolução',
      detail: 'Hildegard Peplau — enfermagem psiquiátrica e cuidado terapêutico centrado na relação.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'etica-autonomia-beneficencia',
      label: 'Ética — autonomia e beneficência',
      value: 'respeitar decisão do paciente (autonomia) e agir para o bem (beneficência)',
      detail: 'Princípios do Código de Ética COFEN — junto com não maleficência, justiça e dignidade.',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'henrique-dutra-vargas',
      label: 'Marco sanitário brasileiro',
      value: 'políticas de saúde e formação profissional no século XX',
      detail: 'Contexto histórico da profissionalização da enfermagem antes e após o SUS (1988).',
      sourceId: 'historia-enfermagem-cofen',
    },
    {
      id: 'teorias-enfermagem-classicas',
      label: 'Teorias clássicas de enfermagem',
      value: 'Nightingale (ambiente), Peplau (relação), Henderson (necessidades básicas)',
      detail: 'Fundamentos para o Processo de Enfermagem e prática baseada em evidências.',
      sourceId: 'historia-enfermagem-cofen',
    },
  ],
};
