import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Prevenção e vigilância de ISTs.
 * Fonte: MS/SVS — PCDT e protocolos de prevenção combinada.
 */
export const ISTS_PREVENCAO_MS: GuidelineTable = {
  id: 'ists-prevencao-ms',
  snapshot: 'IST — rotas de risco e prevenção MS',
  issuer: 'Ministério da Saúde',
  title: 'Infecções sexualmente transmissíveis — prevenção',
  year: 2022,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/i/infeccoes-sexualmente-transmissiveis',
  entries: [
    {
      id: 'ist-via-sexual',
      label: 'Via sexual',
      value: 'relação sexual sem preservativo aumenta risco',
      detail: 'Barreira mecânica (camisinha) é central na prevenção.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'ist-parceria-risco',
      label: 'Parceria de risco',
      value: 'parceiro com relações desprotegidas com terceiros',
      detail: 'Exposição indireta também eleva o risco.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'ist-via-parenteral',
      label: 'Via parenteral',
      value: 'compartilhamento de seringas e agulhas',
      detail: 'Agulha de uso exclusivamente pessoal não é fator de risco na assertiva típica de prova.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'ist-preservativo',
      label: 'Preservativo',
      value: 'barreira mecânica na prevenção sexual',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'ist-notificacao',
      label: 'Notificação compulsória',
      value: 'HIV, sífilis e hepatites virais',
      detail: 'Integra vigilância epidemiológica.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'ist-pep-janela',
      label: 'PEP HIV — janela',
      value: 'até 72 horas',
      detail: 'Profilaxia pós-exposição — quanto antes, melhor.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'ist-agentes',
      label: 'Agentes cobrados',
      value: 'HIV, sífilis, hepatites B/C, HPV, clamídia, gonorreia',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'ist-testagem',
      label: 'Testagem',
      value: 'diagnóstico precoce e tratamento oportuno',
      detail: 'Prevenção combinada: testar, tratar, usar preservativo.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'sifilis-triagem',
      label: 'Sífilis — triagem',
      value: 'VDRL ou RPR (teste não treponêmico)',
      detail: 'Confirmar com FTA-Abs ou teste treponêmico; tratamento: penicilina benzatina (PCDT MS).',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'hiv-teste-rapido',
      label: 'HIV — testagem',
      value: 'teste rápido de 4ª geração (antígeno + anticorpo)',
      detail: 'Janela imunológica ~30 dias; reagente exige confirmação (carga viral ou Western blot).',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'hepatite-b-ist',
      label: 'Hepatite B — IST',
      value: 'HBsAg, anti-HBc e anti-HBs na investigação',
      detail: 'Vacinação pelo PNI previne transmissão sexual e parenteral; notificação compulsória.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'hpv-prevencao',
      label: 'HPV',
      value: 'vacina quadrivalente/nonavalente no PNI + rastreio citológico',
      detail: 'Citologia oncótica (Papanicolau) para prevenção de câncer de colo — não substitui vacinação.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'clamidia-screening',
      label: 'Clamídia — rastreio',
      value: 'NAAT (urina ou swab endocervical/uretral)',
      detail: 'Infecção frequentemente assintomática — tratar parceiro(s) e orientar preservativo.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'gonorreia-screening',
      label: 'Gonorreia — rastreio',
      value: 'cultura ou NAAT de secreção uretral/cervical',
      detail: 'Coinfecção com clamídia é comum — PCDT MS recomenda tratar ambas quando diagnosticada uma.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'testagem-oferta-ativa',
      label: 'Testagem — oferta ativa',
      value: 'oferecer teste rápido HIV/sífilis/hepatites em toda consulta de IST',
      detail: 'Política MS de prevenção combinada — reduz transmissão não diagnosticada.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'sifilis-gestante',
      label: 'Sífilis na gestação',
      value: 'triagem no 1º trimestre, 3º trimestre e parto',
      detail: 'Tratamento inadequado causa sífilis congênita — penicilina benzatina é droga de escolha.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'sifilis-estadios',
      label: 'Sífilis — estadios clínicos',
      value: 'primária (cancro) · secundária (rash) · latente · terciária',
      detail: 'Primária: lesão indolor; secundária: exantema palmoplantar; latente: sorologia positiva sem sinais; terciária: cardiovascular/neurológica.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'hiv-janela-imunologica',
      label: 'HIV — janela imunológica',
      value: 'até ~30 dias (4ª geração) · até ~90 dias (3ª geração)',
      detail: 'Exposição recente com teste não reagente pode exigir repetição após janela; PEP não substitui testagem seriada.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'hepatite-c-ist',
      label: 'Hepatite C — IST',
      value: 'anti-HCV e HCV-RNA na investigação',
      detail: 'Transmissão sexual menos eficiente que HBV/HIV, mas ocorre; coinfecção HIV-HCV eleva risco; notificação compulsória.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'hpv-transmissao-ist',
      label: 'HPV — transmissão sexual',
      value: 'contato pele a pele — preservativo reduz mas não elimina risco',
      detail: 'Lesões genitais e orofaríngeas; vacinação PNI antes do início da vida sexual é prevenção primária.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'clamidia-tratamento',
      label: 'Clamídia — tratamento',
      value: 'azitromicina ou doxiciclina (PCDT MS)',
      detail: 'Tratar parceiro(s) simultaneamente; abstinência sexual até cura; rastreio em gestantes e populações de risco.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'gonorreia-tratamento',
      label: 'Gonorreia — tratamento',
      value: 'ceftriaxona IM + azitromicina (coinfecção clamídia)',
      detail: 'Resistência antimicrobiana crescente — não tratar com quinolona isolada sem cultura/sensibilidade.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'tricomonas-ist',
      label: 'Tricomoníase',
      value: 'Trichomonas vaginalis — corrimento espumoso, prurido, colo em framboesa',
      detail: 'Tratamento: metronidazol ou tinidazol; tratar parceiro(s); IST frequente e subnotificada.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'preservativo-uso-correto',
      label: 'Preservativo — uso correto',
      value: 'látex ou poliuretano · do início ao fim da relação · sem reutilização',
      detail: 'Verificar validade e integridade; lubrificante à base de água com látex; prevenção combinada com testagem e tratamento.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'prep-hiv',
      label: 'PrEP HIV',
      value: 'profilaxia pré-exposição com antirretrovirais para populações de alto risco',
      detail: 'Diferente da PEP (pós-exposição 72h); exige adesão, testagem prévia e acompanhamento — MS/SVS.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'notificacao-parceiros',
      label: 'Notificação de parceiros',
      value: 'orientar comunicação e busca ativa de contactantes',
      detail: 'Sigilo profissional preservado; enfermagem apoia rastreio de parceiros em sífilis, HIV e outras ISTs.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'gestante-ist-geral',
      label: 'IST na gestação',
      value: 'rastreio HIV, sífilis, hepatite B e HBV na rotina pré-natal',
      detail: 'Tratamento materno reduz transmissão vertical; penicilina benzatina na sífilis gestacional é obrigatória.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'sifilis-congenita',
      label: 'Sífilis congênita',
      value: 'transmissão vertical por falha de rastreio/tratamento na gestação',
      detail: 'Prevenção: triagem seriada da gestante e tratamento adequado; notificação compulsória do caso.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'pegadinha-agulha-unica',
      label: 'Pegadinha via parenteral',
      value: 'agulha de uso exclusivamente pessoal não é fator de risco',
      detail: 'Compartilhamento de seringas/agulhas sim — assertiva típica de prova inverte o conceito.',
      sourceId: 'ists-prevencao-ms',
    },
    {
      id: 'pegadinha-pep-prep',
      label: 'Pegadinha PEP × PrEP',
      value: 'PEP é pós-exposição (72h); PrEP é antes da exposição',
      detail: 'Confundir janelas e indicações é pegadinha frequente — nenhuma substitui preservativo e testagem.',
      sourceId: 'ists-prevencao-ms',
    },
  ],
};
