import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Dispositivos de O₂ — fluxos e FiO₂.
 * Fontes: MS (orientações O₂ COVID-19/CONITEC), POP HU-UFGD oxigenoterapia.
 */
export const OXIGENOTERAPIA_DISPOSITIVOS_MS: GuidelineTable = {
  id: 'oxigenoterapia-dispositivos-ms',
  snapshot: 'Oxigenoterapia — dispositivos, fluxo e FiO₂',
  issuer: 'Ministério da Saúde',
  title: 'Oxigenoterapia e cuidados respiratórios',
  year: 2021,
  url: 'https://www.gov.br/conitec/pt-br/midias/relatorios/diretrizesbrasileiras_tratamentohospitalarpaciente_capi.pdf',
  entries: [
    {
      id: 'cna-baixo-fluxo',
      label: 'Cateter nasal (CNA)',
      value: '1 a 6 L/min',
      detail: 'Dispositivo de baixo fluxo; mensurar comprimento na narina.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'cna-fio2',
      label: 'FiO₂ cateter nasal',
      value: '21 a 44%',
      detail: 'FiO₂ variável conforme fluxo e padrão respiratório.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'venturi-fio2',
      label: 'Máscara Venturi',
      value: 'FiO₂ controlada por diluidores (24%, 28%, 31%, 35%, 40%, 50%)',
      detail: 'Alto fluxo com FiO₂ precisa — não é máscara facial simples.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'mascara-simples-fluxo',
      label: 'Máscara facial simples',
      value: '4 a 15 L/min',
      detail: 'FiO₂ aproximada 40 a 60%.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'mascara-nao-reinalante',
      label: 'Máscara não reinalante (reservatório)',
      value: '7 a 10 L/min',
      detail: 'FiO₂ aproximada 60 a 100%; fluxo mínimo adequado obrigatório.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'spo2-meta-geral',
      label: 'Meta SpO₂ (titulação)',
      value: '90 a 94%',
      detail: 'Reduzir fluxo se SpO₂ acima de 94%.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'spo2-dpoc-retentor',
      label: 'SpO₂ alvo DPOC retentor',
      value: '88 a 92%',
      detail: 'Evitar hiperóxia cega (98–100%) em retenção de CO₂.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'cnaf-fluxo',
      label: 'Cateter nasal alto fluxo (CNAF)',
      value: '40 a 60 L/min',
      detail: 'Dispositivo distinto do CNA de baixo fluxo.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'umidificacao-o2',
      label: 'Umidificação do O₂',
      value: 'recomendada em fluxos altos e uso prolongado',
      detail: 'CNA >4 L/min ou máscaras de reservatório: umidificar para evitar ressecamento de mucosa.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'higiene-nasal-cna',
      label: 'Higiene nasal (CNA)',
      value: 'aspirar/umidificar secreções antes de posicionar cateter',
      detail: 'Narinas obstruídas reduzem FiO₂ efetiva e aumentam desconforto.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'posicionamento-fowler',
      label: 'Posicionamento Fowler',
      value: '45° a 90° (semi-Fowler 30° a 45°)',
      detail: 'Facilita expansão pulmonar e reduz trabalho respiratório na dispneia.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'sinais-hipoxia',
      label: 'Sinais de hipoxemia',
      value: 'taquipneia, cianose, agitação, confusão, SpO₂ <90%',
      detail: 'Bradipneia tardia e rebaixamento de consciência indicam deterioração grave.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'dpoc-o2-alto-contra',
      label: 'DPOC — O₂ em alto fluxo',
      value: 'evitar FiO₂ elevada cega em retentor de CO₂',
      detail: 'Hiperóxia pode suprimir drive ventilatório e agravar acidose respiratória — titular SpO₂ 88–92%.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'venturi-dpoc-inicial',
      label: 'Venturi em DPOC',
      value: 'iniciar com diluidor 24% ou 28%',
      detail: 'FiO₂ controlada — preferível a máscara simples de alto fluxo livre.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'monitorar-respiracao',
      label: 'Monitorização respiratória',
      value: 'SpO₂, FR, esforço respiratório e nível de consciência',
      detail: 'Reavaliar dispositivo e fluxo após cada mudança clínica.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'pegadinha-o2-100-dpoc',
      label: 'Pegadinha DPOC',
      value: 'não buscar SpO₂ 98–100% em DPOC retentor',
      detail: 'Meta segura 88–92% — não hiperoxigenar.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'cnaf-fio2',
      label: 'CNAF — FiO₂',
      value: '21 a 100% (ajustável no dispositivo)',
      detail: 'Alto fluxo com FiO₂ titulável — distinto do CNA de baixo fluxo.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'cnaf-umidificacao',
      label: 'CNAF — umidificação e aquecimento',
      value: 'gás aquecido e umidificado no dispositivo',
      detail: 'Reduz desconforto e trabalho respiratório; não confundir com CNA simples.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'mascara-simples-fio2',
      label: 'Máscara simples — FiO₂',
      value: 'aproximadamente 40 a 60%',
      detail: 'FiO₂ variável conforme fluxo e padrão ventilatório — não é FiO₂ precisa.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'mascara-nrb-fio2',
      label: 'Máscara não reinalante — FiO₂',
      value: 'aproximadamente 60 a 100%',
      detail: 'Fluxo mínimo 7–10 L/min para manter reservatório inflado.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'venturi-fluxo',
      label: 'Venturi — fluxo total',
      value: 'depende do diluidor (ex.: 2–15 L/min conforme FiO₂)',
      detail: 'Fluxo total inclui ar ambiente — FiO₂ precisa pelo diluidor colorido.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'cianose-central',
      label: 'Cianose central',
      value: 'lábios, língua e mucosas azuladas',
      detail: 'Indica hipoxemia significativa — avaliar SpO₂ e trocar dispositivo/fluxo.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'cianose-periferica',
      label: 'Cianose periférica',
      value: 'extremidades frias e azuladas — mucosas rosadas',
      detail: 'Pode refletir vasoconstrição (frio, choque inicial) — não confundir com hipoxemia central.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'aspiracao-traqueal-indicacao',
      label: 'Aspiração traqueal — indicação',
      value: 'secreção excessiva, ruídos adventícios ou obstrução parcial da via aérea',
      detail: 'Procedimento estéril em paciente intubado ou traqueostomizado — não é rotina profilática.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'aspiracao-traqueal-tecnica',
      label: 'Aspiração traqueal — técnica',
      value: 'pressão ≤120 mmHg (adulto); tempo de sucção ≤15 s',
      detail: 'Hiperoxigenar antes/depois; monitorar SpO₂ e FC — bradicardia indica hipóxia.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'aspiracao-orofaringe',
      label: 'Aspiração orofaríngea',
      value: 'cateter rígido ou flexível na cavidade oral/faringe',
      detail: 'Paciente com reflexo de tosse ausente ou secreção visível — técnica limpa ou estéril conforme protocolo.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'fisio-resp-expansao',
      label: 'Fisioterapia respiratória — expansão',
      value: 'exercícios de expansão pulmonar e incentivo respiratório',
      detail: 'Enfermagem apoia posicionamento, Fowler e uso de incentivador — fisioterapeuta prescreve técnica.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'fisio-resp-drenagem',
      label: 'Fisioterapia respiratória — drenagem',
      value: 'posturas de drenagem e percussão/vibração conforme prescrição',
      detail: 'Auxiliar na mobilização de secreções; contraindicar em instabilidade hemodinâmica ou fratura costal.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'enf-monitora-secrecao',
      label: 'Enfermagem — monitorização respiratória',
      value: 'avaliar cor, volume e odor das secreções',
      detail: 'Registrar FR, esforço, uso de musculatura acessória e SpO₂ — comunicar piora ao médico.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'umidificador-bolhas',
      label: 'Umidificador de bolhas',
      value: 'indicado em O₂ >4 L/min ou uso prolongado',
      detail: 'Manter nível de água destilada; trocar conforme protocolo — prevenir colonização.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'higiene-nasal-solucao',
      label: 'Higiene nasal',
      value: 'SF 0,9% ou solução salina para umidificar e desobstruir narinas',
      detail: 'Antes de posicionar CNA — crostas e secreções reduzem fluxo efetivo de O₂.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'titulacao-o2-incremento',
      label: 'Titulação de O₂',
      value: 'aumentar fluxo em 1–2 L/min até atingir SpO₂ alvo',
      detail: 'Reavaliar em 5 minutos após mudança; documentar dispositivo e fluxo.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'dpoc-labios-franzidos',
      label: 'DPOC — lábios franzidos',
      value: 'técnica de expiração prolongada para reduzir aprisionamento aéreo',
      detail: 'Complementa O₂ titulado — não substitui broncodilatador prescrito.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'pegadinha-mascara-simples-dpoc',
      label: 'Pegadinha DPOC — dispositivo',
      value: 'máscara simples de alto fluxo não é primeira escolha em DPOC retentor',
      detail: 'Preferir Venturi 24–28% com FiO₂ controlada — evitar hiperóxia.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
    {
      id: 'oxigenoterapia-contraindicacao-relativa',
      label: 'O₂ — cautela em retentor',
      value: 'DPOC com hipercapnia crônica — titular SpO₂ 88–92%',
      detail: 'Pegadinha de prova: SpO₂ 98–100% pode piorar retenção de CO₂ e nível de consciência.',
      sourceId: 'oxigenoterapia-dispositivos-ms',
    },
  ],
};
