import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Doenças parasitárias e zoonoses de interesse epidemiológico.
 * Fontes: MS Dengue diagnóstico e manejo clínico 6ª ed.; fluxograma profilaxia raiva;
 * Guia de Vigilância em Saúde (arboviroses/zoonoses).
 */
export const PARASITARIAS_ZOONOSES_MS: GuidelineTable = {
  id: 'parasitarias-zoonoses-ms',
  snapshot: 'Dengue 6ª ed. MS + raiva PEP + zoonoses',
  issuer: 'Ministério da Saúde',
  title: 'Doenças parasitárias e zoonoses',
  year: 2024,
  url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca',
  entries: [
    {
      id: 'dengue-vetor',
      label: 'Vetor da dengue',
      value: 'Aedes aegypti',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-criadouro',
      label: 'Criadouro Aedes',
      value: 'água parada limpa em recipientes domiciliares',
      detail: 'Pneus, caixas d\'água, lixeiras sem tampa.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-transmissao',
      label: 'Transmissão dengue',
      value: 'vetorial pelo mosquito infectado',
      detail: 'Não é via respiratória entre humanos.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-controle',
      label: 'Controle da dengue',
      value: 'eliminação de criadouros + proteção contra picada',
      detail: 'Repelente, telas, roupas longas.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'esquistossomose',
      label: 'Esquistossomose',
      value: 'Schistosoma mansoni — caramujo como hospedeiro intermediário',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leishmaniose',
      label: 'Leishmaniose',
      value: 'transmissão por flebotomíneos (mosquito-palha)',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-respiratoria',
      label: 'Pegadinha arbovirose',
      value: 'arbovirose não se transmite por gotículas humanas',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'chikungunya',
      label: 'Chikungunya',
      value: 'Aedes aegypti/albopictus — febre e artralgia intensa',
      detail: 'Artralgia pode persistir meses; controle do vetor igual dengue.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'zika-microcefalia',
      label: 'Zika vírus',
      value: 'transmissão pelo Aedes — associação com microcefalia fetal',
      detail: 'Gestante infectada: acompanhamento pré-natal e vigilância do recém-nascido.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'malaria-vetor',
      label: 'Malária',
      value: 'Plasmodium — transmissão pelo mosquito Anopheles',
      detail: 'Vetor diferente do Aedes; vigilância em área endêmica da Amazônia Legal.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-malaria-aedes',
      label: 'Pegadinha malária',
      value: 'malária não é transmitida pelo Aedes aegypti',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'hantavirose',
      label: 'Hantavirose',
      value: 'roedores silvestres — aerossóis de fezes/urina em ambiente fechado',
      detail: 'Síndrome cardiopulmonar por hantavírus é emergência com alta letalidade.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leptospirose',
      label: 'Leptospirose',
      value: 'contato com água ou solo contaminado por urina de roedores',
      detail: 'Comum após enchentes; febre, mialgia e icterícia na forma grave (Weil).',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-profilaxia',
      label: 'Raiva — profilaxia',
      value: 'lavagem abundante + vacina e soro conforme exposição leve/grave',
      detail:
        'MS fluxograma vigente: silvestre sempre grave; contato indireto (pele íntegra) sem profilaxia. Ver raiva-categoria-exposicao.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-lavagem-local',
      label: 'Raiva — ferimento',
      value: 'lavar com água e sabão imediatamente por pelo menos 15 min',
      detail: 'Primeira medida local antes da vacina e imunoglobulina anti-rábica.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'febre-amarela-urbana',
      label: 'Febre amarela urbana',
      value: 'transmissão pelo Aedes aegypti em área urbana',
      detail: 'Forma silvestre: Haemagogus em mata; ambas exigem vacinação em áreas de risco e notificação compulsória.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'doenca-chagas',
      label: 'Doença de Chagas',
      value: 'Trypanosoma cruzi — transmissão por triatomíneos (barbeiro)',
      detail: 'Fase aguda: chagoma de inoculação; crônica: cardiopatia e megas. Transfusão e vertical são vias alternativas.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leishmaniose-cutanea',
      label: 'Leishmaniose tegumentar',
      value: 'úlcera cutânea indolor com borda elevada — flebotomíneo infectado',
      detail: 'Leishmania spp.; diagnóstico por escarificação/biópsia; tratamento conforme espécie e forma clínica.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-categoria-exposicao',
      label: 'Raiva — classificação de exposição (MS)',
      value: 'leve ou grave (cão/gato); silvestre sempre grave; contato indireto sem profilaxia',
      detail:
        'Fluxograma MS: leve = mordedura/arranhadura superficial tronco/membros (exceto mãos/pés) ou lambedura superficial → vacina; grave = cabeça/mãos/pés/mucosa, múltipla/profunda → SAR/IGHAR + vacina. exam_vs_current: provas antigas usam categorias OMS I–III.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-esquema-vacinal-pep',
      label: 'Raiva — esquema vacinal PEP',
      value: '4 doses ID ou IM nos dias 0, 3, 7 e 14',
      detail:
        'NT 8/2022-CGZV/MS + fluxograma vigente; SAR 40 UI/kg ou IGHAR 20 UI/kg no D0 (até D7 da 1ª dose). Não aplicar no glúteo.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-grupo-a',
      label: 'Dengue — Grupo A',
      value: 'sem sinais de alarme, sem comorbidade/risco social — acompanhamento ambulatorial',
      detail: 'MS 6ª ed.: hidratação oral; retorno se sinais de alarme ou na defervescência.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-grupo-b',
      label: 'Dengue — Grupo B',
      value: 'sem sinais de alarme, com condição especial/comorbidade/risco social',
      detail:
        'MS 6ª ed.: hemograma obrigatório; observação até exames; lactentes, gestantes, >65 anos, DM, HAS grave etc.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-grupo-c',
      label: 'Dengue — Grupo C',
      value: 'sinais de alarme presentes — hidratação venosa e monitoramento',
      detail:
        'Sinais de alarme: dor abdominal intensa, vômitos persistentes, acúmulo de líquido, sangramento de mucosa, letargia/irritabilidade, hepatomegalia, aumento progressivo do Ht.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-grupo-d',
      label: 'Dengue — Grupo D',
      value: 'dengue grave (choque, extravasamento grave, sangramento grave, falência orgânica)',
      detail: 'MS 6ª ed.: emergência — reposição volêmica imediata (ex. 10 mL/kg SF na 1ª hora) em qualquer nível de atenção.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-sinais-alarme',
      label: 'Dengue — sinais de alarme',
      value: 'costumam surgir na defervescência (fase crítica)',
      detail: 'MS: retorno imediato na remissão da febre ou no 5º dia se febre persiste — pegadinha clássica de prova.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'malaria-plasmodium-especies',
      label: 'Malária — Plasmodium',
      value: 'P. vivax e P. falciparum predominam no Brasil',
      detail: 'P. falciparum: formas graves (cerebral); P. vivax: recidivas por hipnozoítos hepáticos — tratamento com primaquina.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'esquistossomose-prevencao',
      label: 'Esquistossomose — prevenção',
      value: 'evitar contato com água de foco em área endêmica',
      detail: 'Controle do caramujo (Biomphalaria); saneamento básico e educação em saúde.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'chikungunya-cronico',
      label: 'Chikungunya — artralgia crônica',
      value: 'dor articular pode persistir meses após fase aguda',
      detail: 'Não confundir com dengue hemorrágica; controle vetorial idêntico ao Aedes.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'zika-sindrome-congenita',
      label: 'Zika — síndrome congênita',
      value: 'microcefalia, calcificações cerebrais e restrição de crescimento fetal',
      detail: 'Infecção materna no 1º trimestre: maior risco; vigilância pré-natal obrigatória em área de transmissão.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leptospirose-notificacao',
      label: 'Leptospirose — vigilância',
      value: 'notificação compulsória — surtos após enchentes',
      detail: 'Profissionais de saneamento e agricultura: grupo de risco ocupacional.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'hantavirose-prevencao',
      label: 'Hantavirose — prevenção',
      value: 'evitar poeira de fezes de roedores em locais fechados',
      detail: 'Umidificar antes de limpar; uso de EPI em áreas silvestres ou galpões abandonados.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-vetor-doenca',
      label: 'Pegadinha vetor × doença',
      value: 'cada zoonose tem vetor ou via específica — não generalizar Aedes',
      detail: 'Malária = Anopheles; leishmaniose = flebotomíneo; hantavirose = aerossol de roedor (sem vetor).',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-leptospirose-mosquito',
      label: 'Pegadinha leptospirose',
      value: 'leptospirose não é transmitida por picada de mosquito',
      detail: 'Via é contato com água/solo contaminado por urina de roedores — banca mistura com arboviroses.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
  ],
};
