import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Doenças parasitárias e zoonoses de interesse epidemiológico.
 * Fonte: MS — vigilância de arboviroses e zoonoses.
 */
export const PARASITARIAS_ZOONOSES_MS: GuidelineTable = {
  id: 'parasitarias-zoonoses-ms',
  snapshot: 'Dengue e zoonoses — vetor e controle',
  issuer: 'Ministério da Saúde',
  title: 'Doenças parasitárias e zoonoses',
  year: 2024,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/d/dengue',
  entries: [
    {
      id: 'dengue-vetor',
      label: 'Vetor da dengue',
      value: 'Aedes aegypti',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-criadouro',
      label: 'Criadouro Aedes',
      value: 'água parada limpa em recipientes domiciliares',
      detail: 'Pneus, caixas d\'água, lixeiras sem tampa.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-transmissao',
      label: 'Transmissão dengue',
      value: 'vetorial pelo mosquito infectado',
      detail: 'Não é via respiratória entre humanos.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'dengue-controle',
      label: 'Controle da dengue',
      value: 'eliminação de criadouros + proteção contra picada',
      detail: 'Repelente, telas, roupas longas.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'esquistossomose',
      label: 'Esquistossomose',
      value: 'Schistosoma mansoni — caramujo como hospedeiro intermediário',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leishmaniose',
      label: 'Leishmaniose',
      value: 'transmissão por flebotomíneos (mosquito-palha)',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-respiratoria',
      label: 'Pegadinha arbovirose',
      value: 'arbovirose não se transmite por gotículas humanas',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'chikungunya',
      label: 'Chikungunya',
      value: 'Aedes aegypti/albopictus — febre e artralgia intensa',
      detail: 'Artralgia pode persistir meses; controle do vetor igual dengue.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'zika-microcefalia',
      label: 'Zika vírus',
      value: 'transmissão pelo Aedes — associação com microcefalia fetal',
      detail: 'Gestante infectada: acompanhamento pré-natal e vigilância do recém-nascido.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'malaria-vetor',
      label: 'Malária',
      value: 'Plasmodium — transmissão pelo mosquito Anopheles',
      detail: 'Vetor diferente do Aedes; vigilância em área endêmica da Amazônia Legal.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-malaria-aedes',
      label: 'Pegadinha malária',
      value: 'malária não é transmitida pelo Aedes aegypti',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'hantavirose',
      label: 'Hantavirose',
      value: 'roedores silvestres — aerossóis de fezes/urina em ambiente fechado',
      detail: 'Síndrome cardiopulmonar por hantavírus é emergência com alta letalidade.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leptospirose',
      label: 'Leptospirose',
      value: 'contato com água ou solo contaminado por urina de roedores',
      detail: 'Comum após enchentes; febre, mialgia e icterícia na forma grave (Weil).',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-profilaxia',
      label: 'Raiva — profilaxia',
      value: 'lavagem abundante do ferimento + vacina e soro conforme categoria',
      detail: 'MS: esquema pós-exposição obrigatório após mordedura ou escoriação por mamífero suspeito.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-lavagem-local',
      label: 'Raiva — ferimento',
      value: 'lavar com água e sabão imediatamente por pelo menos 15 min',
      detail: 'Primeira medida local antes da vacina e imunoglobulina anti-rábica.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'febre-amarela-urbana',
      label: 'Febre amarela urbana',
      value: 'transmissão pelo Aedes aegypti em área urbana',
      detail: 'Forma silvestre: Haemagogus em mata; ambas exigem vacinação em áreas de risco e notificação compulsória.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'doenca-chagas',
      label: 'Doença de Chagas',
      value: 'Trypanosoma cruzi — transmissão por triatomíneos (barbeiro)',
      detail: 'Fase aguda: chagoma de inoculação; crônica: cardiopatia e megas. Transfusão e vertical são vias alternativas.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leishmaniose-cutanea',
      label: 'Leishmaniose tegumentar',
      value: 'úlcera cutânea indolor com borda elevada — flebotomíneo infectado',
      detail: 'Leishmania spp.; diagnóstico por escarificação/biópsia; tratamento conforme espécie e forma clínica.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-categoria-exposicao',
      label: 'Raiva — categorias de exposição',
      value: 'I (contato sem lesão) a III (mordedura/escoriação com sangramento)',
      detail: 'Cat. I: lavagem; II: lavagem + vacina; III: lavagem + vacina + soro (imunoglobulina anti-rábica).',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'raiva-esquema-vacinal-pep',
      label: 'Raiva — esquema vacinal PEP',
      value: '4 doses intradérmicas ou IM nos dias 0, 3, 7 e 14',
      detail: 'Esquema MS atualizado; soro apenas na categoria III — aplicar o quanto antes após exposição.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'malaria-plasmodium-especies',
      label: 'Malária — Plasmodium',
      value: 'P. vivax e P. falciparum predominam no Brasil',
      detail: 'P. falciparum: formas graves (cerebral); P. vivax: recidivas por hipnozoítos hepáticos — tratamento com primaquina.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'esquistossomose-prevencao',
      label: 'Esquistossomose — prevenção',
      value: 'evitar contato com água de foco em área endêmica',
      detail: 'Controle do caramujo (Biomphalaria); saneamento básico e educação em saúde.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'chikungunya-cronico',
      label: 'Chikungunya — artralgia crônica',
      value: 'dor articular pode persistir meses após fase aguda',
      detail: 'Não confundir com dengue hemorrágica; controle vetorial idêntico ao Aedes.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'zika-sindrome-congenita',
      label: 'Zika — síndrome congênita',
      value: 'microcefalia, calcificações cerebrais e restrição de crescimento fetal',
      detail: 'Infecção materna no 1º trimestre: maior risco; vigilância pré-natal obrigatória em área de transmissão.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'leptospirose-notificacao',
      label: 'Leptospirose — vigilância',
      value: 'notificação compulsória — surtos após enchentes',
      detail: 'Profissionais de saneamento e agricultura: grupo de risco ocupacional.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'hantavirose-prevencao',
      label: 'Hantavirose — prevenção',
      value: 'evitar poeira de fezes de roedores em locais fechados',
      detail: 'Umidificar antes de limpar; uso de EPI em áreas silvestres ou galpões abandonados.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-vetor-doenca',
      label: 'Pegadinha vetor × doença',
      value: 'cada zoonose tem vetor ou via específica — não generalizar Aedes',
      detail: 'Malária = Anopheles; leishmaniose = flebotomíneo; hantavirose = aerossol de roedor (sem vetor).',
      sourceId: 'parasitarias-zoonoses-ms',
    },
    {
      id: 'pegadinha-leptospirose-mosquito',
      label: 'Pegadinha leptospirose',
      value: 'leptospirose não é transmitida por picada de mosquito',
      detail: 'Via é contato com água/solo contaminado por urina de roedores — banca mistura com arboviroses.',
      sourceId: 'parasitarias-zoonoses-ms',
    },
  ],
};
