import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Assistência perioperatória e centro cirúrgico.
 * Fontes: OMS (cirurgia segura), COFEN, Anvisa RDC CC.
 */
export const PERIOPERATORIO_CIRURGIA_SEGURA: GuidelineTable = {
  id: 'perioperatorio-cirurgia-segura',
  snapshot: 'Cirurgia segura — checklist e SRPA',
  issuer: 'OMS / COFEN',
  title: 'Assistência perioperatória e centro cirúrgico',
  year: 2017,
  url: 'https://www.cofen.gov.br/',
  entries: [
    {
      id: 'cirurgia-segura-checklist',
      label: 'Lista cirurgia segura',
      value: 'conferir identidade, procedimento e sítio cirúrgico antes da incisão',
      detail: 'Time-out — pausa antes da incisão.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'cirurgia-contagem',
      label: 'Contagem de materiais',
      value: 'compressas, agulhas e instrumentos — início, meio e fim',
      detail: 'Previne corpo estranho retido.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'cirurgia-asseptica',
      label: 'Campo operatório',
      value: 'técnica asséptica obrigatória — duração não dispensa',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'srpa-def',
      label: 'SRPA',
      value: 'sala de recuperação pós-anestésica — monitorização contínua',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'srpa-tecnico-papel',
      label: 'Técnico na SRPA',
      value: 'monitorar, observar e comunicar — não executar procedimentos privativos',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'srpa-cpd-curativo',
      label: 'Curativo cateter peridural (CPD)',
      value: 'troca é privativa do enfermeiro',
      detail: 'Supervisão não autoriza técnico a executar procedimento privativo.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'cc-circulante-instrumentador',
      label: 'Funções no CC',
      value: 'circulante e instrumentador — papéis distintos',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'jejum-pre-operatorio',
      label: 'Jejum pré-operatório',
      value: 'conforme protocolo anestésico — reduzir risco de aspiração',
      detail: 'Adulto: em geral 8 horas sólidos, 2 horas líquidos claros (diretrizes atuais).',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'jejum-solidos-8h',
      label: 'Jejum — alimentos sólidos',
      value: '8 horas antes do procedimento eletivo',
      detail: 'Diretriz OMS/ASA adotada no Brasil — inclui leite e fórmulas; reduz risco de aspiração pulmonar.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'jejum-liquidos-2h',
      label: 'Jejum — líquidos claros',
      value: 'até 2 horas antes (água, chá, suco coado sem polpa)',
      detail: 'Líquidos claros sem resíduos — não inclui leite ou refeição líquida.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'cirurgia-sign-in',
      label: 'Checklist — Sign In',
      value: 'antes da indução anestésica',
      detail: 'Confirmar identidade, sítio, procedimento, consentimento, alergias e risco de sangramento.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'cirurgia-time-out',
      label: 'Checklist — Time Out',
      value: 'pausa cirúrgica antes da incisão',
      detail: 'Toda a equipe confere paciente, sítio marcado e procedimento em voz alta.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'cirurgia-sign-out',
      label: 'Checklist — Sign Out',
      value: 'antes de sair do centro cirúrgico',
      detail: 'Contagem de compressas e instrumentos, rotulagem de peças e plano pós-operatório.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'posicao-cirurgica',
      label: 'Posicionamento cirúrgico',
      value: 'prevenir lesão por pressão e distúrbios circulatórios',
      detail: 'Proteger proeminências ósseas, nervos e vasos — alinhar membros; documentar posição.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'posicao-trendelenburg',
      label: 'Trendelenburg',
      value: 'decúbito dorsal com cabeceira mais baixa que os pés',
      detail: 'Cirurgias pélvicas e laparoscopia — monitorar pressão intra-abdominal e vias aéreas.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'srpa-escala-aldrete',
      label: 'SRPA — escala de Aldrete',
      value: 'avalia consciência, atividade, respiração, circulação e saturação',
      detail: 'Alta da SRPA quando escore ≥ 8 (ou protocolo institucional) — critério objetivo de recuperação.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'srpa-nivel-consciencia',
      label: 'SRPA — nível de consciência',
      value: 'monitorar resposta a estímulos — alerta, sonolento ou não responsivo',
      detail: 'Depressão respiratória pós-anestésica — manter oximetria e comunicar anestesista imediatamente.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'sign-in-itens-oms',
      label: 'Sign In — itens obrigatórios',
      value: 'identidade, sítio, procedimento, consentimento, alergias, via aérea e risco de sangramento',
      detail: 'Realizado na sala cirúrgica, antes da indução anestésica — toda a equipe confirma em voz alta.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'time-out-itens-oms',
      label: 'Time Out — itens obrigatórios',
      value: 'pausa com confirmação verbal de paciente, sítio marcado e procedimento',
      detail: 'Momento imediatamente antes da incisão — inclui profilaxia antibiótica e imagens quando aplicável.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'sign-out-itens-oms',
      label: 'Sign Out — itens obrigatórios',
      value: 'contagem final, rotulagem de peças e plano de recuperação',
      detail: 'Antes de sair da sala — registrar nome do procedimento realizado e destino do paciente (SRPA/UTI).',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'posicao-litotomia',
      label: 'Posição — litotomia',
      value: 'decúbito dorsal com pernas elevadas e flexionadas nos estribos',
      detail: 'Cirurgias ginecológicas, urológicas e anorretais — proteger nervo ciático, poplíteo e áreas de pressão.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'posicao-prona',
      label: 'Posição — prona (decúbito ventral)',
      value: 'paciente de bruços com cabeça alinhada ou fixada',
      detail: 'Cirurgias de coluna e neurocirurgia — almofadas em tórax e pelve; evitar compressão de abdome e olhos.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'srpa-aldrete-criterios',
      label: 'Aldrete — critérios de pontuação',
      value: 'consciência, atividade, respiração, circulação (PA ± 20% basal) e saturação — cada item 0 a 2 pontos',
      detail: 'Atividade: 0 nenhum movimento, 2 quatro membros. Ventilação: 0 apneia, 2 respira e tosse. Circulação: PA ± 20% do basal = 2. SpO₂ > 92% em ar = 2.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'posop-imediato-24h',
      label: 'Pós-operatório imediato',
      value: 'primeiras 24 horas após a cirurgia',
      detail: 'Estabilização, dor, sangramento e início da mobilização — marco temporal clássico até o mediato.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'posop-mediato-24h',
      label: 'Pós-operatório mediato',
      value: 'após as primeiras 24 horas até alta hospitalar ou retorno domiciliar',
      detail: 'Plano de cuidados, reabilitação, curativos e educação para alta — tempo individualizado.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'isc-surveillance-30d',
      label: 'ISC — vigilância temporal',
      value: '30 dias após cirurgia (ou 1 ano com implante)',
      detail: 'Infecção de sítio cirúrgico — janela de vigilância CDC/NHSN para classificação.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'porte-cirurgico-iv',
      label: 'Porte cirúrgico IV — ABC',
      value: 'acima de 6 horas de duração',
      detail: 'Classificação da Associação Brasileira de Cirurgia — maior porte/tempo.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'porte-cirurgico-iii',
      label: 'Porte cirúrgico III — referência',
      value: 'a partir de 3 horas até 6 horas',
      detail: 'Portes menores: 2 h e 3 h são distratores frente ao porte IV (>6 h).',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'rpa-duracao-tipica',
      label: 'RPA — permanência típica',
      value: '30 minutos a 2 horas na recuperação pós-anestésica',
      detail: 'Varia conforme anestésico e estabilização — vigilância até critérios de alta da sala.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'curativo-posop-7d',
      label: 'Curativo pós-operatório — troca',
      value: 'primeira troca em até 7 dias conforme protocolo',
      detail: 'Curativo oclusivo inicial — reavaliação precoce do sítio cirúrgico.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'dreno-posop-8d',
      label: 'Dreno cirúrgico — retirada',
      value: '8 dias como referência de retirada em alguns protocolos',
      detail: 'Tempo depende do débito e tipo de dreno — prova pode fixar marco de 8 dias.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'sv-rpa-aprazamento',
      label: 'SRPA — aprazamento de sinais vitais',
      value: 'aferir sinais vitais a cada 5 minutos; 1 minuto se instável na recuperação',
      detail: 'Paciente instável pode exigir intervalo de 1 minuto até estabilização.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'infusao-volume-referencia',
      label: 'Infusão IV — volumes de referência',
      value: '100 ml e 540 ml em cálculos de gotejamento',
      detail: 'Prova de vias/administração no perioperatório — converter ml/h em gotas/min.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'cc-aquecimento-60min',
      label: 'Centro cirúrgico — aquecimento pré-incisão',
      value: '60 minutos de aquecimento ativo antes da incisão',
      detail: 'Normotermia perioperatória — cobertor térmico e fluidos aquecidos.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'higiene-clorexidina-concentracao',
      label: 'Antissepsia — concentrações',
      value: 'clorexidina 2% a 4% conforme protocolo de banho/higiene',
      detail: 'Curativo ou banho antisséptico — não confundir com álcool 70% na punção.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'curativo-troca-3d',
      label: 'Curativo — intervalo de troca',
      value: '3 dias entre trocas em alguns protocolos de ferida',
      detail: 'Depende do tipo de curativo e exsudato — prova pode fixar 3 dias.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'febre-posop-38c',
      label: 'Febre pós-operatória',
      value: '38 °C como limiar de vigilância de infecção',
      detail: 'Temperatura ≥ 38°C no pós-operatório imediato exige investigação de ISC.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'alcool-70-antissepsia',
      label: 'Álcool 70% — antissepsia',
      value: 'álcool 70% no preparo de pele ou punção venosa',
      detail: 'Alternativa à clorexidina conforme tipo de amostra e procedimento.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'anestesia-fases',
      label: 'Fases da anestesia',
      value: 'pré-anestésica, indução, manutenção e emergência/recuperação',
      detail: 'Pré: avaliação e jejum. Indução: início da anestesia. Manutenção: procedimento. Emergência: despertar e SRPA.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'contagem-fases-cirurgicas',
      label: 'Contagem — compressas, agulhas e instrumentos',
      value: 'início, antes de fechar cavidade, meio e fim do procedimento',
      detail: 'Contagem dupla e registro — discrepância impede fechamento até localizar material; radiografia se necessário.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'preparo-pele-antisseptico',
      label: 'Preparo da pele cirúrgica',
      value: 'antissepsia com clorexidina ou PVPI — do centro para a periferia',
      detail: 'Aguardar tempo de contato do produto; não passar sobre área já estéril; remover pelos quando indicado.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'sonda-vesical-pre-operatorio',
      label: 'Sonda vesical pré-operatória',
      value: 'indicada conforme procedimento, tempo cirúrgico e tipo de anestesia',
      detail: 'Evita retenção urinária e protege bexiga em cirurgias pélvicas prolongadas — não é rotina universal.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'normotermia-hipotermia',
      label: 'Aquecimento e hipotermia',
      value: 'manter normotermia — cobertores térmicos, fluidos aquecidos e temperatura ambiente',
      detail: 'Hipotermia perioperatória aumenta infecção de sítio, sangramento e tempo de recuperação na SRPA.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'pegadinha-checklist-formal',
      label: 'Pegadinha — checklist cirurgia segura',
      value: 'checklist não é formalidade burocrática — reduz eventos adversos graves',
      detail: 'Prova cobra ordem Sign In → Time Out → Sign Out; pular etapa ou fazer só no papel é erro grave.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
    {
      id: 'pegadinha-contagem-incompleta',
      label: 'Pegadinha — contagem de materiais',
      value: 'contagem só no final não basta — exige registro em múltiplos momentos',
      detail: 'Fechar cavidade com contagem divergente é conduta inaceitável; técnico participa e comunica discrepância.',
      sourceId: 'perioperatorio-cirurgia-segura',
    },
  ],
};
