import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Intervalos e regras PNI — builders de Imunização devem citar estas entradas.
 * Snapshot alinhado à IN do Calendário Nacional 2026 (DPNI/MS); id estável `pni-2025-intervalos`.
 */
export const PNI_INTERVALOS_2025: GuidelineTable = {
  id: 'pni-2025-intervalos',
  snapshot: 'PNI / Manual MS + IN Calendário Nacional 2026',
  issuer: 'Ministério da Saúde',
  title: 'Manual de Normas e Procedimentos para Vacinação — intervalos',
  year: 2026,
  url: 'https://www.gov.br/saude/pt-br/composicao/svsa/pni/calendario-tecnico',
  entries: [
    {
      id: 'grace-period-4d',
      label: 'Grace period (antecipação)',
      value: '≤4 dias antes da idade mínima ou intervalo mínimo = dose válida',
      detail: 'Não registrar erro nem repetir só por antecipação dentro da margem.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'scr-fa-menor-2a',
      label: 'SCR/SCRV × febre amarela <2 anos',
      value: 'Não simultâneo em rotina; intervalo mínimo 30 dias',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'vpc13-vpp23',
      label: 'VPC13 × VPP23',
      value: 'Não simultâneas; mín. 8 semanas; VPC13 primeiro; VPP23 antes → 1 ano para VPC13',
      detail:
        'IN 2026: VPC20 (pneumocócica 20-valente) passa a substituir VPP23 em grupos prioritários (ex.: ≥60 anos acamados/institucionalizados sem histórico; indígenas ≥5 anos sem conjugada). Ver entry vpc20-transicao.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'vpc20-transicao',
      label: 'VPC20 — transição (IN 2026)',
      value: 'Dose única de VPC20 substitui esquema de 2 doses VPP23 nos grupos prioritários da IN',
      detail:
        'Se já tem 2 doses VPP23 → considerar vacinado. Se 1 dose VPP23 → completar com VPC20 respeitando intervalo mínimo. Sem histórico → dose única VPC20. Demais públicos: seguir calendário técnico vigente.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'oral-injetavel',
      label: 'Oral atenuada × injetável',
      value: 'Mesmo dia ou qualquer intervalo',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'oral-oral-15d',
      label: 'Vacinas orais atenuadas entre si',
      value: 'Mesmo dia ou intervalo mínimo de 15 dias',
      detail: 'Rotavírus e VOP: não confundir com oral×injetável (livre) — oral×oral exige ≥15 dias se não simultâneo.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'virais-vivos-injetaveis',
      label: 'Virais vivos injetáveis',
      value: 'Mesmo dia OU ≥4 semanas entre si',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'virais-vivos-30d',
      label: 'Virais atenuadas parenterais (não simultâneas)',
      value: 'Intervalo mínimo de 30 dias',
      detail: 'Tríplice viral, varicela e similares.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'scr-fa-maior-2a',
      label: 'SCR/SCRV × febre amarela ≥2 anos',
      value: 'Simultânea ou intervalo de 30 dias',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'inativada-inativada',
      label: 'Vacinas inativadas entre si',
      value: 'Nenhum intervalo — podem ser no mesmo dia',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'penta-intervalo-60d',
      label: 'Pentavalente — intervalo entre doses',
      value: '60 dias entre doses (mínimo 30 dias)',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'dt-intervalo-60d',
      label: 'dT — intervalo entre doses esquema primário',
      value: '60 dias entre doses (mínimo 30 dias)',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'rota-intervalo-30d',
      label: 'Rotavírus — intervalo mínimo',
      value: '30 dias entre 1ª e 2ª dose',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'covid-intervalo-4sem',
      label: 'Covid-19 — intervalo doses pediátricas',
      value: '4 semanas entre D1 e D2 (Moderna crianças)',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'covid-intervalo-6m',
      label: 'Covid-19 — reforço idosos',
      value: '6 meses entre doses anuais',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'covid-intervalo-8sem',
      label: 'Covid-19 — imunocomprometidos',
      value: '8 semanas entre D2 e D3 no esquema primário',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'imunossup-2sem',
      label: 'Imunossupressão — intervalo mínimo vacina',
      value: 'Manter intervalo mínimo de 2 semanas quando não puder vacinar antes',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'bcg-nascer',
      label: 'BCG — rotina',
      value: 'Ao nascer até 4 anos, 11 meses e 29 dias se não vacinado',
      detail: 'Via intradérmica; deltóide direito preferencial; 0,05 mL (<1 ano) ou 0,1 mL (≥1 ano).',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'bcg-peso-2kg',
      label: 'BCG — RN com baixo peso',
      value: 'Adiar se peso ao nascer <2 kg até atingir 2 kg',
      detail: 'Exposto ao HIV assintomático e sem imunodepressão: pode receber BCG.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'hepatite-b-rn',
      label: 'Hepatite B — recém-nascido',
      value: '1ª dose preferencialmente nas primeiras 12 h de vida (até 24 h)',
      detail: 'Ao nascer com BCG; se mãe HBsAg+: vacinar + imunoglobulina anti-HBs em até 12 h.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'rota-limite-idade',
      label: 'Rotavírus — limites de idade',
      value: 'D1 até 11 meses e 29 dias; D2 até 23 meses e 29 dias',
      detail: 'Intervalo mínimo de 30 dias; não iniciar após o limite etário do PNI.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'meningo-c-esquema',
      label: 'Meningocócica C conjugada',
      value: '3 doses aos 3, 5 e 12 meses de idade',
      detail: 'Esquema do lactente no calendário PNI 2025 — não confundir com marco dos 2 meses.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'dtp-reforco-calendario',
      label: 'DTP — reforços de rotina',
      value: 'Aos 15 meses e 4 anos de idade',
      detail: 'Integrados ao calendário infantil (pentavalente/DTP conforme idade).',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'anafilaxia-contraindicacao',
      label: 'Anafilaxia — contraindicação',
      value: 'Reação anafilática prévia ao componente da vacina: contraindicação absoluta',
      detail: 'Manual PNI: não revacinar com o mesmo imunobiológico; avaliar componentes cruzados.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'anafilaxia-alerta',
      label: 'Anafilaxia pós-vacinação',
      value: 'Observar 15–30 min no serviço; epinefrina IM se anafilaxia',
      detail: 'Evento adverso grave exige notificação e contraindicação às doses subsequentes da mesma vacina.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'pegadinha-bcg-via',
      label: 'Pegadinha BCG',
      value: 'BCG é intradérmica — não intramuscular',
      detail: 'Banca troca via de administração ou confunde marco ao nascer com 2–3 meses.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'doenca-aguda-grave',
      label: 'Doença aguda moderada/grave',
      value: 'Adiar vacinação até recuperação clínica',
      detail: 'Febre alta ou doença aguda significativa: postergar. Resfriado leve sem febre não contraindica.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'febre-leve-nao-contra',
      label: 'Febre ou doença leve',
      value: 'Não contraindica vacinação de rotina',
      detail: 'Infecção leve de vias aéreas superiores, diarreia leve ou febre baixa: vacinar conforme calendário.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'gestante-vivo-contra',
      label: 'Gestante × vacinas vivas atenuadas',
      value: 'Contraindicadas na gestação (exceto FA em situação de alto risco epidemiológico)',
      detail: 'SCR, SCRV, VOP, varicela isolada e rotavírus: não aplicar em gestantes. Influenza inativada e dTpa são indicadas.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'gestante-dtpa-janela',
      label: 'dTpa — gestante',
      value: '1 dose a cada gestação, preferencialmente entre 20 semanas e 36 semanas e 6 dias',
      detail: 'Proteção do neonato contra coqueluche. Não substitui esquema prévio de dT/dTpa fora da gestação.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'gestante-influenza-trimestre',
      label: 'Influenza — gestante',
      value: 'Vacinar em qualquer trimestre da gestação',
      detail: 'Vacina inativada; prioridade no calendário sazonal. Intervalo anual entre campanhas.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'imunodeprimido-vivo-contra',
      label: 'Imunodeprimidos × vacinas vivas',
      value: 'Contraindicadas em imunodeficiência grave ou imunossupressão significativa',
      detail: 'SCR, SCRV, VOP, BCG, FA, rotavírus e varicela: evitar. Avaliar risco × benefício individualmente.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'imunodeprimido-inativada',
      label: 'Imunodeprimidos × vacinas inativadas',
      value: 'Indicadas conforme calendário; resposta pode ser subótima',
      detail: 'Pentavalente, VIP, pneumo conjugada, influenza, hepatites e meningocócicas inativadas: administrar quando indicadas.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'imuno-delay-vivo-pos',
      label: 'Pós-imunossupressão — vacinas vivas',
      value: 'Aguardar ≥3 meses após cessar imunossupressor para vivas atenuadas',
      detail: 'Quimioterapia, corticoide em dose imunossupressora, biológicos e transplante: intervalo antes de SCR, FA e similares.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'intervalo-curto-erro',
      label: 'Intervalo menor que o mínimo',
      value: 'Dose inválida — repetir respeitando o intervalo mínimo a partir da dose inadequada',
      detail: 'Diferente do grace period de 4 dias: intervalo insuficiente entre doses exige revacinação após o prazo mínimo.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'intervalo-ig-vivo-11m',
      label: 'Imunoglobulina × vacina viral viva',
      value: 'Intervalo mínimo de 11 meses entre Ig heteróloga e SCR (ou 3–11 meses conforme produto e esquema)',
      detail: 'Soro antirrábico, anti-HBs, IVIG e similares podem interferir na resposta às vivas — consultar Manual PNI por produto.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'hpv-intervalo-5m',
      label: 'HPV — intervalo entre doses',
      value: 'Rotina CNV 2026: dose única 9–14 anos; multi-dose só em situações especiais',
      detail:
        'IN/Calendário Nacional 2026: rotina HPV4 = 1 dose. Intervalos de 2 ou 3 doses aplicam-se a esquemas legados/grupos especiais da IN — não à rotina atual.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'evento-local-leve',
      label: 'Evento adverso local leve',
      value: 'Dor, edema ou eritema no local não contraindicam doses subsequentes',
      detail: 'Reações locais e febre baixa são esperadas. Orientar analgesia e sinais de alerta.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'evento-febre-pos-vacina',
      label: 'Febre pós-vacinação',
      value: 'Febre isolada e autolimitada não contraindica próxima dose do esquema',
      detail: 'Avaliar convulsão febril prévia em DTP: precaução e vigilância, não contraindicação absoluta rotineira.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'notificacao-eapv',
      label: 'Notificação de evento adverso',
      value: 'Notificar EAPV grave, inusitado ou de interesse no serviço e no sistema oficial',
      detail: 'Anafilaxia, síncope com queda, eventos neurológicos e óbito: notificação imediata e registro no prontuário/SI-EAPV.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'syncope-adolescente',
      label: 'Síncope pós-vacinação',
      value: 'Observar sentado ou deitado 15 min após vacina em adolescentes',
      detail: 'HPV, meningocócica e dTpa: risco de síncope vasovagal — evitar lesão por queda.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'alergia-ovo-influenza',
      label: 'Alergia grave ao ovo × influenza',
      value: 'Alergia anafilática ao ovo: avaliar risco; vacinar em serviço com suporte se indicado',
      detail: 'Não é contraindicação absoluta universal no PNI atual — diferenciar alergia leve de anafilaxia ao ovo.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'dnc-progressiva-dtp',
      label: 'Encefalopatia/DNC progressiva',
      value: 'Contraindicação à vacina com componente pertussis (DTP/dTpa)',
      detail: 'Encefalopatia nos 7 dias após dose anterior de pertussis: contraindica pertussis; usar dT.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'vacina-congelada-acidental',
      label: 'Vacina refrigerada congelada por acidente',
      value: 'Congelamento acidental de imunobiológico refrigerado: descartar — não aplicar',
      detail: 'Vacinas que exigem refrigeração perdem potência se congelam; acionar fluxo de perda de cadeia de frio.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'prematuro-bcg-peso',
      label: 'BCG — prematuro de baixo peso',
      value: 'Prematuro com peso inferior a 2 000 g: adiar BCG até recuperação ponderal',
      detail: 'Cauda longa de contraindicação relativa; vacinar quando estável e conforme manual local.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'evento-adverso-grave-notificar',
      label: 'Evento adverso grave pós-vacina',
      value: 'Anafilaxia, convulsão, síncope com trauma ou evento neurológico: notificar e contraindicar revacinação com o mesmo produto',
      detail: 'Complementa notificacao-eapv; diferenciar reação local leve de evento grave.',
      sourceId: 'pni-2025-intervalos',
    },
    {
      id: 'dtpa-td-intervalo-4sem',
      label: 'dTpa × dT/dTpa — intervalo',
      value: 'Mínimo 4 semanas entre doses com componente tetânico quando esquemas se sobrepõem',
      detail: 'Evitar acúmulo de reforços em intervalo curto; respeitar esquema gestacional e de ferimento à parte.',
      sourceId: 'pni-2025-intervalos',
    },
  ],
};
