import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Calendário e esquemas vacinais — Manual MS / IN Calendário Nacional 2026.
 * Id estável `pni-calendario-2025` (sourceIds nos goldens); snapshot aponta à IN 2026.
 * Fonte: https://www.gov.br/saude/pt-br/composicao/svsa/pni/calendario-tecnico
 */
export const PNI_CALENDARIO_2025: GuidelineTable = {
  id: 'pni-calendario-2025',
  snapshot: 'PNI Calendário — IN MS 2026 (base técnica 2025+)',
  issuer: 'Ministério da Saúde',
  title: 'Calendário Nacional de Vacinação — esquemas e idades',
  year: 2026,
  url: 'https://www.gov.br/saude/pt-br/composicao/svsa/pni/calendario-tecnico',
  entries: [
    {
      id: 'penta-esquema',
      label: 'Pentavalente (DTP/Hib/HB)',
      value: '3 doses aos 2 meses, 4 meses e 6 meses de idade',
      detail: 'Intervalo de 60 dias entre doses (mínimo 30 dias). 3ª dose não antes dos 6 meses.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'penta-reforcos',
      label: 'Pentavalente — reforços DTP',
      value: 'Reforços aos 15 meses e 4 anos de idade',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'penta-via-local',
      label: 'Pentavalente — via e local',
      value: 'Intramuscular profunda; vasto lateral da coxa preferencial em lactentes',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'penta-conservacao',
      label: 'Pentavalente — conservação',
      value: 'Entre 2 °C e 8 °C; não congelar',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rota-2025',
      label: 'Rotavírus (VRH) — CNV 2026',
      value: 'D1 aos 2 meses (até 11 meses e 29 dias); D2 aos 4 meses (até 23 meses e 29 dias)',
      detail: 'IN CNV 2026: intervalo 60 dias (mín. 30). Perde oportunidade se D1 fora da faixa.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vip-reforco-2025',
      label: 'VIP — reforços poliomielite (CNV 2026)',
      value: 'Esquema exclusivo VIP; reforços aos 15 meses e aos 4 anos',
      detail: 'CNV 2026 criança: 1º reforço 15 m; 2º reforço 4 anos — sem VOP na rotina.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'dt-adulto-reforco',
      label: 'Dupla adulto (dT) — reforço rotina',
      value: 'Esquema completo: 1 dose a cada 10 anos',
      detail: 'Sem comprovação: 3 doses com intervalo 60 dias (mín. 30 dias).',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'dt-ferimento-5anos',
      label: 'dT — ferimento e última dose <5 anos',
      value: '3 doses ou mais com última dose há menos de 5 anos: não vacinar em ferimento de risco mínimo',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'dt-ferimento-5-10anos',
      label: 'dT — ferimento e última dose 5–10 anos',
      value: 'Última dose há mais de 5 anos e menos de 10 anos: 1 reforço em ferimento alto risco',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'dt-ferimento-10anos',
      label: 'dT — ferimento e última dose ≥10 anos',
      value: 'Última dose há 10 anos ou mais: reforço com vacina em ferimentos',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'covid-crianca-6m',
      label: 'Covid-19 — crianças (CNV 2026)',
      value: 'Rotina infantil com 3 doses (RNAm); atraso até 4 a 11 m 29 d',
      detail:
        'CNV 2026: intervalos mín. 4 sem (D1–D2) e 8 sem (D2–D3). Imunocomprometidos: doses periódicas 6/6 meses até 4 a 11 m 29 d.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'covid-spikevax-lactente',
      label: 'Covid-19 — volume pediátrico',
      value: 'Usar apresentação/volume pediátrico conforme bula e IN vigente',
      detail:
        'Não usar volume de adulto em lactente. exam_vs_current: provas antigas podem citar só 2 doses Spikevax 0,25 mL — CNV 2026 prevê esquema de 3 doses na rotina.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vsr-gestante-28sem',
      label: 'VSR — vacina em gestante',
      value: '1 dose a partir da 28ª semana — a cada gestação (VVSR)',
      detail:
        'CNV/Calendário Técnico Gestante 2026: proteção passiva do RN até ~6 meses. Não confundir com dTpa (a partir da 20ª semana).',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'hpv-dose-unica-2024',
      label: 'HPV — atualização 2024',
      value: 'Rotina 9 a 14 anos: dose única para meninas e meninos',
      detail: 'Até 14 anos, 11 meses e 29 dias; substitui esquema de 2 doses na rotina.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'covid-idoso-60',
      label: 'Covid-19 — idosos',
      value: '60 anos ou mais: 2 doses anuais com intervalo de 6 meses',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'covid-12anos',
      label: 'Covid-19 — Serum/Zalika',
      value: 'Vacina Serum/Zalika: apenas a partir de 12 anos de idade',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'gripe-6m-5a',
      label: 'Influenza — crianças 2025',
      value: 'Rotina: a partir de 6 meses a menores de 6 anos (5 anos, 11 meses e 29 dias)',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'gripe-idoso-60',
      label: 'Influenza — idosos',
      value: '60 anos ou mais no calendário de rotina',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'hepatite-b-gestante',
      label: 'Hepatite B — gestante',
      value: '3 doses (0, 1 e 6 meses) conforme histórico vacinal',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'idade-14anos-adolescente',
      label: 'Faixa etária adolescente (prova)',
      value: '14 anos — faixa comum em esquemas HPV e campanhas escolares',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'cadeia-frio-2-8',
      label: 'Cadeia de frio — temperatura positiva',
      value: 'Vacinas na rede de frio: 2 °C a 8 °C',
      detail: 'Diluentes armazenar 2 °C a 8 °C por no mínimo 24 horas antes do uso.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'diluente-24h',
      label: 'Diluentes — preparo',
      value: '24 horas na geladeira (2 °C a 8 °C) antes do uso; aceita 24h',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-freezer',
      label: 'Câmara negativa — freezer PNI',
      value: '−15 °C a −25 °C para vacinas liofilizadas que exigem congelamento (ex.: SCR)',
      detail: 'Não confundir com temperatura positiva 2 °C a 8 °C da maioria dos imunobiológicos.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-nao-congelar-positiva',
      label: 'Temperatura positiva — não congelar',
      value: 'Vacinas em 2 °C a 8 °C: não congelar — congelamento inativa a maioria',
      detail: 'Pentavalente, VIP, hepatite B, meningocócicas refrigeradas: perda se atingir congelamento.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-armazenamento-central',
      label: 'Armazenamento na geladeira',
      value: 'Parte central da geladeira — nunca porta nem compartimento do congelador',
      detail: 'Porta e topo variam; manter frascos longe de fontes de frio direto e de congelamento acidental.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-termometro',
      label: 'Monitoramento de temperatura',
      value: 'Termômetro calibrado na parte central; registrar leituras mínimo 2 vezes ao dia',
      detail: 'Manual da Rede de Frio: controle diário da faixa 2 °C a 8 °C e registro no SI-PNI.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-acima-8',
      label: 'Acima de 8 °C — conservação',
      value: 'Acima de 8 °C o imunobiológico sai da faixa adequada — não aplicar sem fluxo de avaliação',
      detail: 'Perda de potência; acionar protocolo de perda de cadeia de frio e notificar.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-abaixo-2',
      label: 'Abaixo de 2 °C — piso positiva',
      value: 'Piso da cadeia fria positiva é 2 °C — faixa abaixo disso não é conservação adequada',
      detail: 'Alternativas de prova que iniciam em 0 °C ou congelamento seduzem fora do decore 2–8 °C.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-armadilha-0-2',
      label: 'Armadilha de prova — faixa 0 a 2 °C',
      value: '0 °C a 2 °C — distrator comum; piso correto da positiva é 2 °C',
      detail: 'Manual da Rede de Frio: imunobiológicos em temperatura positiva ficam entre 2 °C e 8 °C.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-armadilha-8-12',
      label: 'Armadilha de prova — faixa 8 a 12 °C',
      value: '8 °C a 12 °C — distrator com teto estourado; acima de 8 °C perde conservação adequada',
      detail: 'Alternativa seduz quem lembra o 8 °C mas prolonga a faixa para cima.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-ruptura-agitar',
      label: 'Ruptura de cadeia — não recuperar agitando',
      value: 'Vacina fora da faixa 2 °C a 8 °C: não aplicar — agitar não recupera potência',
      detail: 'Seguir fluxo de perda; registrar e notificar SI-PNI — nunca improvisar aplicação.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-perda-fluxo',
      label: 'Perda de cadeia de frio — conduta',
      value: 'Identificar, registrar perda, notificar fluxo PNI e não aplicar sem orientação',
      detail: 'Geladeira quebrada, caixa térmica aberta ou leitura fora da faixa: acionar responsável e sistema.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-caixa-termica',
      label: 'Transporte — caixa térmica',
      value: 'Transporte com caixa térmica, gelo refrigerante e termômetro — manter 2 °C a 8 °C',
      detail: 'Não usar gelo em contato direto com frascos; validar tempo máximo de transporte do manual.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'diluente-scr-par',
      label: 'SCR liofilizada — par vacina + diluente',
      value: 'Vacina SCR liofilizada no freezer (−15 °C a −25 °C); diluente em 2 °C a 8 °C por 24 horas',
      detail: 'Reconstituir no turno; descartar se fora da faixa ou após tempo de uso do fabricante.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'diluente-reconstituicao-turno',
      label: 'Vacina reconstituída — uso',
      value: 'Usar no mesmo turno de atendimento após reconstituição; descartar ao fim do expediente',
      detail: 'Alguns fabricantes limitam a 6 horas — respeitar bula e Manual PNI.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-geladeira-domestica',
      label: 'Geladeira da sala de vacinação',
      value: 'Refrigerador exclusivo para imunobiológicos — não geladeira doméstica compartilhada',
      detail: 'Capacidade para estoque, circulação de ar e monitoramento contínuo da faixa 2 °C a 8 °C.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'imunossup-14dias',
      label: 'Imunossupressão × vacina inativada',
      value: 'Vacinas inativadas: pelo menos 14 dias antes da imunossupressão',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'intervalo-90-dias-imuno',
      label: 'Imunoglobulina × vacina atenuada',
      value: 'Intervalo mínimo de 90 dias após Ig em alguns esquemas de resgate',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'menor-1ano-limite',
      label: 'Denominador PNI — menor de 1 ano',
      value: 'Até 1 ano, 11 meses e 29 dias de idade',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'scr-1-dose',
      label: 'Tríplice viral (SCR) — 1ª dose',
      value: 'Aos 12 meses de idade',
      detail: 'Vacina atenuada; combina sarampo, caxumba e rubéola.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'scr-2-dose-scrv',
      label: 'Tríplice viral (SCR) — 2ª dose',
      value: 'Aos 15 meses de idade',
      detail:
        'CNV 2026: SCR 2ª aos 15 m (separada da varicela monovalente). Indisponibilidade de varicela mono: tetraviral (SCRV) pode substituir conforme IN. exam_vs_current: provas antigas podem citar SCRV como padrão aos 15 m.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'varicela-calendario',
      label: 'Varicela — calendário infantil',
      value: '1ª dose aos 15 meses; 2ª dose aos 4 anos',
      detail:
        'CNV 2026: varicela monovalente (VZ). Se indisponível, tetraviral pode ser usada. Não confundir 2ª dose de SCR (15 m) com 2ª de varicela (4 a).',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'hpv-esquema-adolescente',
      label: 'HPV — esquema PNI',
      value: '9 a 14 anos, 11 m 29 d: dose única (HPV4); resgate 15–19 conforme estado',
      detail:
        'Calendário Nacional 2026 / IN CNV: rotina = 1 dose. Provas antigas podem cobrar 2 doses — registrar exam_vs_current. Grupos especiais: ver IN vigente.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'febre-amarela-9m',
      label: 'Febre amarela — rotina',
      value: '1 dose aos 9 meses em áreas com recomendação vacinal',
      detail: 'Esquema de dose única na rotina; reforço conforme situação epidemiológica vigente.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'febre-amarela-area',
      label: 'Febre amarela — áreas de recomendação',
      value: 'Vacinar rotineiramente apenas onde o MS define recomendação vacinal',
      detail: 'Fora das áreas recomendadas: situações especiais (viagem, surto, profilaxia orientada).',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'hepatite-a-15m',
      label: 'Hepatite A — rotina infantil',
      value: '1 dose aos 15 meses de idade',
      detail: 'Vacina inativada intramuscular; integrada ao marco dos 15 meses no PNI.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'pneumo-10-esquema',
      label: 'Pneumocócica — esquema infantil (transição VPC20/VPC10)',
      value: '2 m: VPC20 · 4 m: VPC10 · 12 m: reforço VPC20',
      detail:
        'IN/Guia Técnico MS 2026: esquema sequencial na rotina (início oficial jun/2026). Provas antigas com 3× VPC10 (2-4-12) → exam_vs_current. ID do entry mantido por estabilidade.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vpc20-infantil-rotina-2026',
      label: 'VPC20 infantil — rotina 2026',
      value: 'D1 e reforço com VPC20; D2 do básico com VPC10 na transição',
      detail:
        'Guia Técnico introdução VPC20 no PNI (2026). Atualizar atraso até 4 a 11 m 29 d conforme IN. Não confundir com dose única VPC20 do idoso prioritário.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'pegadinha-hpv-doses',
      label: 'Pegadinha HPV',
      value: 'rotina atual = dose única 9–14 anos (não 2 ou 3 doses)',
      detail:
        'Pegadinha clássica de prova antiga (2 doses <15 / 3 doses ≥15) divergente do CNV 2024–2026 — ensinar gabarito + exam_vs_current.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vip-esquema-completo',
      label: 'VIP — esquema completo poliomielite',
      value: '3 doses aos 2, 4 e 6 meses + reforços VIP aos 15 meses e aos 4 anos',
      detail:
        'Calendário Nacional 2026 (criança): exclusivo VIP; 1º reforço 15 meses e 2º reforço aos 4 anos. VOP fora da rotina.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'dengue-calendario-2026',
      label: 'Dengue (DNG4) — calendário',
      value: '2 doses a partir dos 10 anos (até 14 a 11 m 29 d em atraso)',
      detail:
        'CNV 2026 adolescente: DNG4 no marco dos 10 anos; esquema de 2 doses. Usar mesmo laboratório no esquema.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vop-historico',
      label: 'VOP — uso histórico',
      value: 'Retirada da rotina infantil; uso residual apenas em situações excepcionais orientadas',
      detail: 'Calendário 2025: poliomielite somente com VIP. VOP não faz parte do esquema rotineiro atual.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vpp23-idoso-60',
      label: 'Pneumocócica 23-valente (VPP23) — idoso',
      value: '60 anos ou mais: indicação conforme calendário; grupos prioritários migram para VPC20 (IN 2026)',
      detail:
        'Polissacarídica; não simultânea à VPC conjugada. IN 2026: ≥60 acamados/institucionalizados e indígenas ≥5 anos sem conjugada → VPC20 (dose única) em substituição à VPP23. Demais: Manual/calendário técnico vigente.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vpc20-idoso-prioritario-2026',
      label: 'Pneumocócica 20-valente (VPC20) — grupos prioritários 2026',
      value: 'Dose única VPC20 nos grupos da IN 2026 (substitui VPP23 nesses públicos)',
      detail:
        '≥60 anos acamados e/ou institucionalizados sem vacina prévia; indígenas ≥5 anos sem comprovação de conjugada. Histórico de 2× VPP23 → considerar vacinado.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'meningo-acwy-12meses',
      label: 'Meningocócica ACWY — 12 meses',
      value: '1 dose aos 12 meses (CNV 2026 criança)',
      detail:
        'Marco dos 12 m com SCR 1ª e reforço VPC20. Distinta da menACWY do adolescente (11 a) e da menC da infância precoce.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'meningo-acwy-adolescente',
      label: 'Meningocócica ACWY — adolescente',
      value: '1 dose aos 11 anos (atraso até 14 a 11 m 29 d)',
      detail:
        'CNV 2026 adolescente: menACWY conjugada. Não confundir com dose dos 12 meses nem com meningocócica C.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'raiva-pep-conceito',
      label: 'Raiva — profilaxia pós-exposição (PEP)',
      value: 'Lavar ferimento + vacina 0/3/7/14 + soro se exposição grave (ou silvestre)',
      detail:
        'Fluxograma MS + NT 8/2022: classificação leve/grave (não OMS I–III). Leve (cão/gato observável): vacina; grave/silvestre: SAR/IGHAR + vacina. exam_vs_current: provas antigas usam categorias OMS.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'triplice-bacteriana-adulto',
      label: 'Tríplice bacteriana adulto (dT/dTpa)',
      value: 'Sem comprovação: 3 doses de dT (0, 60 e 180 dias); reforço a cada 10 anos',
      detail: 'Gestante recebe dTpa na janela gestacional; adulto usa dT ou dTpa conforme indicação e histórico de pertussis.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'febre-amarela-viajante',
      label: 'Febre amarela — viajante',
      value: 'Dose única ≥10 dias antes da viagem para área de risco, se indicada',
      detail: 'Avaliar recomendação vacinal e contraindicações (imunodeprimidos, gestantes, <9 meses). Certificado internacional quando exigido.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'bloqueio-vacinal-sarampo',
      label: 'Bloqueio vacinal — sarampo',
      value: 'Vacinar contactantes suscetíveis em até 72 horas após exposição',
      detail: 'Surto ou caso confirmado: SCR/SCRV para suscetíveis no bloqueio; Ig em ≤6 dias se contraindicação à vacina.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'registro-sis',
      label: 'Registro no SIS — vacinação',
      value: 'Registrar toda dose no sistema de informação no dia da aplicação',
      detail: 'Caderneta + SI-PNI/SIS: lote, fabricante, via, local, profissional e data — base para cobertura e recall.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'erro-vacinal-conduta',
      label: 'Erro de imunização — conduta',
      value: 'Identificar, notificar, corrigir esquema e orientar sem culpabilizar o usuário',
      detail: 'Dose fora de idade, intervalo, via ou produto errado: avaliar validade, repetir se necessário e documentar no prontuário.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'validade-frasco-aberto',
      label: 'Validade após abertura do frasco',
      value: 'Usar no mesmo turno/atendimento; descartar ao fim do expediente ou após tempo do fabricante',
      detail: 'Frascos multidose: manter 2–8 °C; não reutilizar no dia seguinte salvo orientação específica do fabricante (ex.: alguns 6 h).',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'nao-agitar-vacina',
      label: 'Preparo — não agitar',
      value: 'Não agitar vacinas adsorvidas (pentavalente, hepatite B, pneumo conjugada)',
      detail: 'Agitar pode romper agregados e reduzir eficácia; homogeneizar suavemente apenas quando o fabricante orientar.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'descarte-seringa',
      label: 'Descarte de material perfurocortante',
      value: 'Descartar agulhas e seringas em coletor amarelo sem recapar',
      detail: 'Seguir NR-32 e protocolo local; não reutilizar; descarte de resíduos infectantes conforme RDC Anvisa.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'gestante-influenza-dtpa',
      label: 'Gestante — influenza e dTpa',
      value: 'Influenza inativada em qualquer trimestre + dTpa entre 20 e 36 semanas e 6 dias a cada gestação',
      detail: 'Duas vacinas prioritárias na gestação no PNI; não substituem uma à outra.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'hepatite-b-esquema-completo',
      label: 'Hepatite B — esquema completo',
      value: '3 doses: 0, 1 e 6 meses (intervalo mínimo 4 semanas entre D1–D2 e 8 semanas entre D2–D3)',
      detail: 'RN: 1ª dose ao nascer; adolescente/adulto sem comprovação: três doses com intervalos mínimos do Manual PNI.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'scr-catchup-adolescente',
      label: 'SCR — catch-up adolescente',
      value: '2 doses com intervalo mínimo de 30 dias se suscetível',
      detail: 'Sem comprovação de 2 doses após 1 ano de idade: vacinar adolescente com SCR ou SCRV conforme idade e histórico.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'meningo-c-catchup',
      label: 'Meningocócica C — resgate',
      value: 'Lactente fora do calendário: esquema de resgate conforme idade ao iniciar (1–3 doses)',
      detail: 'Consultar quadro de resgate do Manual PNI por faixa etária; não confundir com ACWY do adolescente.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'antissepsia-alcool-70',
      label: 'Antissepsia — álcool 70%',
      value: 'Fricção com álcool 70% até secagem completa antes da manipulação de imunobiológicos',
      detail: 'Higienização das mãos e antissepsia de tampas de borracha conforme Manual da Rede de Frio.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'cobertura-rebanho-95',
      label: 'Cobertura vacinal — imunidade de rebanho',
      value: 'Meta de cobertura ≥95% para bloquear reintrodução (ex.: sarampo)',
      detail: 'Indicador epidemiológico citado em campanhas PNI — distinto de eficácia individual da vacina.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'raiva-letalidade-100',
      label: 'Raiva humana — letalidade',
      value: 'Encefalite aguda com letalidade próxima de 100% após início dos sintomas',
      detail: 'Profilaxia pós-exposição e bloqueio animal são urgentes — não há tratamento curativo após sintomas.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'rede-frio-ocupacao-70',
      label: 'Geladeira PNI — ocupação máxima',
      value: 'Não superlotar — ocupação máxima em torno de 70% para circulação de ar',
      detail: 'Alternativas de prova que fixam 70% exclusivo com bobinas são pegadinha; o princípio é não comprometer a faixa 2 °C a 8 °C.',
      sourceId: 'pni-calendario-2025',
    },
    {
      id: 'vacina-pegadinha-100-eficacia',
      label: 'Eficácia vacinal — absoluto de prova',
      value: 'Formulário «100% eficazes» é pegadinha — nenhuma vacina garante eficácia absoluta',
      detail: 'Prova testa reconhecimento de absolutismo; ensinar o gabarito sem validar o 100% como norma PNI.',
      sourceId: 'pni-calendario-2025',
    },
  ],
};
