import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Promoção à Saúde e princípios do SUS.
 * Fontes: Lei 8.080/1990 · Lei 8.142/1990 · PNPS Portaria 2.446/2014
 * (consolidada na Portaria de Consolidação nº 2/2017, Anexo I).
 */
export const PROMOCAO_SAUDE_SUS: GuidelineTable = {
  id: 'promocao-saude-sus',
  snapshot: 'Lei 8.080/8.142 + PNPS (Portaria 2.446/2014 · PRC 2/2017)',
  issuer: 'Presidência da República / Ministério da Saúde',
  title: 'Promoção à Saúde e Prevenção de Agravos',
  year: 2017,
  url: 'https://bvsms.saude.gov.br/bvs/saudelegis/gm/2017/prc0002_03_10_2017.html',
  entries: [
    {
      id: 'lei-8080',
      label: 'Lei Orgânica da Saúde',
      value: 'Lei 8.080/1990',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'art4-composicao',
      label: 'Art. 4º — composição do SUS',
      value: 'ações e serviços de saúde',
      detail: 'Prestados por órgãos e instituições públicas federais, estaduais e municipais.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'art4-gestao',
      label: 'Administração',
      value: 'direta e indireta',
      detail: 'Inclui fundações mantidas pelo Poder Público.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'principios-sus',
      label: 'Princípios doutrinários',
      value: 'universalidade, integralidade, equidade',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'principios-organizativos',
      label: 'Princípios organizativos',
      value: 'descentralização, regionalização, hierarquização, participação social',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'lei-8142',
      label: 'Lei 8.142/1990',
      value: 'participação da comunidade e conselhos de saúde',
      detail: 'Não define composição do SUS — foco em controle social.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'cf-art196',
      label: 'CF/88 Art. 196',
      value: 'saúde é direito de todos e dever do Estado',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pegadinha-so-hospital',
      label: 'Pegadinha composição',
      value: 'SUS não é só hospital nem só atenção básica',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'ottawa-carta',
      label: 'Carta de Ottawa (1986)',
      value: 'promoção da saúde como processo de capacitação comunitária',
      detail: 'OMS/MS: saúde não é só ausência de doença — é recurso para vida plena.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'ottawa-cinco-acoes',
      label: 'Carta de Ottawa — cinco ações',
      value: 'políticas saudáveis · ambientes favoráveis · ação comunitária · habilidades · reorientar serviços',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pnps-portaria',
      label: 'PNPS — Política Nacional de Promoção da Saúde',
      value: 'Portaria GM/MS nº 2.446/2014 (Anexo I da Portaria de Consolidação nº 2/2017)',
      detail:
        'Redefine a PNPS — equidade, participação social, autonomia; vigente via consolidação das políticas nacionais de saúde.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pnps-temas-prioritarios',
      label: 'PNPS — temas prioritários (exemplos)',
      value: 'alimentação · atividade física · tabaco · álcool · violência · ambiente · cultura da paz',
      detail:
        'Art. 10 Portaria 2.446/2014 — agendas transversais de promoção alinhadas ao Plano Nacional de Saúde e pactos interfederativos.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'determinantes-sociais',
      label: 'Determinantes sociais da saúde',
      value: 'condições de vida, trabalho, educação, renda e acesso a bens',
      detail: 'CSDH/OMS e MS: desigualdades sociais estruturam risco e adoecimento.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'prevencao-primaria',
      label: 'Prevenção primária',
      value: 'evitar surgimento da doença ou agravo',
      detail: 'Vacinação, saneamento, educação em saúde, legislação sanitária.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'prevencao-secundaria',
      label: 'Prevenção secundária',
      value: 'diagnóstico precoce e tratamento oportuno',
      detail: 'Rastreamento (mamografia, Papanicolau, glicemia) e detecção em fase assintomática.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'prevencao-terciaria',
      label: 'Prevenção terciária',
      value: 'reduzir complicações, incapacidade e reincidência',
      detail: 'Reabilitação, fisioterapia pós-AVC, controle de DM descompensado.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'educacao-saude',
      label: 'Educação em saúde',
      value: 'processo de construção de autonomia e protagonismo do sujeito',
      detail: 'PNPS/COFEN: diálogo e práticas educativas — não só transmissão de informação.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pegadinha-prevencao-terciaria',
      label: 'Pegadinha níveis de prevenção',
      value: 'reabilitação é prevenção terciária, não primária',
      detail: 'Primária = evitar adoecer; secundária = detectar cedo; terciária = limitar sequelas.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'art6-diretrizes',
      label: 'Lei 8.080 Art. 6º — diretrizes',
      value: 'descentralização · atendimento integral · participação da comunidade',
      detail: 'Diretrizes do SUS — distintas dos princípios doutrinários (universalidade, integralidade, equidade).',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'art7-direitos-usuario',
      label: 'Lei 8.080 Art. 7º — direitos do usuário',
      value: 'atendimento sem discriminação · acesso à rede · sigilo · negativa fundamentada',
      detail: 'Inclui ambiente seguro, tratamento digno, documentação completa e conhecimento científico atualizado.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'determinantes-dahlgren-whitehead',
      label: 'Determinantes — modelo Dahlgren-Whitehead',
      value: 'camadas: estilo de vida → redes sociais → condições de vida/trabalho → macrodeterminantes',
      detail: 'Indivíduo no centro; determinantes sociais estruturam risco — promoção atua nas camadas externas.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pnps-eixos-acoes',
      label: 'PNPS — eixos de ação',
      value: 'ambiente e território · vida no trabalho · educação · alimentação · cultura · esporte · mobilidade',
      detail: 'Portaria 2.446/2014: promoção transversal — não se restringe à sala de vacina ou consultório.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'ottawa-estrategias-exemplos',
      label: 'Ottawa — exemplos por estratégia',
      value: 'lei antifumo · parque urbano · grupo comunitário · escola · consulta participativa',
      detail: 'Cada uma das cinco ações da Carta de Ottawa tem exemplo concreto em prova de promoção.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'prevencao-exemplos-classificacao',
      label: 'Níveis de prevenção — exemplos',
      value: 'primária: vacina · secundária: mamografia · terciária: fisioterapia pós-AVC',
      detail: 'Quaternária (evitar iatrogenia) aparece em provas avançadas — não confundir com primária.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'enfermagem-educacao-saude',
      label: 'Enfermagem — educação em saúde',
      value: 'facilitar autonomia, não impor conduta',
      detail: 'COFEN/PNPS: práticas educativas dialógicas na APS — orientação sobre IST, vacina, aleitamento.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'cf-art196-dever-estado',
      label: 'CF Art. 196 — dever do Estado',
      value: 'garantir saúde por políticas econômicas e sociais',
      detail: 'Direito de todos + dever do Estado — base constitucional da universalidade do SUS.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pegadinha-art4-art6',
      label: 'Pegadinha Art. 4º × Art. 6º',
      value: 'Art. 4º define composição; Art. 6º define diretrizes',
      detail: 'Composição = ações e serviços públicos; diretrizes = descentralização, integralidade, participação.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pegadinha-promocao-curativo',
      label: 'Pegadinha promoção × prevenção',
      value: 'promoção amplia autonomia; prevenção foca evitar/detectar agravo',
      detail: 'Promoção não é só campanha de vacina — inclui determinantes sociais e empowerment.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pegadinha-sus-privatizacao',
      label: 'Pegadinha SUS × setor privado',
      value: 'SUS integra público e privado contratado — não é só hospital público',
      detail: 'Lei 8.080: serviços privados podem participar mediante contrato ou convênio; controle social via conselhos.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pegadinha-lei-8142-composicao',
      label: 'Pegadinha Lei 8.142',
      value: '8.142 trata participação social — não define composição do SUS',
      detail: 'Conselhos e conferências de saúde; confundir com Lei 8.080 é pegadinha clássica.',
      sourceId: 'promocao-saude-sus',
    },
    {
      id: 'pegadinha-universalidade-seletiva',
      label: 'Pegadinha universalidade',
      value: 'SUS é universal — acesso para todos, não só contribuintes',
      detail: 'Equidade corrige desigualdades; integralidade = conjunto de ações preventivas e curativas.',
      sourceId: 'promocao-saude-sus',
    },
  ],
};
