import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Processo de Enfermagem (PE) / SAE.
 * Fonte vigente: Resolução COFEN nº 736/2024 (revoga a 358/2009) + Lei 7.498/86.
 * ID da tabela mantido (`sae-cofen-358`) por estabilidade de sourceId nos goldens.
 * @see https://www.cofen.gov.br/resolucao-cofen-no-736-de-17-de-janeiro-de-2024/
 */
export const SAE_COFEN_358: GuidelineTable = {
  id: 'sae-cofen-358',
  snapshot: 'Processo de Enfermagem — COFEN 736/2024 (revoga 358/2009)',
  issuer: 'COFEN',
  title: 'Processo de Enfermagem e SAE',
  year: 2024,
  url: 'https://www.cofen.gov.br/resolucao-cofen-no-736-de-17-de-janeiro-de-2024/',
  entries: [
    {
      id: 'sae-etapas',
      label: 'Etapas do Processo de Enfermagem',
      value: 'avaliação → diagnóstico → planejamento → implementação → evolução',
      detail:
        'Res. COFEN 736/2024: 5 etapas cíclicas. Nomenclatura antiga (coleta/avaliação final) pode aparecer em provas — exam_vs_current.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-privativa-diagnostico',
      label: 'Privativa do enfermeiro',
      value: 'diagnóstico de enfermagem + prescrição de enfermagem',
      detail:
        'Res. COFEN 736/2024 Art. 6º + Lei 7.498/86. TE participa com anotações, implementação e checagem sob supervisão.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-anotacao',
      label: 'Anotação de enfermagem',
      value: 'registro das ações executadas pela equipe de enfermagem',
      detail: '736/2024: TE/auxiliar — anotação + checagem da prescrição; não diagnóstico nem evolução.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-tecnico-registro',
      label: 'Técnico / auxiliar',
      value: 'anotação, implementação dos cuidados prescritos e checagem — sob supervisão',
      detail: 'Não registra diagnóstico nem evolução (736/2024 Art. 7º).',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-identificacao',
      label: 'Identificação no registro',
      value: 'carimbo, nome legível e assinatura obrigatórios',
      detail: 'Não é facultativo no documento firmado.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-integridade',
      label: 'Integridade do registro',
      value: 'permanente, legível, sem rasura indevida',
      detail: 'Não registrar a lápis nem rasuras sem protocolo.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-veracidade',
      label: 'Veracidade',
      value: 'vedado registrar cuidado não executado',
      detail: 'Proibido registrar em nome de outro profissional.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-prontuario',
      label: 'Prontuário',
      value: 'documento compartilhado da equipe multiprofissional',
      detail: 'Equipe de enfermagem registra o que executa.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-nanda',
      label: 'Diagnóstico NANDA-I',
      value: 'formulação clínica privativa do enfermeiro',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-nanda-taxonomia',
      label: 'NANDA-I',
      value: 'taxonomia de diagnósticos de enfermagem — problema, risco ou promoção da saúde',
      detail: 'Base para identificar fenômenos humanos que a equipe de enfermagem pode tratar.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-nic',
      label: 'NIC',
      value: 'Nursing Interventions Classification — intervenções de enfermagem',
      detail: 'Catálogo de ações que o enfermeiro prescreve e delega na implementação.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-noc',
      label: 'NOC',
      value: 'Nursing Outcomes Classification — resultados de enfermagem',
      detail: 'Indicadores mensuráveis para avaliar se o diagnóstico foi resolvido ou melhorou.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-coleta-dados',
      label: 'Avaliação de Enfermagem (etapa 1)',
      value: 'história de saúde, exame físico e dados complementares — contínua',
      detail:
        '736/2024: etapa inicial chamada Avaliação (substitui “coleta de dados” da 358). Enfermeiro conduz; TE colabora conforme competência.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-diagnostico-enfermagem',
      label: 'Diagnóstico de enfermagem',
      value: 'julgamento clínico sobre respostas humanas — privativo do enfermeiro',
      detail: 'Formulação PES: Problema + Etiologia + Sinais/Sintomas (NANDA-I).',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-prescricao-enfermagem',
      label: 'Prescrição de enfermagem',
      value: 'planejamento das intervenções (NIC) com metas e prazos',
      detail: 'Etapa de planejamento — documento que orienta a implementação dos cuidados.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-implementacao',
      label: 'Implementação',
      value: 'execução das intervenções prescritas',
      detail: 'Enfermeiro supervisiona, delega e executa; técnico/auxiliar registra cuidados realizados.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-avaliacao-resultado',
      label: 'Evolução de Enfermagem (etapa 5)',
      value: 'comparar achados atuais com metas (NOC) — revisão do PE',
      detail:
        '736/2024: etapa final = Evolução. Enfermeiro registra todas as etapas; decide continuar, modificar ou encerrar o plano.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-cinco-etapas',
      label: 'PE — 5 etapas integradas',
      value: 'avaliação → diagnóstico → planejamento → implementação → evolução',
      detail: 'Res. COFEN 736/2024 — processo cíclico e contínuo (revoga 358/2009).',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-etapa1-coleta',
      label: 'Etapa 1 — Avaliação de Enfermagem',
      value: 'anamnese, exame físico de enfermagem, exames complementares e dados do prontuário',
      detail: '736/2024: Avaliação (inicial e contínua). Enfermeiro conduz; TE colabora na aferição e anotação.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-etapa2-diagnostico',
      label: 'Etapa 2 — Diagnóstico de enfermagem',
      value: 'julgamento clínico sobre respostas humanas — privativo do enfermeiro',
      detail: 'Usa taxonomia NANDA-I; não confundir com diagnóstico médico (CID).',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-etapa3-planejamento',
      label: 'Etapa 3 — Planejamento (prescrição)',
      value: 'prescrição de enfermagem com metas, prazos e intervenções (NIC)',
      detail: 'Documento orientador da implementação — enfermeiro prescreve e delega conforme competência.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-etapa4-implementacao',
      label: 'Etapa 4 — Implementação',
      value: 'execução das intervenções prescritas e registro dos cuidados realizados',
      detail: 'Enfermeiro supervisiona, delega e executa; técnico/auxiliar registra anotação de enfermagem.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-etapa5-avaliacao',
      label: 'Etapa 5 — Evolução de Enfermagem',
      value: 'comparar resultado atual com metas (NOC) e revisar o PE',
      detail: '736/2024: Evolução (antes “Avaliação”). Enfermeiro registra; TE não elabora evolução.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-privativa-lista',
      label: 'Privativas do enfermeiro (Lei 7.498/86 + 736/2024)',
      value: 'diagnóstico de enfermagem + prescrição de enfermagem',
      detail:
        '736/2024 Art. 6º. Enfermeiro registra todas as etapas do PE; TE: anotação, implementação e checagem.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-tecnico-anotacao',
      label: 'Técnico — anotação de enfermagem',
      value: 'anotação + implementação + checagem — não diagnóstico, prescrição nem evolução',
      detail: 'Res. COFEN 736/2024 Art. 7º — sob supervisão do enfermeiro; carimbo e assinatura.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-vs-pe-736',
      label: 'SAE × Processo de Enfermagem',
      value: 'PE = método de trabalho em 5 etapas; SAE organiza a assistência',
      detail:
        '736/2024 distingue conceitualmente SAE e PE — provas antigas tratam como sinônimos (exam_vs_current).',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-nanda-risco-infeccao',
      label: 'NANDA — Risco de infecção',
      value: 'diagnóstico de risco — vulnerabilidade a patógenos que comprometem defesas',
      detail: 'Ex.: pós-operatório, imunossupressão, cateter venoso; etiologia e fatores de risco na formulação PES.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-nanda-dor-aguda',
      label: 'NANDA — Dor aguda',
      value: 'experiência sensorial e emocional desagradável — início recente, causa identificável',
      detail: 'Diferencia de dor crônica; sinais/sintomas: expressão facial, FC elevada, proteção da área.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-nic-funcao',
      label: 'NIC — função no SAE',
      value: 'classifica intervenções de enfermagem prescritas na etapa de planejamento',
      detail: 'Ex.: controle de infecção, analgesia, orientação — base para delegação e implementação.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-noc-funcao',
      label: 'NOC — função no SAE',
      value: 'indicadores mensuráveis para avaliar se o diagnóstico melhorou ou foi resolvido',
      detail: 'Usado na etapa de avaliação — escala Likert ou critério objetivo (ex.: ausência de febre).',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-pes-estrutura',
      label: 'Diagnóstico PES — estrutura',
      value: 'Problema (P) + Etiologia (E) + Sinais/Sintomas (S)',
      detail: 'NANDA-I — etiologia ligada ao problema por "relacionado a"; sinais com "evidenciado por".',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-pes-exemplo',
      label: 'Diagnóstico PES — exemplo',
      value: 'Dor aguda relacionada a procedimento cirúrgico, evidenciada por relato verbal e proteção da incisão',
      detail: 'Modelo clássico de prova — P + E + S na mesma frase diagnóstica.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-prescricao-conteudo',
      label: 'Prescrição de enfermagem — conteúdo',
      value: 'intervenções (NIC), frequência, responsável e meta (NOC) por diagnóstico',
      detail: 'Etapa de planejamento — documento legal privativo do enfermeiro.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-prontuario-carimbo',
      label: 'Prontuário — carimbo e assinatura',
      value: 'nome legível, carimbo com COREN e assinatura em todo registro firmado',
      detail: 'Res. COFEN 736/2024 — identificação obrigatória; registro sem autoria é inválido.',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-pegadinha-diagnostico-medico',
      label: 'Pegadinha SAE — diagnóstico médico',
      value: 'CID/diagnóstico médico não substitui diagnóstico de enfermagem',
      detail: 'Banca troca "pneumonia" (médico) por "Risco de infecção" ou "Déficit de troca gasosa" (enfermagem).',
      sourceId: 'sae-cofen-358',
    },
    {
      id: 'sae-pegadinha-anotacao-evolucao',
      label: 'Pegadinha SAE — anotação × evolução',
      value: 'anotação = cuidado executado; evolução = avaliação clínica privativa do enfermeiro',
      detail: 'Técnico faz anotação; evolução exige julgamento clínico — só enfermeiro.',
      sourceId: 'sae-cofen-358',
    },
  ],
};
