import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Saúde do adolescente.
 * Fonte: MS — Caderneta de Saúde do Adolescente 4ª ed. (2024) + Calendário Nacional 2026 (HPV).
 * @see https://www.gov.br/saude/pt-br/composicao/saps/publicacoes/cadernetas-e-cartoes
 */
export const SAUDE_ADOLESCENTE_MS: GuidelineTable = {
  id: 'saude-adolescente-ms',
  snapshot: 'Caderneta Adolescente MS 2024 + HPV dose única CNV 2026',
  issuer: 'Ministério da Saúde',
  title: 'Saúde do Adolescente',
  year: 2026,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-do-adolescente/publicacoes/caderneta-de-saude-da-adolescente-feminina-4a-edicao',
  entries: [
    {
      id: 'adolescente-escuta',
      label: 'Consulta de enfermagem',
      value: 'privacidade e escuta qualificada',
      detail: 'Respeitar autonomia progressiva — linguagem acessível.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'gravidez-adolescente',
      label: 'Gravidez na adolescência',
      value: 'aumenta riscos materno-fetais',
      detail: 'Exige acompanhamento pré-natal precoce.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'sigilo-adolescente',
      label: 'Sigilo profissional',
      value: 'protegido com limites legais',
      detail: 'Quebra quando há risco grave — não é absoluto nem inexistente.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'contracepcao-adolescente',
      label: 'Saúde sexual e reprodutiva',
      value: 'orientação sobre contracepção integra o cuidado',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'acolhimento-sem-julgamento',
      label: 'Acolhimento',
      value: 'vínculo sem julgamento',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'pegadinha-sigilo-absoluto',
      label: 'Pegadinha sigilo',
      value: 'não quebrar sigilo sem critério em qualquer tema',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'bullying-violencia-escolar',
      label: 'Bullying e cyberbullying',
      value: 'violência interpessoal — acolher, escutar e notificar rede',
      detail: 'MS: identificar sinais (isolamento, queda escolar, lesões) e articular escola, família e NASF.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'automutilacao-risco',
      label: 'Automutilação (NSSI)',
      value: 'sinal de sofrimento psíquico — avaliar risco e encaminhar',
      detail: 'Não minimizar; investigar ideação suicida associada; acionar CAPS/urgência conforme gravidade.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'hpv-adolescente-pni',
      label: 'Vacina HPV (PNI)',
      value: '9 a 14 anos, 11 m 29 d — dose única (HPV4)',
      detail:
        'Calendário Nacional 2026: 1 dose na rotina (meninas e meninos). Resgate 15–19 conforme estratégia estadual. Provas antigas com 2 doses → exam_vs_current.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'faixa-adolescente-ms',
      label: 'Faixa etária adolescente (saúde)',
      value: '10 a 19 anos (OMS/MS nos serviços)',
      detail:
        'ECA: 12 a 18 anos. Caderneta MS e calendário do adolescente usam 10–19 anos — pegadinha clássica de prova.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'ist-testagem-adolescente',
      label: 'IST na adolescência',
      value: 'orientar prevenção combinada e ofertar testagem',
      detail: 'Preservativo, vacina HBV/HPV e rastreio conforme exposição — sigilo respeitado na APS.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'alimentacao-adolescente',
      label: 'Alimentação saudável',
      value: 'evitar dietas restritivas e ultraprocessados',
      detail: 'Guia Alimentar MS: priorizar in natura; atenção a transtornos alimentares e imagem corporal.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'atividade-fisica-adolescente',
      label: 'Atividade física',
      value: '≥60 min/dia de moderada a vigorosa',
      detail: 'OMS/MS: reduz sedentarismo; esporte escolar e lazer como promoção de saúde.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'alcool-drogas-adolescente',
      label: 'Álcool e outras drogas',
      value: 'abstinência na adolescência — prevenção e acolhimento',
      detail: 'Uso precoce aumenta risco de dependência; escuta qualificada sem julgamento.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'pegadinha-hpv-3-doses',
      label: 'Pegadinha HPV',
      value: 'não confundir esquema de 2 doses (<15 anos) com 3 doses (≥15 anos)',
      detail: 'Banca troca idade de corte e intervalo entre doses.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'transtornos-alimentares',
      label: 'Transtornos alimentares',
      value: 'anorexia, bulimia e compulsão — avaliar IMC, purga e distorção corporal',
      detail: 'MS: sinais de alerta (perda rápida de peso, isolamento); encaminhar multiprofissional sem julgamento.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'transtornos-alimentares-95-mulheres',
      label: 'Transtornos alimentares — epidemiologia',
      value: '95%',
      detail: 'Apesar de ocorrerem em homens, ~95% dos casos acometem mulheres — pico em adolescentes e jovens (prova FAU).',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'metodos-contraceptivos',
      label: 'Métodos contraceptivos',
      value: 'barreira, hormonal (COC, injetável, implante), DIU e LAM',
      detail: 'Adolescente tem direito à orientação na APS; preservativo é único que previne IST + gravidez.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'consentimento-adolescente-eca',
      label: 'Consentimento do adolescente (ECA)',
      value: '≥12 anos pode consentir procedimentos de baixa complexidade com orientação',
      detail: 'Art. 14 ECA: autonomia progressiva; sigilo respeitado salvo risco grave ou incapacidade.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'gravidez-adolescente-complicacoes',
      label: 'Gravidez adolescente — riscos',
      value: 'eclâmpsia, parto prematuro, baixo peso ao nascer e abandono escolar',
      detail: 'Pré-natal precoce na APS; apoio familiar sem estigmatização.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'ideacao-suicida-adolescente',
      label: 'Ideação suicida',
      value: 'perguntar diretamente sobre pensamentos de morte — não induz risco',
      detail: 'CVV 188; encaminhar urgência se plano ou tentativa; notificar rede conforme protocolo local.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'depressao-adolescente',
      label: 'Depressão na adolescência',
      value: 'humor deprimido, anedonia, alteração de sono e rendimento escolar',
      detail: 'Rastreio na consulta de enfermagem; diferenciar luto, uso de substâncias e transtorno bipolar.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'preservativo-dupla-protecao',
      label: 'Dupla proteção',
      value: 'preservativo + outro método contraceptivo',
      detail: 'Previne gravidez e IST simultaneamente — orientação central na saúde sexual do adolescente.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'atividade-fisica-oms-detalhe',
      label: 'Atividade física — OMS',
      value: '≥60 min/dia moderada a vigorosa; fortalecimento muscular ≥3×/semana',
      detail: 'Limitar tempo de tela; atividade regular reduz obesidade, depressão e sedentarismo.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'substancias-prevencao-escola',
      label: 'Uso de substâncias — prevenção',
      value: 'tabaco, álcool, cannabis e outras drogas — início precoce aumenta dependência',
      detail: 'Estratégias na escola e comunidade; acolhimento e encaminhamento ao CAPS-ad.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'violencia-sexual-adolescente',
      label: 'Violência sexual',
      value: 'acolhimento, profilaxia IST/HIV e contracepção de emergência',
      detail: 'Notificação compulsória; preservar vestígios; não exigir boletim de ocorrência para atendimento.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'pegadinha-consentimento-pais',
      label: 'Pegadinha consentimento',
      value: 'nem todo atendimento ao adolescente exige autorização dos pais',
      detail: 'ECA permite autonomia progressiva ≥12 anos; banca confunde com incapacidade civil absoluta.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'puberdade-tardia-meninas',
      label: 'Puberdade tardia — meninas',
      value: 'sem desenvolvimento mamário dos 12 aos 13 anos',
      detail: 'Ausência de broto mamário (Tanner M1) após 12–13 anos sugere atraso puberal — investigar.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'puberdade-tardia-meninos',
      label: 'Puberdade tardia — meninos',
      value: 'sem hipertrofia testicular (< 4 mL) até 13-14 anos',
      detail: 'Volume < 4 mL indica estágio G1 (pré-puberal); hipertrofia ausente até 13–14 anos = investigar.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'tanner-puberal',
      label: 'Estágios de Tanner',
      value: 'avaliação padronizada de mamas, genitais masculinos e pelos pubianos',
      detail: 'Complementa marcos cronológicos no exame físico do adolescente.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'obesidade-comorbidades-dm-depressao',
      label: 'Obesidade adolescente — comorbidades',
      value: 'diabetes tipo 2 + depressão',
      detail: 'Complicações clássicas: metabólicas (DM2) e psíquicas (depressão/estigma). Não confundir com carências.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'escore-z-imc-sobrepeso',
      label: 'Escore Z IMC — sobrepeso (5–19 anos)',
      value: '+1 < Z ≤ +2',
      detail: 'Caderneta/OMS: sobrepeso; orientar alimentação e atividade física.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'escore-z-imc-obesidade',
      label: 'Escore Z IMC — obesidade',
      value: '+2 < Z ≤ +3',
      detail: 'Obesidade; obesidade grave = Z > +3 (não rotular +2 a +3 como grave).',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'escore-z-imc-magreza',
      label: 'Escore Z IMC — magreza / magreza acentuada',
      value: 'magreza −3 ≤ Z < −2 · acentuada Z < −3',
      detail: 'Não confundir magreza com magreza severa/acentuada (Z < −3).',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'escore-z-estatura-muito-baixa',
      label: 'Escore Z estatura — muito baixa',
      value: 'Z < −3',
      detail: 'Estatura muito baixa ≠ faixa −1 a −2 (não caracteriza baixa estatura grave).',
      sourceId: 'saude-adolescente-ms',
    },
  ],
};
