import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Pré-natal de baixo risco — Caderno AB nº 32 / Linha de Cuidado MS.
 * Fonte: https://bvsms.saude.gov.br/bvs/publicacoes/cadernos_atencao_basica_32_prenatal.pdf
 */
export const SAUDE_MULHER_PRENATAL: GuidelineTable = {
  id: 'sm-prenatal-baixo-risco-ms',
  snapshot: 'Caderno AB 32 — Pré-natal baixo risco',
  issuer: 'Ministério da Saúde',
  title: 'Atenção ao pré-natal de baixo risco',
  year: 2012,
  url: 'https://bvsms.saude.gov.br/bvs/publicacoes/cadernos_atencao_basica_32_prenatal.pdf',
  entries: [
    {
      id: 'prenatal-consultas-min',
      label: 'Número mínimo de consultas',
      value: 'Mínimo de 6 consultas de pré-natal',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-periodicidade-28',
      label: 'Periodicidade até 28 semanas',
      value: 'Consultas mensais até a 28ª semana de gestação',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-periodicidade-28-36',
      label: 'Periodicidade 28–36 semanas',
      value: 'Consultas quinzenais entre a 28ª e a 36ª semana',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-periodicidade-36',
      label: 'Periodicidade após 36 semanas',
      value: 'Consultas semanais a partir da 36ª semana até o parto',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-glicemia-jejum',
      label: 'Glicemia de jejum — 1º trimestre',
      value: 'Solicitar na primeira consulta; referência até 85 mg/dL',
      detail: 'Se >85 mg/dL ou fator de risco → TTGO 75g entre 24 e 28 semanas.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-ttgo',
      label: 'Teste tolerância glicose (TTGO 75g)',
      value: 'Entre 24 e 28 semanas de gestação',
      detail: 'Dose 75g de glicose quando indicado.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-vdrl-hiv-1',
      label: 'Sífilis e HIV — 1ª consulta',
      value: 'VDRL/RPR e anti-HIV na primeira consulta',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-vdrl-hiv-3',
      label: 'Sífilis e HIV — 3º trimestre',
      value: 'Repetir VDRL e anti-HIV no 3º trimestre',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-hemograma',
      label: 'Hemograma',
      value: '1ª consulta e 3º trimestre',
      detail: 'Referência comum em prova: Hb ≥11 g/dL no 3º trimestre.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-urina',
      label: 'Urina tipo I / urocultura',
      value: '1ª consulta e 3º trimestre',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-bacterioscopia-37',
      label: 'Bacterioscopia vaginal',
      value: 'A partir de 37 semanas quando indicado',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-41-semanas',
      label: 'Pós-data (41 semanas)',
      value: 'Avaliar bem-estar fetal a partir de 41 semanas',
      detail: 'Considerar indução do trabalho de parto se indicado.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'puerperio-consulta',
      label: 'Consulta de puerpério',
      value: 'Até 42 dias após o parto',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'puerperio-visita',
      label: 'Visita domiciliar puerpério',
      value: 'Visita na primeira semana após alta do recém-nascido',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-altura-uterina',
      label: 'Altura uterina',
      value: 'Aferir a partir de 12 semanas; gráfico AU × idade gestacional',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-pressao',
      label: 'PA na gestação',
      value: 'Aferir em toda consulta; hipertensão ≥140 × 90 mmHg',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'parto-humanizado',
      label: 'Parto humanizado (PNH/MS)',
      value: 'Direito à acompanhante, ambiente acolhedor e participação da mulher',
      detail: 'Política Nacional de Humanização: cuidado respeitoso e evidências no parto normal.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'parto-humanizado-enfermagem',
      label: 'Enfermagem no parto',
      value: 'Monitorar SV, contrações, progressão e bem-estar materno-fetal',
      detail: 'COFEN: técnico/enfermeiro atuam na assistência humanizada e segurança do parto.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'puerperio-imediato',
      label: 'Puerpério imediato',
      value: 'Primeiras 24 h após o parto — vigilância de hemorragia e estabilização',
      detail: '1ª hora: pele a pele, amamentação e avaliação de sangramento (útero contraído).',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'puerperio-tardio',
      label: 'Puerpério tardio',
      value: 'Até 6 a 8 semanas após o parto',
      detail: 'Involução uterina, lactação, contracepção e saúde mental materna.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'amenorreia-primaria',
      label: 'Amenorreia primária',
      value: 'Ausência de menarca aos 15 anos com caracteres sexuais secundários',
      detail: 'Ou 5 anos após telarca se antes dos 15 anos — investigar causas orgânicas/hormonais.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'amenorreia-secundaria',
      label: 'Amenorreia secundária',
      value: 'Ausência de menstruação por ≥3 ciclos regulares ou ≥6 meses se irregular',
      detail: 'Excluir gestação; avaliar causas hipotalâmicas, ovarianas e uterinas.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'climaterio-menopausa',
      label: 'Climatério e menopausa',
      value: 'Climatério: transição até menopausa; menopausa = 12 meses sem menstruação',
      detail: 'Fase de declínio ovariano; sintomas vasomotores e rastreios conforme idade.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'papanicolau-inicio',
      label: 'Rastreio câncer de colo (Papanicolau)',
      value: 'Iniciar aos 25 anos após início da vida sexual',
      detail: 'INCA/MS: citologia oncótica até 64 anos na ausência de lesão de alto grau.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'papanicolau-periodicidade',
      label: 'Papanicolau — periodicidade',
      value: 'A cada 3 anos se exames anteriores normais',
      detail: 'Dois exames anuais normais podem espaçar para trienal; seguir protocolo local vigente.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-exames-1-tri-pacote',
      label: 'Exames — 1º trimestre (pacote)',
      value: 'Hemograma, tipagem/Coombs, glicemia jejum, VDRL, anti-HIV, HBsAg, urina I, urocultura, citologia se indicado',
      detail: 'Caderno AB 32: solicitar na primeira consulta ou o mais precoce possível.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-exames-2-tri-pacote',
      label: 'Exames — 2º trimestre',
      value: 'TTGO 75g entre 24 e 28 semanas; ultrassom morfológico ~20–24 semanas',
      detail: 'Glicemia de jejum alterada no 1º tri também indica TTGO no intervalo 24–28 sem.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-exames-3-tri-pacote',
      label: 'Exames — 3º trimestre (pacote)',
      value: 'Repetir VDRL, anti-HIV, hemograma e urina I/urocultura',
      detail: 'Bacterioscopia vaginal (Streptococcus grupo B) a partir de 37 semanas quando protocolo local exige.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-hiv-teste-rapido-parto',
      label: 'HIV — admissão obstétrica',
      value: 'Teste rápido na admissão se status desconhecido ou sem acompanhamento',
      detail: 'Objetivo: profilaxia intraparto e do RN quando indicado — não substitui rastreio no pré-natal.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-ttgo-interpretacao',
      label: 'TTGO 75g — valores de referência',
      value: 'Jejum <92; 1h <180; 2h <153 mg/dL (critérios IADPSG/OMS adotados no MS)',
      detail: 'Um valor alterado classifica diabetes mellitus gestacional — encaminhar linha de cuidado.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-bacterioscopia-strepto-b',
      label: 'Streptococcus grupo B — 37 semanas',
      value: 'Coleta de swab vaginal/retal entre 35 e 37 semanas em protocolos de rastreio',
      detail: 'Resultado positivo → profilaxia antibiótica intraparto; negativo não exclui colonização transitória.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-pa-hipertensao-gestacional',
      label: 'Hipertensão gestacional',
      value: 'PA ≥140 × 90 mmHg após 20 semanas sem proteinúria',
      detail: 'Diferenciar de hipertensão crônica (diagnóstico antes da 20ª semana ou pré-gestacional).',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-pa-pre-eclampsia',
      label: 'Pré-eclâmpsia — sinais de alerta',
      value: 'PA elevada + proteinúria ou sinais de gravidade (cefaleia, escotomas, epigastralgia, plaquetopenia)',
      detail: 'Encaminhar urgência obstétrica; enfermagem monitora PA, diurese e reflexos.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-au-curva-padrao',
      label: 'Altura uterina — curva de crescimento',
      value: 'Medir com fita métrica do púbis à fundo uterino; registrar em gráfico AU × IG',
      detail: 'Desvio >2 cm da curva → avaliar IG, polidrâmnio/oligoâmnio e crescimento fetal.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'prenatal-movimentos-fetais-orientacao',
      label: 'Movimentos fetais — orientação',
      value: 'Informar gestante a perceber movimentos a partir de ~18–20 semanas',
      detail: 'Redução súbita ou ausência → procurar serviço no mesmo dia; cardiotocografia complementa avaliação.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'parto-humanizado-acompanhante',
      label: 'Acompanhante de livre escolha',
      value: 'Direito a um acompanhante durante trabalho de parto, parto e puerpério imediato',
      detail: 'PNH/MS: não restringir por horário ou vínculo — inclui doula quando política local permitir.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'puerperio-tardio-42-dias',
      label: 'Puerpério tardio — limite 42 dias',
      value: 'Consulta de puerpério até o 42º dia pós-parto',
      detail: 'Pegadinha: não confundir com “30 dias” — MS define puerpério até 42 dias; tardio até 6–8 semanas.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'puerperio-pegadinha-30-dias',
      label: 'Pegadinha — encerrar puerpério aos 30 dias',
      value: '30 dias não é o limite da consulta puerperal — correto até 42º dia',
      detail: 'Distrator clássico em prova: “puerpério encerra aos 30 dias”.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'amenorreia-beta-hcg',
      label: 'Amenorreia — primeira investigação',
      value: 'Excluir gestação (beta-HCG) antes de encaminhar causas hormonais',
      detail: 'Válido para amenorreia primária tardia e secundária — prova costuma cobrar esta ordem.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'contracepcao-metodos-categorias',
      label: 'Contracepção — categorias',
      value: 'Barreira, hormonais combinados/progestagênio, LARC (DIU, implante), comportamentais',
      detail: 'Escolha compartilhada no planejamento familiar; lactante: priorizar progestagênio ou LARC.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'contracepcao-puerperio-lactacao',
      label: 'Contracepção no puerpério',
      value: 'Iniciar orientação antes da alta; método seguro conforme AM exclusivo e tempo pós-parto',
      detail: 'Método de amenorreia lactacional (MAL) exige critérios — não é garantia isolada em prova.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'violencia-sinan-notificacao',
      label: 'Violência contra a mulher — notificação',
      value: 'Notificar compulsoriamente ao SINAN (violência doméstica, sexual, obstétrica)',
      detail: 'Sigilo profissional não impede notificação epidemiológica; acolhimento e encaminhamento à rede.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'aleitamento-materno-exclusivo',
      label: 'Aleitamento materno exclusivo',
      value: 'AM exclusivo até 6 meses; complementar alimentos saudáveis após, mantendo AM até 2 anos ou mais',
      detail: 'MS/OMS: colostro nas primeiras horas; apoio à pega e ordenha quando necessário.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'planejamento-familiar-aps',
      label: 'Planejamento familiar na APS',
      value: 'Oferta de métodos e orientação em toda consulta de mulher em idade fértil',
      detail: 'Inclui pré-concepcional, intervalo interpartal e contracepção pós-aborto ou puerpério.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'pegadinha-prenatal-consultas-4',
      label: 'Pegadinha — número de consultas',
      value: 'Mínimo 6 consultas, não 4',
      detail: 'Programa de humanização e Caderno AB 32: 6+ consultas; prova antiga citava 4 — desatualizado.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    {
      id: 'pegadinha-prenatal-ttgo-1-tri',
      label: 'Pegadinha — TTGO no 1º trimestre',
      value: 'TTGO 75g rotineiro não é no 1º trimestre',
      detail: '1º tri: glicemia de jejum; TTGO entre 24 e 28 semanas (salvo protocolo de alto risco).',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
    // — Parto humanizado OMS (reforço handcraft mulher_parto) —
    {
      id: 'oms-ctg-seletiva',
      label: 'OMS — monitorização fetal',
      value: 'Cardiotocografia contínua não é obrigatória para todas as gestantes de baixo risco',
      detail: 'Recomenda-se monitorização seletiva conforme evolução do trabalho de parto — pegadinha I falsa em V/F.',
      sourceId: 'sm-parto-oms-who',
    },
    {
      id: 'oms-metodos-nao-farmacologicos',
      label: 'OMS — alívio não farmacológico da dor',
      value: 'Oferecer métodos não farmacológicos (ex.: imersão em água morna, mobilidade, massagem)',
      detail: 'Durante a dilatação — parte do parto humanizado.',
      sourceId: 'sm-parto-oms-who',
    },
    {
      id: 'oms-posicao-expulsivo',
      label: 'OMS — posição no expulsivo',
      value: 'Posição vertical, lateral ou em quatro apoios — não apenas supina',
      detail: 'Pegadinha: supina como única posição é incorreta.',
      sourceId: 'sm-parto-oms-who',
    },
    {
      id: 'oms-clampeamento-tardio',
      label: 'OMS — clampeamento do cordão',
      value: 'Clampeamento tardio entre um e três minutos após o nascimento, se estável',
      detail: 'Quando não há contraindicação materno-fetal.',
      sourceId: 'sm-parto-oms-who',
    },
    {
      id: 'oms-enema-depilacao-rotina',
      label: 'OMS — enema e depilação',
      value: 'Enema e depilação pubiana não são rotineiros no parto normal',
      detail: 'Procedimentos desnecessários em parto fisiológico — pegadinha comum em prova.',
      sourceId: 'sm-parto-oms-who',
    },
    {
      id: 'oms-ocitocina-hpp',
      label: 'OMS — profilaxia HPP',
      value: 'Ocitocina 10 UI IM após o nascimento para prevenção de hemorragia pós-parto',
      detail: 'Administração profilática em parto vaginal — não confundir com indução do trabalho de parto.',
      sourceId: 'sm-parto-oms-who',
    },
    {
      id: 'oms-puxos-dirigidos',
      label: 'OMS — puxos no expulsivo',
      value: 'Evitar puxos dirigidos prolongados de rotina',
      detail: 'Favorecer puxos espontâneos quando possível.',
      sourceId: 'sm-parto-oms-who',
    },
    // — Rastreio câncer de mama INCA/MS (reforço mulher_mama) —
    {
      id: 'mamografia-faixa-etaria',
      label: 'Mamografia — faixa etária MS/INCA',
      value: 'Mulheres de 50 a 69 anos no rastreamento populacional',
      detail: 'Programa de detecção precoce — baixo risco, assintomáticas.',
      sourceId: 'inca-rastreio-mama',
    },
    {
      id: 'mamografia-periodicidade',
      label: 'Mamografia — periodicidade',
      value: 'Bienal (a cada 2 anos)',
      detail: 'Não é anual universal para todas — pegadinha D em provas VUNESP.',
      sourceId: 'inca-rastreio-mama',
    },
    {
      id: 'mamografia-inicio',
      label: 'Mamografia — início do rastreio',
      value: 'Aos 50 anos — não aos 40 como rotina universal',
      detail: 'Alto risco tem protocolo distinto; prova cobra faixa populacional 50+.',
      sourceId: 'inca-rastreio-mama',
    },
    {
      id: 'mamografia-autoexame',
      label: 'Autoexame das mamas',
      value: 'Conscientização e complementar — não substitui mamografia no rastreamento',
      detail: 'Pegadinha E: autoexame não substitui mamografia populacional.',
      sourceId: 'inca-rastreio-mama',
    },
    {
      id: 'mamografia-assintomaticas',
      label: 'Rastreio — população-alvo',
      value: 'Mulheres assintomáticas na faixa etária do programa',
      detail: 'Sintomáticas seguem investigação diagnóstica, não rastreio populacional.',
      sourceId: 'inca-rastreio-mama',
    },
    {
      id: 'pegadinha-mamografia-40-anos',
      label: 'Pegadinha — início aos 40 anos',
      value: '40 anos não é marco universal de rastreio mamográfico no SUS',
      detail: 'Alternativa A falsa em questões VUNESP/Consulplan.',
      sourceId: 'inca-rastreio-mama',
    },
    {
      id: 'pegadinha-mamografia-anual',
      label: 'Pegadinha — periodicidade anual',
      value: 'Rastreio bienal, não anual universal',
      detail: 'Alternativa D falsa — confundir com seguimento de alto risco.',
      sourceId: 'inca-rastreio-mama',
    },
    // — Valores discretos cobrados em prova (corpus factcheck) —
    {
      id: 'sm-prova-idades-marcos',
      label: 'Idades e marcos — casos de prova',
      value:
        '3 meses · 3meses · 2 meses · 4 meses · 6 meses · 9 meses · 12 meses · 12 semanas · 16 semanas · 24 semanas · 28 semanas · 36 semanas · 40 semanas · 42 dias · 3 dias · 7 dias · 48 horas · 15 min · 10 min · 1 mL · 0,5 mL',
      detail: 'Valores literais do enunciado; cruzar com calendário vacinal ou pré-natal quando aplicável.',
      sourceId: 'sm-prenatal-baixo-risco-ms',
    },
  ],
};
