import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Saúde do adolescente.
 * Fonte: MS — Linha de cuidado e Cadernos de Atenção Básica (adolescência).
 */
export const SAUDE_ADOLESCENTE_MS: GuidelineTable = {
  id: 'saude-adolescente-ms',
  snapshot: 'Adolescente — escuta, sigilo, violência e vacinação',
  issuer: 'Ministério da Saúde',
  title: 'Saúde do Adolescente',
  year: 2021,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/a/adolescente',
  entries: [
    {
      id: 'adolescente-escuta',
      label: 'Consulta de enfermagem',
      value: 'privacidade e escuta qualificada',
      detail: 'Respeitar autonomia progressiva — linguagem acessível.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'gravidez-adolescente',
      label: 'Gravidez na adolescência',
      value: 'aumenta riscos materno-fetais',
      detail: 'Exige acompanhamento pré-natal precoce.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'sigilo-adolescente',
      label: 'Sigilo profissional',
      value: 'protegido com limites legais',
      detail: 'Quebra quando há risco grave — não é absoluto nem inexistente.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'contracepcao-adolescente',
      label: 'Saúde sexual e reprodutiva',
      value: 'orientação sobre contracepção integra o cuidado',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'acolhimento-sem-julgamento',
      label: 'Acolhimento',
      value: 'vínculo sem julgamento',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'pegadinha-sigilo-absoluto',
      label: 'Pegadinha sigilo',
      value: 'não quebrar sigilo sem critério em qualquer tema',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'bullying-violencia-escolar',
      label: 'Bullying e cyberbullying',
      value: 'violência interpessoal — acolher, escutar e notificar rede',
      detail: 'MS: identificar sinais (isolamento, queda escolar, lesões) e articular escola, família e NASF.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'automutilacao-risco',
      label: 'Automutilação (NSSI)',
      value: 'sinal de sofrimento psíquico — avaliar risco e encaminhar',
      detail: 'Não minimizar; investigar ideação suicida associada; acionar CAPS/urgência conforme gravidade.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'hpv-adolescente-pni',
      label: 'Vacina HPV (PNI)',
      value: '9 a 14 anos — 2 doses (0 e 6 meses)',
      detail: 'Meninas e meninos; esquema de 2 doses se iniciado antes dos 15 anos (intervalo mín. 5 meses).',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'ist-testagem-adolescente',
      label: 'IST na adolescência',
      value: 'orientar prevenção combinada e ofertar testagem',
      detail: 'Preservativo, vacina HBV/HPV e rastreio conforme exposição — sigilo respeitado na APS.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'alimentacao-adolescente',
      label: 'Alimentação saudável',
      value: 'evitar dietas restritivas e ultraprocessados',
      detail: 'Guia Alimentar MS: priorizar in natura; atenção a transtornos alimentares e imagem corporal.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'atividade-fisica-adolescente',
      label: 'Atividade física',
      value: '≥60 min/dia de moderada a vigorosa',
      detail: 'OMS/MS: reduz sedentarismo; esporte escolar e lazer como promoção de saúde.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'alcool-drogas-adolescente',
      label: 'Álcool e outras drogas',
      value: 'abstinência na adolescência — prevenção e acolhimento',
      detail: 'Uso precoce aumenta risco de dependência; escuta qualificada sem julgamento.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'pegadinha-hpv-3-doses',
      label: 'Pegadinha HPV',
      value: 'não confundir esquema de 2 doses (<15 anos) com 3 doses (≥15 anos)',
      detail: 'Banca troca idade de corte e intervalo entre doses.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'transtornos-alimentares',
      label: 'Transtornos alimentares',
      value: 'anorexia, bulimia e compulsão — avaliar IMC, purga e distorção corporal',
      detail: 'MS: sinais de alerta (perda rápida de peso, isolamento); encaminhar multiprofissional sem julgamento.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'metodos-contraceptivos',
      label: 'Métodos contraceptivos',
      value: 'barreira, hormonal (COC, injetável, implante), DIU e LAM',
      detail: 'Adolescente tem direito à orientação na APS; preservativo é único que previne IST + gravidez.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'consentimento-adolescente-eca',
      label: 'Consentimento do adolescente (ECA)',
      value: '≥12 anos pode consentir procedimentos de baixa complexidade com orientação',
      detail: 'Art. 14 ECA: autonomia progressiva; sigilo respeitado salvo risco grave ou incapacidade.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'gravidez-adolescente-complicacoes',
      label: 'Gravidez adolescente — riscos',
      value: 'eclâmpsia, parto prematuro, baixo peso ao nascer e abandono escolar',
      detail: 'Pré-natal precoce na APS; apoio familiar sem estigmatização.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'ideacao-suicida-adolescente',
      label: 'Ideação suicida',
      value: 'perguntar diretamente sobre pensamentos de morte — não induz risco',
      detail: 'CVV 188; encaminhar urgência se plano ou tentativa; notificar rede conforme protocolo local.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'depressao-adolescente',
      label: 'Depressão na adolescência',
      value: 'humor deprimido, anedonia, alteração de sono e rendimento escolar',
      detail: 'Rastreio na consulta de enfermagem; diferenciar luto, uso de substâncias e transtorno bipolar.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'preservativo-dupla-protecao',
      label: 'Dupla proteção',
      value: 'preservativo + outro método contraceptivo',
      detail: 'Previne gravidez e IST simultaneamente — orientação central na saúde sexual do adolescente.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'atividade-fisica-oms-detalhe',
      label: 'Atividade física — OMS',
      value: '≥60 min/dia moderada a vigorosa; fortalecimento muscular ≥3×/semana',
      detail: 'Limitar tempo de tela; atividade regular reduz obesidade, depressão e sedentarismo.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'substancias-prevencao-escola',
      label: 'Uso de substâncias — prevenção',
      value: 'tabaco, álcool, cannabis e outras drogas — início precoce aumenta dependência',
      detail: 'Estratégias na escola e comunidade; acolhimento e encaminhamento ao CAPS-ad.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'violencia-sexual-adolescente',
      label: 'Violência sexual',
      value: 'acolhimento, profilaxia IST/HIV e contracepção de emergência',
      detail: 'Notificação compulsória; preservar vestígios; não exigir boletim de ocorrência para atendimento.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'pegadinha-consentimento-pais',
      label: 'Pegadinha consentimento',
      value: 'nem todo atendimento ao adolescente exige autorização dos pais',
      detail: 'ECA permite autonomia progressiva ≥12 anos; banca confunde com incapacidade civil absoluta.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'puberdade-tardia-meninas',
      label: 'Puberdade tardia — meninas',
      value: 'sem desenvolvimento mamário dos 12 aos 13 anos',
      detail: 'Ausência de broto mamário (Tanner M1) após 12–13 anos sugere atraso puberal — investigar.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'puberdade-tardia-meninos',
      label: 'Puberdade tardia — meninos',
      value: 'sem hipertrofia testicular (< 4 mL) até 13-14 anos',
      detail: 'Volume < 4 mL indica estágio G1 (pré-puberal); hipertrofia ausente até 13–14 anos = investigar.',
      sourceId: 'saude-adolescente-ms',
    },
    {
      id: 'tanner-puberal',
      label: 'Estágios de Tanner',
      value: 'avaliação padronizada de mamas, genitais masculinos e pelos pubianos',
      detail: 'Complementa marcos cronológicos no exame físico do adolescente.',
      sourceId: 'saude-adolescente-ms',
    },
  ],
};
