import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Saúde mental na atenção básica e RAPS.
 * Fonte: MS — Rede de Atenção Psicossocial (RAPS) e cadernos APS.
 */
export const SAUDE_MENTAL_MS: GuidelineTable = {
  id: 'saude-mental-ms',
  snapshot: 'Saúde mental — acolhimento e risco suicida',
  issuer: 'Ministério da Saúde',
  title: 'Saúde mental',
  year: 2021,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-mental',
  entries: [
    {
      id: 'sm-estigma',
      label: 'Estigma',
      value: 'reduz busca por tratamento — combater com linguagem respeitosa',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-acolhimento',
      label: 'Acolhimento',
      value: 'primeira resposta humanizada na APS e na rede',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-ideacao-suicida',
      label: 'Ideação suicida',
      value: 'acolher, avaliar risco e encaminhar conforme protocolo',
      detail: 'Não minimizar o relato — perguntar não induz suicídio.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-avaliacao-risco',
      label: 'Avaliação de risco suicida',
      value: 'investigar plano, meio e intenção',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-restricao',
      label: 'Restrição física',
      value: 'não é primeira linha para ansiedade leve na UBS',
      detail: 'Indicação proporcional à gravidade e contexto legal.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-caps',
      label: 'CAPS',
      value: 'componente da RAPS para casos de maior complexidade',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-rede-apoio',
      label: 'Encaminhamento',
      value: 'CAPS, urgência psiquiátrica ou hospital conforme gravidade',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-linguagem',
      label: 'Comunicação',
      value: 'evitar termos estigmatizantes — pessoa em sofrimento psíquico',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-cvv-188',
      label: 'CVV 188',
      value: 'atendimento 24h — apoio emocional e prevenção do suicídio',
      detail: 'Ligação gratuita e sigilosa; acionar em ideação ou risco iminente.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-transtornos-comuns',
      label: 'Transtornos comuns na APS',
      value: 'depressão, ansiedade e uso prejudicial de álcool/drogas',
      detail: 'Principais motivos de demanda em atenção básica e RAPS.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-medicacao-leve',
      label: 'Casos leves a moderados',
      value: 'psicoterapia e intervenções psicossociais antes de psicofármaco',
      detail: 'Medicação não é primeira linha isolada em quadro leve sem avaliação global.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-caps-ad',
      label: 'CAPS AD',
      value: 'CAPS Álcool e Drogas — componente da RAPS',
      detail: 'Atendimento especializado para dependência química e transtornos associados.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-alcool-uso',
      label: 'Uso de álcool',
      value: 'avaliar padrão de consumo, riscos e comorbidades',
      detail: 'Encaminhar CAPS AD ou rede de urgência conforme gravidade e abstinência.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-abstinencia-alcool',
      label: 'Abstinência alcoólica',
      value: 'delirium tremens e convulsões são emergência médica',
      detail: 'Não manejar abstinência grave apenas na UBS sem suporte.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-crise-aguda',
      label: 'Crise aguda psiquiátrica',
      value: 'acolher, proteger, avaliar risco e acionar urgência se necessário',
      detail: 'Agitação com risco à integridade exige contenção verbal e rede de apoio imediata.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-dependencia-encaminhamento',
      label: 'Dependência química',
      value: 'rede CAPS AD, ambulatórios e internação quando indicado',
      detail: 'Tratamento multiprofissional — não apenas prescrição isolada.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-depressao-sinais',
      label: 'Depressão — sinais',
      value: 'humor deprimido, anedonia, alteração sono/apetite, fadiga, culpa, ideação suicida',
      detail: 'Avaliar duração (≥2 semanas) e impacto funcional; PHQ-9 na APS; encaminhar se moderado/grave.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-ansiedade',
      label: 'Transtorno de ansiedade',
      value: 'preocupação excessiva, tensão, sintomas somáticos, evitação',
      detail: 'TAG, pânico e fobias são comuns na APS; psicoeducação e TCC — benzodiazepínico não é primeira linha crônica.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-bipolar',
      label: 'Transtorno bipolar',
      value: 'episódios de mania/hipomania alternados com depressão',
      detail: 'Suspeitar em depressão com início precoce, ciclos rápidos ou história familiar; encaminhar psiquiatria.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-psicose-encaminhamento',
      label: 'Psicose — encaminhamento',
      value: 'sintomas psicóticos agudos exigem avaliação psiquiátrica urgente',
      detail: 'Alucinações, delírios, desorganização do pensamento — CAPS ou urgência; descartar causas orgânicas.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-uso-substancias',
      label: 'Uso prejudicial de substâncias',
      value: 'álcool, cannabis, cocaína, crack — avaliar padrão, risco e comorbidades',
      detail: 'CAGE/AUDIT na APS; CAPS AD para dependência; abstinência grave é emergência.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-internacao-involuntaria',
      label: 'Internação involuntária (Brasil)',
      value: 'Lei 10.216/2001 — indicação médica + avaliação posterior do MP em até 72h',
      detail: 'Três modalidades: voluntária, involuntária e compulsória; direitos do paciente preservados.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-familia-apoio',
      label: 'Família — apoio',
      value: 'incluir rede de apoio no plano terapêutico singular',
      detail: 'Psicoeducação familiar reduz recaída; cuidador também precisa de acolhimento na RAPS.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-vinculo-terapeutico',
      label: 'Vínculo terapêutico',
      value: 'escuta ativa, continuidade do cuidado e confiança mútua',
      detail: 'Base do acolhimento na APS — relação terapêutica precede prescrição em quadros leves/moderados.',
      sourceId: 'saude-mental-ms',
    },
    {
      id: 'sm-pegadinha-restricao',
      label: 'Pegadinha contenção física',
      value: 'restrição/contensão não é rotina para ansiedade leve na UBS',
      detail: 'Último recurso, proporcional, com registro e revisão — Lei 10.216 e humanização.',
      sourceId: 'saude-mental-ms',
    },
  ],
};
