import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Faixas de referência — adulto e pediátrico.
 * Fontes: protocolos clássicos de enfermagem + Caderneta da Criança (MS) / SBP.
 * URL: https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-crianca/publicacoes/caderneta-de-saude-da-crianca
 */
export const SINAIS_VITAIS_ADULTO: GuidelineTable = {
  id: 'sv-adulto-referencia',
  snapshot: 'Referência MS/SBP — adulto e pediátrico',
  issuer: 'Ministério da Saúde / SBP',
  title: 'Faixas de sinais vitais — repouso',
  year: 2024,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-crianca/publicacoes/caderneta-de-saude-da-crianca',
  entries: [
    {
      id: 'fc-adulto',
      label: 'FC adulto',
      value: '60 a 100 bpm',
      detail: 'Taquicardia >100 bpm; bradicardia <60 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-adulto',
      label: 'FR adulto',
      value: '12 a 20 irpm',
      detail: 'Taquipneia >20 irpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-adulto',
      label: 'PA adulto',
      value: 'Normotenso ~90–140 × 60–90 mmHg',
      detail: 'Valores variam por fonte; hipertensão estágio 1 ≥140 × 90 mmHg (SBC).',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-axilar-adulto',
      label: 'Temperatura axilar adulto',
      value: '36 °C a 37,5 °C',
      detail: 'Febre axilar ≥37,8 °C (critério comum em prova)',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'spo2-adulto',
      label: 'SpO₂ adulto',
      value: '≥95% em ar ambiente',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-rn',
      label: 'FC recém-nascido',
      value: '120 a 160 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-rn',
      label: 'FR recém-nascido',
      value: '30 a 60 irpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-lactente',
      label: 'FC lactente (1–12 meses)',
      value: '100 a 160 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-lactente',
      label: 'FR lactente',
      value: '30 a 53 irpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-pre-escolar',
      label: 'FC pré-escolar (1–5 anos)',
      value: '80 a 140 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-pre-escolar',
      label: 'FR pré-escolar',
      value: '20 a 28 irpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-escolar',
      label: 'FC escolar (6–11 anos)',
      value: '70 a 120 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-escolar',
      label: 'FR escolar',
      value: '18 a 25 irpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-adolescente',
      label: 'FC adolescente (12–17 anos)',
      value: '60 a 100 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-adolescente',
      label: 'FR adolescente',
      value: '12 a 20 irpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-axilar-crianca',
      label: 'Temperatura axilar criança',
      value: '36 °C a 37,5 °C',
      detail: 'Febre ≥37,8 °C axilar',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'spo2-crianca',
      label: 'SpO₂ criança',
      value: '≥95% em ar ambiente',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'apgar-7-10',
      label: 'APGAR normal',
      value: '7 a 10 no 1º e 5º minuto',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'apgar-4-6',
      label: 'APGAR moderado',
      value: '4 a 6 — reanimação moderada',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'apgar-0-3',
      label: 'APGAR grave',
      value: '0 a 3 — reanimação vigorosa',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-gestante',
      label: 'PA na gestação',
      value: 'Aferir em toda consulta; hipertensão ≥140 × 90 mmHg',
      detail: 'Caderno AB 32/MS: vigilância para pré-eclâmpsia; hipotensão ortostática pode ocorrer.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-idoso',
      label: 'PA no idoso',
      value: 'Hipertensão ≥140 × 90 mmHg (SBC); hipotensão ortostática frequente',
      detail: 'Queda ≥20 mmHg da PAS ou ≥10 mmHg da PAD ao levantar — risco de queda.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-crianca-taquipneia',
      label: 'Taquipneia pediátrica (referência)',
      value: 'RN >60 · lactente >50 · pré-escolar >40 · escolar >30 irpm',
      detail: 'Limites superiores por faixa etária — acima disso = taquipneia em repouso.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-retal',
      label: 'Temperatura retal',
      value: '36,5 °C a 37,5 °C — normal',
      detail: 'Febre retal ≥38,0 °C; método mais próximo da temperatura central.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-hiperpirexia',
      label: 'Hiperpirexia',
      value: 'Febre extrema — ≥41 °C em provas clássicas',
      detail: 'Acima de 40 °C já é febre alta; hiperpirexia marca pico térmico extremo.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-esfigmo-inflacao-max',
      label: 'Insuflação máxima — esfigmomanômetro',
      value: 'Não inflar acima de 300 mmHg',
      detail: 'Limite de segurança do manômetro aneroide — evita lesão vascular e dor.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-retal-vs-axilar',
      label: 'Retal × axilar',
      value: 'Axilar costuma ser ~0,5 °C menor que retal',
      detail: 'Registrar via de aferição; não comparar valores de métodos diferentes sem conversão.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'escala-dor-eva',
      label: 'Escala visual analógica (EVA)',
      value: '0 a 10 — 0 sem dor; 1–3 leve; 4–6 moderada; 7–10 intensa',
      detail: 'COFEN/protocolos de enfermagem: reavaliar após analgesia e registrar escore.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'glasgow-componentes',
      label: 'Escala de Coma de Glasgow (ECG)',
      value: 'Abertura ocular (1–4) + resposta verbal (1–5) + resposta motora (1–6)',
      detail: 'Escore total 3 a 15; registrar melhor resposta; T no verbal se intubado.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'glasgow-classificacao',
      label: 'ECG — classificação',
      value: 'Leve 13–15 · moderado 9–12 · grave ≤8',
      detail: 'Glasgow ≤8: considerar via aérea definitiva; reavaliar seriado no trauma e AVC.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-glasgow-min',
      label: 'Pegadinha Glasgow',
      value: 'escore mínimo é 3, não zero',
      detail: 'Soma dos três componentes; morte cerebral não se expressa como Glasgow 0.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-manguito-80-circunferencia',
      label: 'Tamanho do manguito (PA)',
      value: 'Comprimento do manguito ≈ 80% da circunferência do braço',
      detail: 'Largura da bolsa ≈ 40% da circunferência; manguito inadequado distorce a leitura.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-braco-nivel-coracao',
      label: 'Posicionamento do braço (PA)',
      value: 'Braço apoiado ao nível do coração (4º EIC)',
      detail: 'Braço abaixo do coração superestima; acima subestima a PA sistólica.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-repouso-5-minutos',
      label: 'Repouso pré-aferição de PA',
      value: 'Repouso ≥5 minutos sentado, sem falar',
      detail: 'Diretriz SBC: evitar cafeína/tabaco/exercício 30 min antes; bexiga vazia se possível.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-metodo-auscultatoria-padrao',
      label: 'Método auscultatório (PA)',
      value: 'Padrão-ouro — sons de Korotkoff com esfigmomanômetro',
      detail: 'Fase I = PAS; fase V (desaparecimento) = PAD; registrar posição e lado do braço.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-metodo-oscilometrica-automatica',
      label: 'Método oscilométrico (PA)',
      value: 'Aparelho automático — válido para triagem e monitorização',
      detail: 'Não substitui confirmação auscultatória em gestantes, arritmia ou PA limítrofe.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-pam-formula',
      label: 'Pressão arterial média (PAM)',
      value: 'PAM ≈ (2 × PAD + PAS) ÷ 3',
      detail: 'Alvo perfusão ~≥65 mmHg em choque; não confundir PAM com PAD.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-hipotensao-ortostatica',
      label: 'Hipotensão ortostática',
      value: 'Queda ≥20 mmHg na PAS ou ≥10 mmHg na PAD ao ortostatismo',
      detail: 'Aferir deitado 5 min e em pé 1–3 min; comum em idoso, gestante e diuréticos.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-has-estagio-1-sbc',
      label: 'HAS estágio 1 (SBC)',
      value: 'PAS ≥140 mmHg e/ou PAD ≥90 mmHg',
      detail: 'Classificação em repouso, média de ≥2 aferições em dias distintos.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-has-estagio-2-sbc',
      label: 'HAS estágio 2 (SBC)',
      value: 'PAS ≥160 mmHg e/ou PAD ≥100 mmHg',
      detail: 'Risco cardiovascular elevado; reforçar mudança de estilo de vida e farmacoterapia.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-has-estagio-3-sbc',
      label: 'HAS estágio 3 (SBC)',
      value: 'PAS ≥180 mmHg e/ou PAD ≥110 mmHg',
      detail: 'Emergência hipertensiva se com lesão de órgão-alvo aguda; estágio 3 isolado = urgência.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-limite-rn',
      label: 'FC RN — taquicardia/bradicardia',
      value: 'Normal 120–160 bpm · taquicardia >160 · bradicardia <100 bpm',
      detail: 'Bradicardia no RN costuma ser hipóxia ou hipotermia até prova em contrário.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-limite-lactente',
      label: 'FC lactente — taquicardia/bradicardia',
      value: 'Normal 100–160 bpm · taquicardia >160 · bradicardia <100 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-limite-pre-escolar',
      label: 'FC pré-escolar — taquicardia/bradicardia',
      value: 'Normal 80–140 bpm · taquicardia >140 · bradicardia <80 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-limite-escolar',
      label: 'FC escolar — taquicardia/bradicardia',
      value: 'Normal 70–120 bpm · taquicardia >120 · bradicardia <70 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-limite-adolescente',
      label: 'FC adolescente — taquicardia/bradicardia',
      value: 'Normal 60–100 bpm · taquicardia >100 · bradicardia <60 bpm',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-limite-adulto-taq-brad',
      label: 'FC adulto — taquicardia/bradicardia',
      value: 'Normal 60–100 bpm · taquicardia >100 · bradicardia <60 bpm',
      detail: 'Atleta pode ter bradicardia fisiológica; correlacionar com perfusão e sintomas.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-tecnica-1-minuto',
      label: 'Técnica de aferição da FR',
      value: 'Contar movimentos respiratórios por 1 minuto completo',
      detail: 'Não informar o paciente; se 30 s, multiplicar ×2; observar esforço e padrão.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-oral-referencia',
      label: 'Temperatura oral',
      value: '36,1 °C a 37,2 °C — normal',
      detail: 'Não aferir oral após bebidas quentes/frias, respiração bucal ou convulsão recente.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-hipotermia',
      label: 'Hipotermia',
      value: 'Temperatura central <35 °C',
      detail: 'Leve 32–35 °C; moderada 28–32 °C; grave <28 °C; reaquecer controlado e monitorizar SV.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'spo2-tecnica-sem-esmalte',
      label: 'SpO₂ — preparo do sítio',
      value: 'Retirar esmalte/opacos; preferir dedo sem lesão ou edema',
      detail: 'Esmalte escuro e pigmentação podem subestimar a saturação no oxímetro.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'spo2-tecnica-aquecer-extremidade',
      label: 'SpO₂ — extremidade fria',
      value: 'Aquecer mão/dedo ou trocar sítio antes de descartar hipoxemia',
      detail: 'Vasoconstrição por frio ou hipoperfusão gera leitura falsamente baixa.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'enchimento-capilar-normal',
      label: 'Enchimento capilar (TEC)',
      value: '<2 segundos — normal',
      detail: 'Pressionar leito ungueal 5 s; ≥3 s sugere hipoperfusão ou choque.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-materna-parto-dilatacao',
      label: 'FC materna — 1º período (dilatação)',
      value: '1 hora — risco habitual; 2 hora e 4 hora inadequados; alto risco 15–30 min',
      detail: 'MS: aferir e registrar FC materna no 1º período; período expulsivo = intervalos menores.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pa-pediatrica-percentis',
      label: 'PA pediátrica — percentis',
      value: 'PAS avaliada por percentis (idade, sexo e estatura)',
      detail: 'SBP ≥ percentil 95 + 12 mmHg em 3 ocasiões = hipertensão arterial na infância (SBP).',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'gestante-hipotensao-supina',
      label: 'Hipotensão supina na gestação',
      value: 'Após ~20 semanas — compressão da VCI em decúbito dorsal',
      detail: 'Sintomas: náusea, tontura, palidez; posicionar em DLE e aferir PA lateralizada.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fc-idoso-variacao',
      label: 'FC no idoso',
      value: 'Pode diminuir com envelhecimento, betabloqueadores e condicionamento',
      detail: 'Bradicardia assintomática é mais tolerada; atenção a tontura e quedas com FC <50 bpm.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'escala-dor-flacc',
      label: 'Escala FLACC (dor pediátrica)',
      value: 'Face, Legs, Activity, Cry, Consolability — 0 a 10',
      detail: 'Indicada para lactentes e crianças pequenas (≈2 meses a 7 anos) não verbais.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'escala-dor-wong-baker',
      label: 'Escala de faces Wong-Baker',
      value: '0 a 5 faces — 0 sem dor; 5 pior dor imaginável',
      detail: 'Crianças ≥3 anos com linguagem limitada; apontar a face que representa a dor.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'news2-conceito',
      label: 'NEWS2 (conceito)',
      value: 'National Early Warning Score 2 — agrega FC, FR, SpO₂, PA, temperatura e consciência',
      detail: 'Escore de alerta precoce; pontuação elevada exige reavaliação e escalonamento assistencial.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'monitorizacao-sv-uti',
      label: 'Monitorização de SV — UTI',
      value: 'Contínua ou a cada 5–15 min no paciente crítico',
      detail: 'PA invasiva, ECG, SpO₂ e capnografia conforme protocolo; registrar tendência, não só valor isolado.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'monitorizacao-sv-enfermaria',
      label: 'Monitorização de SV — enfermaria',
      value: 'A cada 4–8 h no estável; 1–2 h se risco ou pós-operatório recente',
      detail: 'Intensificar conforme NEWS2, protocolo institucional e prescrição médica.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'registro-sv-prontuario',
      label: 'Registro de SV no prontuário',
      value: 'Valor, horário, método, posição e via de aferição',
      detail: 'COFEN: documentação legal da enfermagem; SV alterado exige conduta e reavaliação registradas.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'dor-aguda-vs-cronica',
      label: 'Dor aguda × crônica',
      value: 'Aguda <3 meses · crônica ≥3 meses (ou ≥6 meses em alguns protocolos)',
      detail: 'Registrar local, intensidade (EVA/faces), fator de melhora/piora e resposta à analgesia.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pressao-de-pulso',
      label: 'Pressão de pulso',
      value: 'PAS − PAD — normal ~30 a 50 mmHg',
      detail: 'Ampliada em insuficiência aórtica e febre; estreita em choque e tamponamento.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-taquipneia-adulto',
      label: 'Taquipneia no adulto',
      value: 'FR >20 irpm em repouso',
      detail: 'Sinal precoce de insuficiência respiratória; correlacionar com SpO₂ e esforço respiratório.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'fr-bradipneia-adulto',
      label: 'Bradipneia no adulto',
      value: 'FR <12 irpm',
      detail: 'Pode indicar depressão respiratória (opioides, SNC); risco de hipoventilação e acidose.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'temp-febre-hiperpirexia',
      label: 'Febre × hiperpirexia',
      value: 'Febre axilar ≥37,8 °C · hiperpirexia ≥40,0 °C',
      detail: 'Hiperpirexia exige medidas físicas e farmacológicas urgentes; investigar foco infeccioso.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'glasgow-pediatrico-modificado',
      label: 'Glasgow pediátrico modificado',
      value: 'Mesmos 3 domínios com respostas ajustadas à idade',
      detail: 'Verbal e motor adaptados em lactentes; escore 3–15; usar tabela pediátrica, não adulto.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-manguito-grande',
      label: 'Pegadinha manguito grande',
      value: 'Manguito largo demais → PA falsamente baixa',
      detail: 'Prova cobra tamanho correto; manguito pequeno eleva artificialmente a leitura.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-manguito-pequeno',
      label: 'Pegadinha manguito pequeno',
      value: 'Manguito estreito demais → PA falsamente alta',
      detail: 'Medir circunferência do braço e escolher manguito antes da aferição.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-fr-15-segundos',
      label: 'Pegadinha contagem da FR',
      value: 'Contar 15 s e multiplicar ×4 superestima se o paciente souber',
      detail: 'Padrão: 1 minuto; se abreviar 30 s ×2, paciente não deve perceber a contagem.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-pam-pad-confusao',
      label: 'Pegadinha PAM × PAD',
      value: 'PAM não é igual à pressão diastólica',
      detail: 'PAM ≈ (2×PAD+PAS)/3; usar PAM errada em choque é erro clássico de prova.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-glasgow-intubado-t',
      label: 'Pegadinha Glasgow intubado',
      value: 'Resposta verbal = T (tube) — não pontua 0',
      detail: 'Intubado: registrar componentes separados; não atribuir verbal 1 por “não fala”.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-spo2-dpoc-alvo',
      label: 'Pegadinha SpO₂ no DPOC',
      value: 'Alvo 88–92% em DPOC retentor crônico — não forçar ≥95%',
      detail: 'Hiperóxia pode suprimir drive respiratório; titular O₂ conforme gasometria basal.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-temp-vias-diferentes',
      label: 'Pegadinha temperatura por via',
      value: 'Não comparar oral, axilar e retal sem registrar a via',
      detail: 'Retal ~0,5 °C acima da axilar; febre depende do método de aferição.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'sv-ordem-afericao-tecnicas',
      label: 'Ordem de aferição dos SV',
      value: 'Temperatura → pulso → respiração → PA (menor interferência)',
      detail: 'PA por último para não alterar FC/FR; repouso antes da PA conforme protocolo.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'pegadinha-pa-perna-vs-braco',
      label: 'Pegadinha PA em membro inferior',
      value: 'PA na coxa/perna pode ser ~10–20 mmHg maior que no braço',
      detail: 'Registrar membro e posição; não usar valores de perna como referência de braço.',
      sourceId: 'sv-adulto-referencia',
    },
    // — Valores discretos cobrados em prova (corpus factcheck) —
    {
      id: 'sv-prova-pas-referencia',
      label: 'PAS — valores discretos em casos de prova',
      value: '90 mmHg · 100 mmHg · 110 mmHg · 120 mmHg · 130 mmHg · 140 mmHg · 160 mmHg · 180 mmHg · 15 mmHg',
      detail: 'Interpretar com PAD associada; normotensão adulto PAS ~90–140 mmHg.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'sv-prova-pad-referencia',
      label: 'PAD — valores discretos em casos de prova',
      value: '60 mmHg · 70 mmHg · 75 mmHg · 80 mmHg · 90 mmHg · 100 mmHg',
      detail: 'Combinações clássicas: 110×75 mmHg, 120×80 mmHg, 140×90 mmHg.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'sv-prova-fc-referencia',
      label: 'FC — valores discretos em casos de prova',
      value: '60 bpm · 65 bpm · 72 bpm · 80 bpm · 90 bpm · 100 bpm · 110 bpm · 120 bpm',
      detail: 'Taquicardia adulto >100 bpm; bradicardia <60 bpm.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'sv-prova-fr-referencia',
      label: 'FR — valores discretos em casos de prova',
      value: '12 irpm · 16 irpm · 18 irpm · 20 irpm · 24 irpm · 30 irpm',
      detail: 'Taquipneia adulto >20 irpm; eupneia 12–20 irpm (varia por fonte).',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'sv-prova-temperatura-referencia',
      label: 'Temperatura — valores discretos em casos de prova',
      value: '26 °C · 28 °C · 32 °C · 35 °C · 35,8 °C · 36 °C · 36,8 °C · 36,5°C · 36,6°C · 36.0°C · 37 °C · 37,2 °C · 37.2°C · 37,3 °C · 37,5 °C · 37,7 °C · 38 °C · 38,5°C · 38.5°C · 39 °C · 40 °C · 41 °C',
      detail: 'Afebril ~36 °C a 37,5 °C axilar; febre axilar ≥37,8 °C.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'sv-prova-diferenca-vias-temp',
      label: 'Diferença axilar × central em prova',
      value: '1°C de diferença · ~0,5 °C a 1 °C entre axilar e retal/central',
      detail: 'Não comparar leituras sem registrar via; axilar ~1°C abaixo da central.',
      sourceId: 'sv-adulto-referencia',
    },
    {
      id: 'sv-prova-spo2-referencia',
      label: 'SpO₂ — valores discretos em prova',
      value: '88% · 90% · 92% · 95% · 98% · 100%',
      detail: 'Hipoxemia <90%; alvo DPOC retentor 88–92%.',
      sourceId: 'sv-adulto-referencia',
    },
  ],
};
