import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Sondagem nasogástrica, vesical e cuidados.
 * Fonte: Anvisa Protocolo 3 — Prevenção de ITU-AC (2025) + técnica COFEN/prática TE.
 * @see https://www.gov.br/anvisa/pt-br/centraisdeconteudo/publicacoes/servicosdesaude/publicacoes/Protocolo3PrevenodeITUFINAL.pdf
 */
export const SONDAS_TECNICA_COFEN: GuidelineTable = {
  id: 'sondas-tecnica-cofen',
  snapshot: 'SNG/SVD + Anvisa Protocolo ITU-AC 2025',
  issuer: 'Anvisa / COFEN',
  title: 'Instalação e manejo de sondas',
  year: 2025,
  url: 'https://www.gov.br/anvisa/pt-br/centraisdeconteudo/publicacoes/servicosdesaude/publicacoes/Protocolo3PrevenodeITUFINAL.pdf',
  entries: [
    {
      id: 'sng-nex',
      label: 'Medida SNG — mnemônico NEX',
      value: 'Nariz → Orelha → Xifoide',
      detail: 'Estimar comprimento antes da inserção.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sng-confirmacao',
      label: 'Confirmação SNG',
      value: 'radiografia é padrão-ouro',
      detail: 'Ausculta isolada não confirma posição com segurança.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-foley-balao',
      label: 'Sonda de Foley',
      value: 'insuflar balão somente após retorno de urina',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-nelaton',
      label: 'Sonda de Nelaton',
      value: 'sem balão — alívio ou coleta única',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-bolsa-nivel',
      label: 'Bolsa coletora SVD',
      value: 'sempre abaixo do nível da bexiga',
      detail: 'Sistema fechado — prevenir refluxo e ITU.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-itu',
      label: 'Complicação mais frequente SVD',
      value: 'ITU associada a cateter (ITU-AC)',
      detail:
        'Anvisa Protocolo 3 (2025): ITU-AC = infecção sintomática com CVD >2 dias consecutivos (D1 = instalação) ou removido no dia anterior.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-bundle-itu-ac-2025',
      label: 'Bundle prevenção ITU-AC (Anvisa 2025)',
      value: 'indicação justa · técnica asséptica · sistema fechado · bolsa abaixo · revisão diária para retirada',
      detail:
        'Protocolo Anvisa/EBSERH 2025 + NT 11/2025. Evitar CVD desnecessário; troca só por indicação/fabricante — não por rotina sem critério.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sonda-lavagem',
      label: 'Manutenção enteral',
      value: 'lavar sonda com água ou SF após dieta/medicação',
      detail: 'Previne obstrução.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sonda-clampar',
      label: 'Manipulação de sonda',
      value: 'clampar antes de desconectar o sistema',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-tecnica-esteril',
      label: 'Sondagem vesical',
      value: 'técnica estéril rigorosa',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sne-alimentacao',
      label: 'SNE — alimentação enteral',
      value: 'dieta por sonda nasoenteral após confirmação de posição',
      detail: 'Cabeceira elevada 30° a 45° durante e 1 h após infusão — reduz risco de aspiração.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sonda-retal-gases',
      label: 'Sonda retal — descompressão',
      value: 'alívio de distensão abdominal e retenção de gases/fezes',
      detail: 'Inserção cerca de 10 a 15 cm; lubrificar ponta; retirar após evacuação ou conforme prescrição.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-troca',
      label: 'Troca de SVD',
      value: 'não é rotina — indicada obstrução, fístula, ITU recorrente ou fechamento de sistema',
      detail: 'Seguir protocolo institucional; troca agendada sem indicação aumenta risco de ITU.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sng-fixacao',
      label: 'Fixação SNG/SNE',
      value: 'fita hipoalergênica alternando narina — nunca na ponta do nariz',
      detail: 'Marcar sonda na narina; verificar posição antes de cada dieta ou medicação.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sonda-complicacoes',
      label: 'Complicações de sondas',
      value: 'aspiração, deslocamento, obstrução, perfuração, ITU (SVD)',
      detail: 'SNG deslocada para traqueia = emergência — interromper dieta e reavaliar posição.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sng-vs-sne',
      label: 'SNG × SNE',
      value: 'SNG termina no estômago; SNE ultrapassa piloro (duodeno/jejuno)',
      detail: 'SNE indicada quando há risco de aspiração ou gastroparesia — confirmação radiográfica obrigatória.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'enteral-velocidade',
      label: 'Infusão enteral',
      value: 'iniciar lentamente e titular conforme tolerância',
      detail: 'Resíduo gástrico elevado, distensão ou vômito — interromper e comunicar equipe.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-higiene-perineal',
      label: 'Higiene perineal SVD',
      value: 'limpeza diária do meato e região perineal',
      detail: 'Manter sistema fechado; não desconectar desnecessariamente — prevenir ITU associada.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sng-indicacao',
      label: 'SNG — indicações',
      value: 'nutrição enteral, medicação oral, descompressão gástrica, lavagem',
      detail: 'Contraindicada em base de crânio fraturada e obstrução esofágica — avaliar antes de inserir.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sne-gavagem-vs-bomba',
      label: 'SNE — gavagem × bomba',
      value: 'gavagem: bolus intermitente; bomba: infusão contínua controlada',
      detail: 'Bomba de infusão reduz distensão e aspiração em pacientes de risco — gavagem para volumes pequenos.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sne-bomba-velocidade',
      label: 'SNE — velocidade bomba',
      value: 'iniciar 20–50 mL/h e titular conforme tolerância e prescrição',
      detail: 'Resíduo gástrico >200–250 mL (protocolo local) — pausar e comunicar equipe.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-balao-volume',
      label: 'SVD Foley — volume do balão',
      value: '10 mL de água destilada (adulto — conforme fabricante)',
      detail: 'Insuflar somente após retorno de urina; volume excessivo pode causar dor e lesão uretral.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-tamanho-adulto',
      label: 'SVD — calibre adulto',
      value: '14 a 18 Fr (mais comum 16 Fr)',
      detail: 'Escolher menor calibre possível que permita drenagem — reduz trauma uretral.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-indicacao',
      label: 'SVD — indicações',
      value: 'retenção urinária, monitorização de débito, cirurgia, feridas perineais',
      detail: 'Usar somente com indicação — cateter vesical de demora aumenta risco de ITU.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'lavagem-vesical-contra',
      label: 'Lavagem vesical — contraindicação',
      value: 'não é procedimento de rotina em SVD sem indicação',
      detail: 'Indicada obstrução por coágulo ou sedimento — lavagem cega aumenta ITU e trauma.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'lavagem-vesical-tecnica',
      label: 'Lavagem vesical — técnica',
      value: 'técnica estéril com SF 0,9% — somente se prescrito',
      detail: 'Não forçar se houver resistência — comunicar equipe.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sng-aspiracao-complicacao',
      label: 'SNG — aspiração pulmonar',
      value: 'complicação grave por deslocamento para traqueia',
      detail: 'Interromper dieta imediatamente; confirmar posição (radiografia) antes de reiniciar.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sng-deslocamento-sinais',
      label: 'SNG — sinais de deslocamento',
      value: 'tosse, dispneia, cianose durante dieta ou aumento súbito de secreção',
      detail: 'Emergência — aspirar se necessário e comunicar médico.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'enteral-cabeceira',
      label: 'Nutrição enteral — posicionamento',
      value: 'cabeceira 30° a 45° durante e 1 h após infusão',
      detail: 'Reduz risco de aspiração — manter em pacientes com SNG/SNE.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'enteral-residuo-gastrico',
      label: 'Resíduo gástrico',
      value: 'avaliar antes de infusão conforme protocolo (ex.: >200 mL = pausar)',
      detail: 'Distensão, náusea ou vômito — interromper e comunicar equipe.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sonda-retal-contraindicacao',
      label: 'Sonda retal — contraindicações',
      value: 'suspeita de abdome agudo, hemorragia digestiva ativa, pós-operatório recente',
      detail: 'Avaliar indicação — uso temporário para descompressão.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sonda-retal-calibre',
      label: 'Sonda retal — calibre',
      value: '22 a 30 Fr conforme idade e indicação',
      detail: 'Lubrificar ponta; inserir 10 a 15 cm; retirar após evacuação ou conforme prescrição.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'fixacao-troca-fita',
      label: 'Fixação — troca de fita',
      value: 'verificar diariamente e trocar se úmida ou solta',
      detail: 'Marcar posição na narina (SNG) — comparar antes de cada manipulação.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-troca-intervalo',
      label: 'SVD — intervalo de troca',
      value: 'não há rotina fixa — trocar apenas com indicação clínica',
      detail: 'Troca agendada sem necessidade aumenta risco de ITU — seguir bundle institucional.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'sng-material',
      label: 'SNG — material',
      value: 'poliuretano ou silicone — calibre 8 a 18 Fr',
      detail: 'Silicone mais flexível para uso prolongado — escolher calibre conforme indicação.',
      sourceId: 'sondas-tecnica-cofen',
    },
    {
      id: 'svd-sistema-fechado',
      label: 'SVD — sistema fechado',
      value: 'manter circuito fechado — não abrir desnecessariamente',
      detail: 'Bolsa abaixo da bexiga; drenagem contínua — prevenir refluxo e ITU.',
      sourceId: 'sondas-tecnica-cofen',
    },
  ],
};
