import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Tuberculose — vigilância e controle.
 * Fonte: Manual de Recomendações para o Controle da Tuberculose no Brasil — 2ª ed.
 * (ainda publicado pelo MS como referência nacional; página atualizada 2024).
 * @see https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/t/tuberculose/publicacoes/manual-de-recomendacoes-para-o-controle-da-tuberculose-no-brasil.pdf
 */
export const TUBERCULOSE_MS: GuidelineTable = {
  id: 'tuberculose-ms',
  snapshot: 'Manual TB MS 2ª ed. (2019; página MS 2024) + TRM-TB',
  issuer: 'Ministério da Saúde',
  title: 'Tuberculose — vigilância epidemiológica',
  year: 2019,
  url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/t/tuberculose/publicacoes/manual-de-recomendacoes-para-o-controle-da-tuberculose-no-brasil.pdf',
  entries: [
    {
      id: 'tb-notificacao',
      label: 'Notificação',
      value: 'compulsória — investigar contactantes',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-baar',
      label: 'BAAR',
      value: 'bacilo álcool-ácido resistente no escarro',
      detail: 'Exame diagnóstico clássico da TB pulmonar.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-transmissao',
      label: 'Transmissão',
      value: 'aerossóis respiratórios — não contato cutâneo',
      detail:
        'Manual MS + Anvisa Protocolo 5: TB pulmonar/laríngea = precaução por aerossóis (não só gotículas).',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-precaucao-bacilifero',
      label: 'TB pulmonar bacilífera',
      value: 'precaução para aerossóis + quarto adequado',
      detail: 'N95/PFF2 + ventilação/pressão negativa conforme protocolo; máscara cirúrgica no paciente no transporte.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-tratamento',
      label: 'Tratamento diretamente observado',
      value: 'TDO — esquema básico conforme manual MS',
      detail: 'Rifampicina, isoniazida, pirazinamida, etambutol na fase intensiva.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-pegadinha-pele',
      label: 'Pegadinha via de transmissão',
      value: 'TB não se transmite por contato direto com pele',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-ppd-mantoux',
      label: 'PPD (teste tuberculínico)',
      value: 'PPD/Mantoux — indicação de infecção latente ou exposição',
      detail: 'Leitura em 48–72 h (induração em mm). Não confirma doença ativa isoladamente — correlacionar com clínica e radiografia.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-dot-tdo',
      label: 'DOT/TDO',
      value: 'Tratamento Diretamente Observado — adesão supervisionada',
      detail: 'Profissional certifica ingestão das doses; reduz abandono e resistência bacteriana.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-meningite',
      label: 'Meningite tuberculosa',
      value: 'Forma grave — notificação compulsória',
      detail: 'Precaução para aerossóis em ambiente hospitalar; início precoce do esquema conforme manual MS.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-incubacao',
      label: 'Período de incubação',
      value: '2 a 12 semanas (média ~4 semanas) até doença ativa',
      detail: 'Infecção latente pode persistir anos sem sintomas — vigilância de contactantes.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-hiv-coinfeccao',
      label: 'TB e HIV',
      value: 'Coinfecção acelera progressão — triagem bidirecional obrigatória',
      detail: 'TB é doença definidora de AIDS; paciente com TB deve testar HIV e vice-versa.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tetano-profilaxia',
      label: 'Tétano — profilaxia pós-exposição',
      value: 'Vacina antitetânica ± soro antitetânico conforme esquema e histórico vacinal',
      detail: 'Feridas contaminadas, mordidas e queimaduras — atualizar calendário vacinal; não confundir com profilaxia de TB.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'candidiase-oportunista',
      label: 'Candidíase',
      value: 'Infecção fúngica oportunista (Candida spp.)',
      detail: 'Oral, vaginal ou cutânea — imunossupressão predispõe. Não é transmissão por gotículas como TB.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-trm-tb',
      label: 'TRM-TB (teste rápido molecular)',
      value: 'método de escolha para casos novos — detecta MTB e resistência à rifampicina',
      detail:
        'MS/Departamento de HIV/Aids/TB: resultado em ~1,5 h; 1 amostra de escarro. Cultura permanece padrão-ouro para sensibilidade ampliada; BAAR ainda usado no acompanhamento.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-iltb-tpt',
      label: 'ILTB / TPT',
      value: 'tratamento da infecção latente (TPT) conforme esquema MS vigente',
      detail:
        'Notas Informativas MS 2024–2025 (ex. NI 25/2025 rifampicina 300 mg): esquemas com isoniazida ou rifampicina — não confundir com tratamento da TB ativa (RHZE).',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-cultura-confirmacao',
      label: 'Cultura para M. tuberculosis',
      value: 'Padrão-ouro para confirmação e teste de sensibilidade',
      detail: 'Complementa BAAR e TRM-TB; resultado demora semanas.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-pegadinha-vacina-bcg',
      label: 'Pegadinha BCG e PPD',
      value: 'BCG pode causar reação cruzada no PPD — interpretar com histórico vacinal',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tetano-esquema-dt-dtpa',
      label: 'Tétano — esquema vacinal (dT/dTpa)',
      value: '3 doses na vida adulta com reforço a cada 10 anos (dT ou dTpa)',
      detail: 'Profilaxia pós-exposição depende do histórico vacinal e tipo de ferida — não confundir com esquema anti-TB.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'candidiase-oral-hiv',
      label: 'Candidíase oral em HIV',
      value: 'monilíase orofaríngea — placa branca removível; infecção oportunista',
      detail: 'Sinal de imunossupressão; tratamento antifúngico — transmissão não é por aerossol como TB.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-meningite-liquor',
      label: 'Meningite TB — liquor',
      value: 'pleocitose linfocítica, proteína elevada, glicose baixa no LCR',
      detail: 'Forma grave — BAAR e cultura no liquor; precaução aerossóis no ambiente hospitalar.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-ppd-cortes-induracao',
      label: 'PPD — interpretação (induração)',
      value: '≥5 mm (HIV/imunossuprimido); ≥10 mm (contactantes/risco); ≥15 mm (sem fator de risco)',
      detail: 'Medir induração transversal em mm — eritema isolado não conta; leitura em 48–72 h.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-mdr-dot',
      label: 'TB multirresistente (MDR) e DOT',
      value: 'resistência a rifampicina e isoniazida — esquema prolongado com TDO obrigatório',
      detail: 'Tratamento supervisionado (DOT/TDO) essencial para adesão e contenção de resistência.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-iltb-ish-reducao',
      label: 'ILTB — isoniazida profilática',
      value: 'reduz em 60 a 90% o risco de adoecimento',
      detail: 'Tratamento da infecção latente com isoniazida conforme manual MS.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-sintomatico-3-semanas',
      label: 'Sintomático respiratório',
      value: 'tosse por 3 semanas ou mais — investigar TB',
      detail: 'Busca ativa na atenção primária.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-tratamento-6-meses',
      label: 'TB sensível — duração',
      value: 'tratamento mínimo 6 meses (não 12 meses)',
      detail: 'Esquema básico rifampicina + isoniazida + pirazinamida + etambutol.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-tdo-frequencia',
      label: 'TDO — frequência',
      value: 'diariamente de segunda a sexta-feira ou 3 vezes na semana',
      detail: 'Local e horário acordados com o paciente.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'hanseniase-pqt-28-dias',
      label: 'Hanseníase — PQT supervisão',
      value: 'consulta de dose supervisionada a cada 28 dias',
      detail: 'Poliquimioterapia com supervisão mensal na UBS.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'hanseniase-pqt-pb-6-meses',
      label: 'Hanseníase PQT paucibacilar',
      value: 'PQT paucibacilar — duração 6 meses',
      detail: 'Esquema único: rifampicina + clofazimina + dapsona.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'hanseniase-pqt-farmacos',
      label: 'Hanseníase — fármacos PQT',
      value: 'rifampicina, clofazimina e dapsona',
      detail: 'Não inclui etambutol no esquema padrão de hanseníase.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-baar-coleta-duas-amostras',
      label: 'Coleta de escarro BAAR',
      value: 'duas amostras — uma supervisionada e outra no dia seguinte',
      detail: 'Refrigerar até processamento; orientação do técnico de enfermagem.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-escarro-volume-coleta',
      label: 'Volume de escarro para diagnóstico',
      value: 'coletar de 5 a 10 ml de escarro',
      detail: 'Volume insuficiente prejudica baciloscopia e cultura na TB pulmonar.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-iltb-pvhiv-cd4',
      label: 'ILTB — investigação em PVHIV',
      value: 'pessoas vivendo com HIV com LT CD4+ menor ou igual a 350 cel/mm³',
      detail: 'Investigação de infecção latente pelo M. tuberculosis conforme manual MS.',
      sourceId: 'tuberculose-ms',
    },
    {
      id: 'tb-diagnostico-triade',
      label: 'Diagnóstico da TB — métodos',
      value: 'exame bacteriológico, radiológico e prova tuberculínica',
      detail: 'Correlacionar com quadro clínico; broncoscopia é complementar.',
      sourceId: 'tuberculose-ms',
    },
  ],
};
