import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Suporte Básico de Vida / RCP — Protocolo SAMU 192 / MS, alinhado AHA/ILCOR 2025.
 * Números-núcleo (30:2, 100–120/min, 5–6 cm) reafirmados em 2025; engasgo e opioides atualizados.
 * Núcleo RCP·DEA·pediatria — ver URGENCIAS_PROTOCOLOS_EMERGENCIA para trauma/triagem/clínica.
 * Fontes: MS SAMU SBV · AHA Guidelines CPR/ECC 2025 (Circulation).
 * @see https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines
 */
export const URGENCIAS_RCP_SBV: GuidelineTable = {
  id: 'urgencias-rcp-sbv-ms',
  snapshot: 'Protocolo SBV/RCP — MS SAMU 192 + AHA/ILCOR 2025',
  issuer: 'Ministério da Saúde',
  title: 'Suporte Básico de Vida e RCP em adulto e pediátrico',
  year: 2025,
  url: 'https://bvsms.saude.gov.br/bvs/publicacoes/protocolo_suporte_basico_vida.pdf',
  entries: [
    {
      id: 'rcp-avaliacao-inicial',
      label: 'Avaliação primária',
      value: 'Segurança da cena → responsividade → acionar 192 → checar respiração',
      detail: 'Sequência ABCDE/XABCDE na avaliação sistemática.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-proporcao-30-2',
      label: 'Proporção compressão:ventilação',
      value: '30 compressões : 2 ventilações',
      detail: 'Com dois socorristas treinados em SBV; evitar hiperventilação.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-frequencia',
      label: 'Frequência das compressões',
      value: '100 a 120 compressões/min',
      detail: 'Manter ritmo regular; minimizar pausas.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-profundidade',
      label: 'Profundidade das compressões (adulto)',
      value: 'Pelo menos 5 cm, sem exceder 6 cm',
      detail: 'Permitir retorno completo do tórax entre compressões.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-pulso-intervalo',
      label: 'Verificação de pulso',
      value: 'A cada 2 minutos',
      detail: 'Não interromper compressões a cada ciclo só para checar pulso — pegadinha de prova.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-dea',
      label: 'DEA',
      value: 'Ligar e aplicar o DEA assim que disponível',
      detail: 'Seguir comandos do aparelho; retomar compressões imediatamente após choque.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-posicao-maos',
      label: 'Posição das mãos',
      value: 'Metade inferior do esterno, entre mamilos',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-oxigenio',
      label: 'Oxigênio durante RCP',
      value: '100% O2 quando disponível no suporte avançado',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'pcr-reconhecimento',
      label: 'PCR — reconhecimento',
      value: 'Inconsciência + ausência de respiração normal',
      detail: 'Gasps agônicos não contam como respiração efetiva.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'hemorragia-controle',
      label: 'Controle de hemorragia externa',
      value: 'Compressão direta; torniquete se sangramento massivo em membro',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'xabcde-sequencia',
      label: 'XABCDE no trauma',
      value: 'X (hemorragia exsanguinante) → A → B → C → D → E',
      detail: 'Controlar sangramento grave antes de via aérea; exposição no final para não perder calor.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'anafilaxia-epinefrina',
      label: 'Anafilaxia — droga de escolha',
      value: 'Epinefrina IM na face ântero-lateral da coxa',
      detail: 'Adulto: 0,3 a 0,5 mg (solução 1:1000). Acionar 192 e posição supina com MMII elevados se hipotensão.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'engasgo-adulto-consciente',
      label: 'Engasgo adulto consciente',
      value: 'Tapas nas costas (interescapulares) primeiro; depois compressões abdominais até expulsão ou inconsciência',
      detail:
        'AHA 2025: iniciar com back blows, depois abdominal thrusts. Gestante/obeso: compressões torácicas. Inconsciente → RCP. Provas antigas podem cobrar só Heimlich — registrar exam_vs_current no golden.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'posicao-lateral-seguranca',
      label: 'Posição lateral de segurança (PLS)',
      value: 'Vítima inconsciente com respiração espontânea e pulso',
      detail: 'Manter via aérea pérvia e prevenir aspiração até chegada do SAMU.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'choque-hipovolemico-sinais',
      label: 'Choque hipovolêmico — sinais',
      value: 'Taquicardia, hipotensão, pele fria e úmida, tempo de enchimento capilar prolongado',
      detail: 'Tratar causa (hemorragia, desidratação); elevar MMII se sem trauma; não atrasar transporte.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'avc-fast',
      label: 'AVC — mnemônico FAST',
      value: 'Face (assimetria) · Arms (fraqueza) · Speech (fala alterada) · Time (acionar 192 imediatamente)',
      detail: 'Tempo é cérebro — suspeita de AVC isquêmico ou hemorrágico exige atendimento urgente.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'samu-192',
      label: 'SAMU — acionamento',
      value: 'Telefone 192 — Serviço de Atendimento Móvel de Urgência',
      detail: 'Informar local, natureza da emergência e estado da vítima; seguir orientações do regulador.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-pediatrica-15-2',
      label: 'RCP pediátrica — proporção',
      value: '15 compressões : 2 ventilações (dois socorristas treinados)',
      detail: 'Com um socorrista: 30:2. Lactente: compressões com dois dedos ou dois polegares.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'torniquete-tempo-max',
      label: 'Torniquete — tempo máximo',
      value: 'Não exceder 2 horas sem reavaliação médica',
      detail: 'Aplicar 5 a 7 cm acima da ferida; registrar horário de colocação. Indicado em hemorragia arterial massiva.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-socorrista-unico-compressoes',
      label: 'RCP com um socorrista',
      value: 'Compressões torácicas contínuas 100–120/min; ventilar a cada 30 compressões',
      detail: 'Priorizar compressões de alta qualidade; minimizar pausas. Se não treinado em ventilação, fazer apenas compressões.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-ped-profundidade-terco',
      label: 'RCP pediátrica — profundidade',
      value: 'Cerca de 1/3 do diâmetro anteroposterior do tórax',
      detail: 'Lactente: ~4 cm; criança: ~5 cm. Permitir retorno completo do tórax entre compressões.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-lactente-tecnica-maos',
      label: 'RCP em lactente — técnica das mãos',
      value: 'Dois dedos no esterno ou dois polegares circundando o tórax',
      detail: 'Dois polegares exigem segundo socorrista; um socorrista usa técnica dos dois dedos no terço inferior do esterno.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'dea-pediatrico-atenuador',
      label: 'DEA em criança',
      value: 'Usar pás pediátricas ou atenuador de energia quando disponível',
      detail: 'Se só houver pás de adulto, usar conforme orientação do aparelho; não atrasar o choque por falta de atenuador.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'engasgo-lactente-5-5',
      label: 'Engasgo em lactente consciente',
      value: '5 golpes nas costas + 5 compressões torácicas, alternando',
      detail: 'Posicionar em decúbito ventral no antebraço; golpes entre escápulas. Em inconsciência, iniciar RCP pediátrica.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'sepse-reconhecimento',
      label: 'Sepse — reconhecimento precoce',
      value: 'Infecção suspeita + alteração mental, taquicardia, taquipneia ou hipotensão',
      detail: 'Acionar 192; oxigenoterapia; acesso venoso se possível. Tempo é tecido — não atrasar transporte.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'iam-sinais-clinicos',
      label: 'IAM — sinais clínicos',
      value: 'Dor torácica opressiva, irradiação para braço/mandíbula, sudorese, náusea, dispneia',
      detail: 'Pode ocorrer sem dor típica (idosos, diabéticos). Posição confortável; acionar 192 imediatamente.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'hipoglicemia-15g-glicose',
      label: 'Hipoglicemia consciente',
      value: '15 g de glicose oral (ex.: 3 sachês de 5 g ou 150 mL de suco)',
      detail: 'Reavaliar em 15 min; repetir se persistir. Se inconsciente, não administrar via oral — posição lateral e 192.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'convulsao-nao-segurar-lingua',
      label: 'Convulsão — conduta',
      value: 'Proteger a cabeça; afastar objetos; NÃO introduzir objetos na boca nem segurar a língua',
      detail: 'Cronometrar duração; após cessar, posição lateral de segurança. Convulsão >5 min ou recorrente: acionar 192.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'afogamento-prioridade-ventilacao',
      label: 'Afogamento — prioridade',
      value: 'Retirar da água com segurança e iniciar ventilação imediatamente',
      detail: 'Não perder tempo drenando água (posição de Trendelenburg invertida). Hipóxia é a causa principal de óbito.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'queimadura-resfriar-20min',
      label: 'Queimadura térmica — primeiro socorro',
      value: 'Resfriar com água corrente fria por pelo menos 20 minutos',
      detail: 'Não aplicar gelo, manteiga ou pasta de dente. Retirar anéis e roupas não aderidas; cobrir com gaze limpa.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'fratura-imobilizacao',
      label: 'Fratura suspeita',
      value: 'Imobilizar na posição encontrada; não tentar reposicionar',
      detail: 'Imobilizar articulação acima e abaixo; tratar choque e hemorragia associados. Transporte urgente se exposta.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'tce-capacete-manter',
      label: 'TCE com capacete instável',
      value: 'Manter o capacete se a via aérea estiver pérvia e o paciente estável',
      detail: 'Remover apenas se necessário para desobstruir via aérea ou realizar RCP; dois socorristas, evitando movimento cervical.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'overdose-opioides-naloxona',
      label: 'Overdose de opioides',
      value: 'Naloxona (antídoto) + suporte ventilatório; acionar 192',
      detail:
        'AHA 2025: naloxona entra no algoritmo BLS em suspeita de overdose (parada respiratória/cardíaca). Sinais: depressão respiratória, pupilas puntiformes. Efeito pode ser mais curto que o opioide — manter suporte.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'intoxicacao-nao-induzir-vomito',
      label: 'Intoxicação exógena',
      value: 'NÃO induzir vômito; não administrar leite ou óleo',
      detail: 'Identificar substância se possível; posição lateral se rebaixamento de consciência. Carvão ativado só com orientação médica.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'escorpionismo-animais-peconhentos',
      label: 'Animais peçonhentos',
      value: 'Lavar o local; imobilizar membro; transporte urgente ao hospital de referência',
      detail: 'Escorpião, aranha, cobra, jararaca: não cortar, sugar ou torniquete. Registrar horário e descrição do animal.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'manchester-classificacao-cores',
      label: 'Protocolo Manchester — cores',
      value: 'Vermelho (imediato) · Laranja (muito urgente) · Amarelo (urgente) · Verde (pouco urgente) · Azul (não urgente)',
      detail: 'Classificação de risco na triagem de pronto-socorro; define tempo máximo até atendimento médico.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'triagem-vermelho-imediato',
      label: 'Triagem vermelha',
      value: 'Atendimento imediato — risco de morte',
      detail: 'Ex.: PCR, obstrução total de via aérea, choque grave, politrauma crítico. Não aguardar na sala de espera.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'transporte-decubito-lateral',
      label: 'Transporte — decúbito lateral',
      value: 'Posição lateral de segurança para inconsciente com respiração espontânea',
      detail: 'Evitar decúbito dorsal em rebaixamento de consciência — risco de aspiração. Monitorar via aérea durante transporte.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'oxigenio-emergencia-indicacao',
      label: 'Oxigênio em emergência',
      value: 'Administrar O2 suplementar em hipóxia, PCR, trauma grave, IAM, dispneia intensa',
      detail: 'Objetivo: manter SpO2 adequada. Venturi ou máscara conforme gravidade; fluxo ajustado ao dispositivo.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'cateter-o2-fluxo',
      label: 'Cateter nasal de O2',
      value: 'Fluxo habitual: 1 a 6 L/min',
      detail: 'Cada litro adiciona ~4% de FiO2 sobre ar ambiente. Umidificar em fluxos altos; monitorar conforto e SpO2.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'parada-respiratoria-vs-cardiaca',
      label: 'Parada respiratória vs cardíaca',
      value: 'Parada respiratória: pulso presente, sem respiração — ventilar. PCR: sem pulso e sem respiração — RCP completa',
      detail: 'Gasps agônicos não são respiração efetiva. Iniciar compressões se dúvida entre parada respiratória e PCR.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'reanimacao-neonatal-3-1',
      label: 'Reanimação neonatal — proporção',
      value: '3 ventilações : 1 compressão (cerca de 120 eventos/min)',
      detail: 'Aplicável ao recém-nascido que não inicia respiração espontânea. Técnica e equipamento específicos para neonato.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'hipotermia-reaquecimento',
      label: 'Hipotermia',
      value: 'Retirar da fonte de frio; secar; aquecer gradualmente (cobertores, calor passivo)',
      detail: 'Hipotermia grave: manobras suaves (risco de fibrilação). Não esfregar extremidades; monitorar ritmo cardíaco.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'insolacao-conduta',
      label: 'Insolação / hipertermia',
      value: 'Ambiente fresco, remover excesso de roupa, resfriar com água/ventilação, hidratar se consciente',
      detail: 'Insolação: pele quente e seca, alteração mental. Choque térmico exige resfriamento ativo e transporte urgente.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'sincope-conduta',
      label: 'Síncope',
      value: 'Deitar com MMII elevados; afrouxar roupas; avaliar pulso e respiração',
      detail: 'Se recuperação rápida, investigar causa. Síncope prolongada, dor torácica ou trauma na queda: acionar 192.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'dor-toracica-acionar-192',
      label: 'Dor torácica aguda',
      value: 'Acionar 192 imediatamente; posição confortável (geralmente semi-Fowler)',
      detail: 'Não administrar AAS sem orientação médica em prova de técnico, salvo protocolo local. Monitorar até SAMU.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'trauma-cervical-estabilizacao-manual',
      label: 'Trauma cervical — imobilização',
      value: 'Estabilização manual em linha neutra até colar cervical',
      detail: 'Manter cabeça, pescoço e tronco alinhados; evitar hiperextensão, flexão ou rotação. Suspeitar lesão se trauma de cabeça.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'pneumotorax-tensionamento-sinais',
      label: 'Pneumotórax hipertensivo',
      value: 'Dispneia súbita, hipotensão, tórax hipertimpânico, desvio traqueal (tardio)',
      detail: 'Emergência que mata — descompressão needle no pré-hospitalar (médico). Oxigênio e transporte imediato.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'edema-agudo-pulmao-ortopneia',
      label: 'Edema agudo de pulmão',
      value: 'Dispneia intensa, ortopneia, estertores, expectoração espumosa rósea',
      detail: 'Posição sentada com pernas pendentes; oxigênio; acionar 192. Causas: ICC descompensada, IAM.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'cetoacidose-halito-cetonico',
      label: 'Cetoacidose diabética',
      value: 'Hálito cetônico (odor de acetona), poliúria, polidipsia, taquipneia (respiração de Kussmaul)',
      detail: 'Hiperglicemia grave com acidose; risco de coma. Hidratação e insulina são hospitalares — transporte urgente.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'pegadinha-rcp-superficie-macia',
      label: 'Pegadinha RCP — superfície',
      value: 'Compressões em superfície firme e rígida (chão)',
      detail: 'Cama macia ou colchão reduz eficácia das compressões — transferir para o chão se possível sem atrasar início.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'pegadinha-rcp-retorno-toracico',
      label: 'Pegadinha RCP — retorno torácico',
      value: 'Permitir retorno completo do tórax entre compressões',
      detail: 'Não apoiar peso entre compressões; retorno incompleto reduz débito cardíaco. Prova cobra como erro frequente.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'pegadinha-rcp-hiperventilacao',
      label: 'Pegadinha RCP — ventilação',
      value: 'Evitar hiperventilação (máx. 10 ventilações/min em PCR)',
      detail: 'Ventilar demais aumenta pressão intratorácica e reduz retorno venoso — piora prognóstico da RCP.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'pegadinha-rcp-parar-antes-samu',
      label: 'Pegadinha RCP — interrupção',
      value: 'Não interromper RCP até chegada da equipe ou sinais de vida claros',
      detail: 'Trocar socorrista a cada 2 min para fadiga; minimizar pausas. Parar ao ver movimento espontâneo ou respiração normal.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'pegadinha-rcp-ordem-dea',
      label: 'Pegadinha RCP — ordem DEA',
      value: 'Ligar DEA o quanto antes, mas retomar compressões imediatamente após análise/choque',
      detail: 'Pausa >10 s para choque piora sobrevida. Seguir voz do aparelho; um socorrista comprime enquanto outro opera DEA.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    // — Valores discretos cobrados em prova (corpus factcheck) —
    {
      id: 'rcp-frequencia-bpm-prova',
      label: 'Frequência RCP em bpm (prova)',
      value: '100 bpm · 120 bpm — meta 100 a 120 compressões/min no adulto',
      detail: 'Bancas citam compressões/min ou bpm indistintamente no SBV adulto.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-pediatrico-15-2',
      label: 'RCP pediátrico — proporção 1 socorrista',
      value: '15 compressões : 2 ventilações',
      detail: 'Criança/lactente: 15:2 com um socorrista; 30:2 com dois socorristas treinados.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-tempo-avaliacao-respiracao',
      label: 'Tempo máximo — checagem de respiração',
      value: 'Avaliar respiração por até 10 s antes de iniciar compressões',
      detail: 'Gasps agônicos não contam como respiração efetiva.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'rcp-fc-alvo-compressoes',
      label: 'Ritmo de compressões — valores de referência',
      value: 'Manter 100 bpm a 120 bpm durante as compressões torácicas',
      detail: 'Metrônomo ou contagem em voz alta ajuda a manter cadência; minimizar pausas.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'urgencias-fc-caso-prova',
      label: 'FC em cenários de urgência (prova)',
      value: '60 bpm · 100 bpm · 120 bpm · 140 bpm',
      detail: 'Taquicardia em choque/anafilaxia; bradicardia sintomática exige suporte e transporte.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'urgencias-pa-caso-prova',
      label: 'PA em cenários de urgência (prova)',
      value: '90 mmHg · 100 mmHg · 120 mmHg · 140 mmHg',
      detail: 'Hipotensão em choque; hipertensão em emergência hipertensiva — acionar 192 e protocolo.',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
    {
      id: 'urgencias-troca-socorrista',
      label: 'Troca de socorrista na RCP',
      value: 'Trocar a cada 2 minutos para evitar fadiga',
      detail: 'Compressões de qualidade caem com fadiga; minimizar pausa na troca (<10 s).',
      sourceId: 'urgencias-rcp-sbv-ms',
    },
  ],
};
