import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Protocolos clínicos de urgência — SBV/SAMU MS + alinhamento AHA/ILCOR 2020.
 * Complementa URGENCIAS_RCP_SBV (núcleo RCP/DEA) com trauma, triagem, anafilaxia e pegadinhas de prova.
 * Fonte: https://bvsms.saude.gov.br/bvs/publicacoes/protocolo_suporte_basico_vida.pdf
 */
export const URGENCIAS_PROTOCOLOS_EMERGENCIA: GuidelineTable = {
  id: 'urgencias-protocolos-emergencia-ms',
  snapshot: 'Protocolos emergência — MS SAMU 192 / AHA 2020',
  issuer: 'Ministério da Saúde',
  title: 'Urgências e emergências — trauma, triagem e condutas específicas',
  year: 2020,
  url: 'https://bvsms.saude.gov.br/bvs/publicacoes/protocolo_suporte_basico_vida.pdf',
  entries: [
    {
      id: 'avc-cincinnati-tres-itens',
      label: 'Escala de Cincinnati (pré-hospitalar)',
      value: 'Face (sorriso/assimetria) · Arms (elevar MMSS — queda) · Speech (repetir frase)',
      detail: 'Não confundir com Glasgow, SSVV isolados ou tríade meníngea. Acionar 192 imediatamente.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'avc-fast-vs-cincinnati',
      label: 'FAST × Cincinnati',
      value: 'FAST inclui Time (tempo); Cincinnati = três itens clínicos sem escala numérica',
      detail: 'Pegadinha: banca mistura Cincinnati com Glasgow ou escala de coma.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'iam-dor-toracica-diferencial-avc',
      label: 'IAM × AVC — diferencial rápido',
      value: 'IAM: dor torácica opressiva, sudorese, irradiação. AVC: déficit neurológico focal súbito',
      detail: 'Ambos exigem 192; não atrasar transporte para “diagnóstico” no local.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'xabcde-x-hemorragia-primeiro',
      label: 'XABCDE — prioridade X',
      value: 'Controlar hemorragia exsanguinante antes de via aérea em politrauma',
      detail: 'Compressão direta, torniquete em membro se sangramento massivo não controlável.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'bt16-sindrome-esmagamento',
      label: 'BT16 — síndrome do esmagamento',
      value: 'Compressão por grande massa muscular (soterramento, esmagamento prolongado)',
      detail: 'Risco de rabdomiólise e hipercalemia; hidratação e transporte urgente — protocolo hospitalar.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'trauma-imobilizacao-colar',
      label: 'Imobilização cervical',
      value: 'Estabilização manual em linha neutra + colar; prancha longa conforme protocolo',
      detail: 'Capacete: manter se via aérea pérvia; remover só com técnica a dois se necessário para RCP.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'trauma-nao-reposicionar-fratura',
      label: 'Fratura exposta — imobilizar',
      value: 'Imobilizar na posição encontrada; não forçar reposicionamento',
      detail: 'EXCETO/INCORRETA: distrator “alinhamento forçado” é conduta errada, não exceção.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'torniquete-indicacao-membro',
      label: 'Torniquete — indicação',
      value: 'Hemorragia arterial massiva em membro quando compressão direta falha',
      detail: 'Não usar em pescoço ou tronco; registrar horário; máximo 2 h sem reavaliação médica.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'queimadura-quimica-lavagem',
      label: 'Queimadura química',
      value: 'Lavagem abundante com água corrente; remover roupa contaminada não aderida',
      detail: 'Não neutralizar com ácido/base caseiro; não pasta de dente, manteiga ou gelo.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'queimadura-caseiro-proibido',
      label: 'Queimadura — proibidos no 1º socorro',
      value: 'Gelo · manteiga · pasta de dente · óleo · café em ferida',
      detail: 'Pegadinha clássica em V/F de primeiros socorros.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'queimadura-resfriar-agua-corrente',
      label: 'Queimadura térmica — resfriamento',
      value: 'Água corrente fria por tempo prolongado (referência MS: pelo menos 20 minutos)',
      detail: 'Em slides handcraft preferir “água corrente abundante” se factcheck do lote for sensível ao literal.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'anafilaxia-im-coxa-imediata',
      label: 'Anafilaxia — via IM',
      value: 'Epinefrina IM imediata na face ântero-lateral da coxa',
      detail: 'Criança e adulto: não postergar para anti-histamínico ou corticoide.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'anafilaxia-iv-excecao',
      label: 'Anafilaxia — epinefrina IV',
      value: 'Reservada a PCR ou hipotensão profunda refratária a IM repetida e volume',
      detail: 'Asserção CPCON: II justifica I — IV não é primeira escolha na anafilaxia aguda.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'anafilaxia-sinais-reconhecimento',
      label: 'Anafilaxia — reconhecimento',
      value: 'Urticária/angioedema + comprometimento respiratório ou hipotensão após exposição',
      detail: 'Medicamentos, alimentos, venenos — acionar 192; O₂; decúbito com MMII elevados se choque.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'engasgo-sinal-universal',
      label: 'Engasgo — sinal universal',
      value: 'Mãos ao pescoço, incapacidade de falar/tossir efetivamente',
      detail: 'Pedir ajuda imediata; consciente → manobra de desobstrução; inconsciente → RCP.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'engasgo-heimlich-adulto',
      label: 'Heimlich — adulto consciente',
      value: 'Compressões abdominais subdiafragmáticas até expulsão do corpo estranho',
      detail: 'Gestante ou obeso: compressões torácicas; lactente: 5+5 costas/tórax.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'engasgo-inconsciente-rcp',
      label: 'Engasgo — inconsciente',
      value: 'Iniciar RCP; verificar boca antes de ventilar',
      detail: 'Não fazer Heimlich em inconsciente; priorizar compressões e desobstrução visível.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'choque-eletrico-seguranca-cena',
      label: 'Choque elétrico — 1ª conduta',
      value: 'Garantir segurança: desenergizar fonte antes de tocar a vítima',
      detail: 'Arritmias e queimaduras internas podem existir sem lesão externa evidente.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'choque-hipovolemico-tipos',
      label: 'Choque hipovolêmico — causas',
      value: 'Perda de sangue, plasma ou fluido (diarreia, vômito, queimadura extensa)',
      detail: 'Diferente de cardiogênico (bomba) e distributivo (vasoplegia/anafilaxia/séptico).',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'choque-cardiogenico-sinais',
      label: 'Choque cardiogênico',
      value: 'Hipotensão + sinais de baixo débito após IAM ou falência cardíaca',
      detail: 'Pegadinha: confundir com hipovolêmico puro em prova de classificação.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'choque-distributivo-anafilaxia',
      label: 'Choque distributivo — anafilaxia',
      value: 'Vasodilatação súbita + broncoespasmo; tratar com epinefrina IM',
      detail: 'Volume e O₂ são adjuvantes; epinefrina é droga que salva.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'manchester-vermelho-emergencia',
      label: 'Manchester — vermelho',
      value: 'Emergência imediata — risco de morte',
      detail: 'PCR, obstrução total VA, choque grave, politrauma instável — não aguardar na sala.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'manchester-azul-nao-urgente',
      label: 'Manchester — azul',
      value: 'Não urgente — atendimento eletivo/ambulatorial',
      detail: 'Pegadinha: azul NÃO é instabilidade máxima — vermelho é emergência.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'manchester-cores-sequencia',
      label: 'Manchester — cores (referência)',
      value: 'Vermelho · Laranja · Amarelo · Verde · Azul',
      detail: 'Tempos-alvo decrescem com gravidade; triagem na chegada ao PS.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'convulsao-proteger-cabeca',
      label: 'Convulsão — crise aguda',
      value: 'Proteger cabeça; afastar objetos; cronometrar; NÃO introduzir objetos na boca',
      detail: 'Não imobilizar forçadamente; após cessar → PLS. Crise prolongada: acionar 192.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'convulsao-nao-pano-boca',
      label: 'Convulsão — pegadinha boca',
      value: 'Não colocar pano, dedo ou objeto entre os dentes',
      detail: 'Risco de aspiração e trauma dental; lateralizar após tônico-clônico.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pcr-pediatrica-epidemiologia',
      label: 'PCR pediátrica — causas',
      value: 'Hipóxia e choque são causas predominantes (não IAM como no adulto)',
      detail: 'RCP precoce; 15:2 com um socorrista; profundidade ~⅓ diâmetro AP.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'rcp-ped-dois-socorristas-30-2',
      label: 'RCP pediátrica — dois socorristas',
      value: '30 compressões : 2 ventilações',
      detail: 'Com um socorrista: 15:2. Pegadinha: aplicar 15:2 no adulto.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'vf-protocolo-julgar-itens',
      label: 'V/F combinatório — método',
      value: 'Julgar cada item (V/F) antes de cruzar com alternativa A–D',
      detail: 'I–IV ou quatro linhas: sequência correta de cima para baixo.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'primeiros-socorros-heimlich-v',
      label: 'Primeiros socorros — Heimlich',
      value: 'Adulto consciente com OVACE: manobra abdominal (Heimlich) até desobstruir',
      detail: 'Item V em provas de primeiros socorros mistos (RCP + queimadura + hemorragia).',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'hemorragia-compressao-nao-caseiro',
      label: 'Hemorragia externa',
      value: 'Compressão direta com gaze/tecido limpo; elevar membro se possível',
      detail: 'Não café, pó ou substância caseira — pegadinha em V/F.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'exceto-conduta-distrator-correto',
      label: 'EXCETO/INCORRETA — regra de prova',
      value: 'Cada alternativa errada descreve conduta correta; só gabarito aponta a exceção',
      detail: 'danger_zone: cada correct explica a letra — nunca repetir mesma frase.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'seguranca-cena-primeiro',
      label: 'Segurança da cena',
      value: 'Avaliar risco para socorrista, vítima e terceiros antes da abordagem',
      detail: 'Choque elétrico, trânsito, violência — não tornar-se segunda vítima.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-rcp-80-100-bpm',
      label: 'Pegadinha RCP — frequência antiga',
      value: 'Meta atual: 100 a 120 compressões/min (não 80–100 nem “pelo menos 80”)',
      detail: 'Diretriz AHA 2015/2020 adotada pelo MS; bancas antigas ainda citam 80–100.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-rcp-4cm-profundidade',
      label: 'Pegadinha RCP — profundidade antiga',
      value: 'Adulto: pelo menos 5 cm, até 6 cm (não “4 cm” isolado como ideal)',
      detail: 'Prova pode oferecer 4 cm como distrator pós-2010.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-rcp-15-2-adulto',
      label: 'Pegadinha RCP — proporção adulto',
      value: 'Adulto: 30:2 (15:2 é pediátrico com um socorrista)',
      detail: 'V/F que mistura protocolo pediátrico no adulto.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-rcp-pulso-cada-ciclo',
      label: 'Pegadinha RCP — pulso',
      value: 'Checar pulso a cada ~2 min, não a cada ciclo 30:2',
      detail: 'Interromper compressões só no intervalo programado ou sinais de vida.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-dea-antes-compressoes',
      label: 'Pegadinha DEA — ordem',
      value: 'Iniciar compressões imediatamente; buscar DEA sem atrasar RCP',
      detail: 'Ligar DEA assim que disponível; retomar compressões após análise.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-glasgow-avc',
      label: 'Pegadinha AVC — escala errada',
      value: 'Cincinnati/FAST na suspeita pré-hospitalar — não substituir por Glasgow',
      detail: 'Glasgow é neurológico hospitalar; não é triagem FAST de rua.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-triagem-azul-critico',
      label: 'Pegadinha triagem — cor azul',
      value: 'Azul = não urgente; vermelho = emergência imediata',
      detail: 'Inversão azul×instabilidade é distrator frequente.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-anafilaxia-antihistaminico-primeiro',
      label: 'Pegadinha anafilaxia — ordem drogas',
      value: 'Epinefrina IM primeiro — anti-H1 e corticoide são adjuvantes',
      detail: 'Atrasar adrenalina aumenta mortalidade.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-queimadura-gelo',
      label: 'Pegadinha queimadura — gelo',
      value: 'Água corrente sim; gelo direto na pele não',
      detail: 'Gelo pode agravar lesão térmica; resfriamento gradual com água.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-engasgo-beber-agua',
      label: 'Pegadinha engasgo — água',
      value: 'Não oferecer líquidos em OVACE total; manobra de desobstrução',
      detail: 'Tosse efetiva: encorajar; se falha → Heimlich.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-choque-eletrico-agua',
      label: 'Pegadinha choque elétrico — água na vítima',
      value: 'Desenergizar antes do contato; água na cena pode conduzir corrente',
      detail: 'Segurança elétrica precede RCP.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'pegadinha-trauma-mover-rapido',
      label: 'Pegadinha trauma — movimentar',
      value: 'Não mover vítima de trauma sem necessidade; imobilizar coluna suspeita',
      detail: 'Exceção: perigo iminente (incêndio, explosão) — arrastar protegendo cabeça.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'samu-informacoes-regulador',
      label: 'SAMU 192 — informações ao regulador',
      value: 'Local exato · natureza da emergência · número de vítimas · estado da vítima',
      detail: 'Manter linha; seguir orientações até chegada da equipe.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'plano-conceito-pcr-lactente',
      label: 'Lactente — avaliação responsividade',
      value: 'Estimular plantas dos pés e ombros; não sacudir',
      detail: 'Técnica de desobstrução e RCP específicas para <1 ano.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'overdose-paracetamol-nao-induzir',
      label: 'Intoxicação — conduta geral',
      value: 'Não induzir vômito; identificar substância; 192 se rebaixamento',
      detail: 'Carvão ativado só com orientação médica e via aérea protegida.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'asma-crise-broncodilatador',
      label: 'Asma — crise aguda grave',
      value: 'Oxigênio + broncodilatador inalatório; acionar 192 se falha ou fadiga respiratória',
      detail: 'Técnico: suporte e monitorização até equipe avançada.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
    {
      id: 'crise-hipertensiva-nao-oral-rotina',
      label: 'Emergência hipertensiva',
      value: 'PA muito elevada + lesão de órgão-alvo — transporte urgente',
      detail: 'Em prova de técnico: não prescrever anti-hipertensivo oral de rotina sem protocolo.',
      sourceId: 'urgencias-protocolos-emergencia-ms',
    },
  ],
};
