import type { GuidelineTable } from '@/lib/guidelines/types';

/**
 * Vias de administração — absorção, sítios e técnica.
 * Conteúdo técnico estável (Potter & Perry / prática de TE); revisão 2026 sem mudança de números-chave.
 * Competência de prescrição do enfermeiro: Res. COFEN 801/2026 (não altera técnica de via do TE).
 */
export const VIAS_ADMINISTRACAO_COFEN: GuidelineTable = {
  id: 'vias-administracao-cofen',
  snapshot: 'Vias IM, SC, EV — absorção e técnica (revisão 2026)',
  issuer: 'COFEN / referência técnica',
  title: 'Vias de administração de medicamentos',
  year: 2026,
  url: 'https://www.cofen.gov.br/resolucao-cofen-no-801-de-14-de-janeiro-de-2026/',
  entries: [
    {
      id: 'im-absorcao',
      label: 'Via IM — absorção',
      value: 'mais rápida que SC',
      detail: 'Músculo é mais vascularizado que tecido subcutâneo.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'sc-absorcao',
      label: 'Via SC — absorção',
      value: 'mais lenta que IM',
      detail: 'Indicada para medicamentos de absorção gradual (ex.: insulina, heparina).',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'ev-absorcao',
      label: 'Via EV',
      value: 'ação imediata — 100% biodisponível',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'im-ventrogluteo',
      label: 'Sítio IM — ventroglúteo',
      value: 'recomendado e seguro em adultos',
      detail: 'Glúteo médio — afastado do nervo ciático.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'im-deltoide',
      label: 'Sítio IM — deltoide',
      value: 'volume limitado (até 2 mL em adulto)',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'im-glutea-5ml',
      label: 'Sítio IM — glútea/dorsoglútea',
      value: 'até 5 mL',
      detail: 'Glúteo maior/dorsoglútea — volume maior que deltoide em adultos.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'im-ventrogluteo-2ml',
      label: 'Ventroglúteo — volume adulto',
      value: '2 mL',
      detail: 'Solução aquosa 2 mL em adulto; agulha 30×0,6–0,7 mm (referência de prova).',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'im-vastolateral',
      label: 'Sítio IM — vasto lateral',
      value: 'seguro em lactentes e crianças',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'im-tecnica',
      label: 'Técnica IM',
      value: 'palpar músculo, marcos ósseos, posicionar e minimizar dor',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'im-angulo',
      label: 'Ângulo de punção IM',
      value: '90°',
      detail: 'Agulha perpendicular ao músculo.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'sc-angulo',
      label: 'Ângulo de punção SC',
      value: '45° ou 90° conforme tecido adiposo',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'pegadinha-im-sc',
      label: 'Pegadinha absorção',
      value: 'IM não é mais lenta que SC',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'ev-direta-lenta',
      label: 'EV direta lenta',
      value: 'bolus em 3 a 5 minutos (ou conforme bula)',
      detail: 'Administrar lentamente — reduz risco de reação adversa grave (ex.: fenitoína, vancomicina).',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'vo-jejum',
      label: 'VO em jejum',
      value: '30 min antes ou 2 h após refeição',
      detail: 'Garante absorção previsível — alguns fármacos exigem jejum absoluto (levotiroxina).',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'via-retal',
      label: 'Via retal',
      value: 'absorção irregular — bypass parcial da primeira passagem',
      detail: 'Indicada quando VO inviável (vômito, convulsão); supositórios e enemas medicamentosos.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'via-inalatoria',
      label: 'Via inalatória',
      value: 'ação rápida na mucosa pulmonar',
      detail: 'Broncodilatadores (SABA) e corticoides inalatórios — técnica correta do dispositivo é essencial.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'via-topica',
      label: 'Via tópica',
      value: 'ação local no sítio de aplicação',
      detail: 'Pomadas, cremes e colírios — evitar contaminação do frasco; não é sistêmica de rotina.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'intradermica-teste',
      label: 'Intradérmica — teste',
      value: 'bevel para cima, ângulo 10° a 15°, bolsa pápulo visível',
      detail: 'PPD/tuberculina e testes de alergia — volume 0,1 mL; ler reação em 48 a 72 h.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'sublingual-bypass',
      label: 'Via sublingual',
      value: 'absorção pela mucosa oral — evita primeira passagem hepática',
      detail: 'Nitroglicerina SL: não engolir; efeito em 1 a 3 minutos.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'sc-volume-max',
      label: 'Volume máximo SC',
      value: '1,5 mL (máximo indicado AVANÇASP) · faixa 1 a 2 mL por sítio',
      detail: 'Distrator clássico: 3 mL acima do limite; alternativas 0,5 · 1,0 · 2,0 · 2,5 mL em provas.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'sc-volume-distractors',
      label: 'Volumes SC — distratores numéricos',
      value: '0,5 mL · 1,0 mL · 2,0 mL · 2,5 mL',
      detail: 'Alternativas falsas em provas de volume máximo SC.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'sc-volume-distrator-3ml',
      label: 'Distrator SC — 3 mL',
      value: '3 mL',
      detail: 'Acima do limite usual SC — item falso em combinações I–IV.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'iv-infusao-rapida',
      label: 'Infusão IV rápida',
      value: '1 a 30 minutos',
      detail: 'Distinto de bolus (segundos a 1 min) e infusão contínua (horas).',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'iv-bolus',
      label: 'Bolus IV',
      value: 'segundos a 1 min',
      detail: 'Administração em bolus — efeito imediato, fora da janela 1–30 min.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'vo-com-alimento',
      label: 'VO com alimento',
      value: 'alguns fármacos exigem refeição para reduzir irritação gástrica',
      detail: 'AINEs e metformina — outros (tetraciclinas, quinolonas) não devem ser tomados com laticínios.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'noradrenalina-glicose-5',
      label: 'Noradrenalina — diluente EV',
      value: 'glicose 5% (glicosado)',
      detail:
        'Vasopressor fotossensível: diluir em glicose 5%; preferir acesso venoso central — reduz oxidação à luz e risco de necrose por extravasamento.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'noradrenalina-sf09-distrator',
      label: 'Noradrenalina — SF 0,9% (distrator)',
      value: '0,9%',
      detail:
        'SF 0,9% (fisiológico) com acesso periférico é distrator clássico — não é diluente preferido de noradrenalina.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'insulina-sc-abdome-rapido',
      label: 'Insulina SC — absorção (literatura)',
      value: 'abdome mais rápido',
      detail: 'ADA/Potter — abdome absorve mais rápido; nádegas mais lento.',
      sourceId: 'vias-administracao-cofen',
    },
    {
      id: 'insulina-sc-nadegas-prova',
      label: 'Insulina SC — gabarito de prova',
      value: 'nádegas mais rápidas',
      detail: 'Cadastro específico de banca — pode divergir da literatura; ensinar letra da prova.',
      sourceId: 'vias-administracao-cofen',
    },
  ],
};
