#!/usr/bin/env tsx
/** Handcraft golden-v1 — coleta-de-exames-laboratoriais-g07 */
import { mcqPack, runHandcraftLote } from './lib/coleta-handcraft-base';

const LOTE = 'coleta-de-exames-laboratoriais-g07';
const REVIEWER = 'coleta-g07';

const SPECS = {
  'avancasp-enfermagem-coleta-de-exames-laboratoriais-1779563165114-3': mcqPack({
    guideline: 'CLSI — sorologia/bioquímica: tubo com gel separador (soro seco/amarelo) — alta qualidade de soro',
    title: 'Tubos — gel separador sorológico',
    conceptItems: [
      { label: 'Comando', detail: 'Composição/ação para sorologia, marcadores cardíacos e bioquímica (ureia, creatinina).', icon: 'FlaskConical' },
      { label: 'Gel separador (E)', detail: 'Separa soro de alta qualidade após coagulação — padrão bioquímica/sorologia.', icon: 'Layers' },
      { label: 'EDTA', detail: 'Anticoagula sangue total — hemograma, não soro sorológico.', icon: 'Droplet' },
      { label: 'Fluoreto', detail: 'Inibe glicólise — glicose/lactato, não painel sorológico amplo.', icon: 'TestTube' },
      { label: 'Heparina', detail: 'Plasma heparinizado — não é escolha típica de sorologia de rotina.', icon: 'Syringe' },
    ],
    conceptFooter: 'Sorologia/bioquímica rotina → gel separador (soro)',
    steps: [
      'Comando: tubo/ação para sorologia, marcadores cardíacos e bioquímica sérica.',
      'Esses exames usam soro — tubo com ativador + gel separador.',
      'Eliminar A (EDTA), B (fluoreto), C (heparina), D (soro seco sem gel quando E é mais completo).',
      'Marcar E — gel separador para soro de alta qualidade.',
    ],
    logicFooter: 'E = gel separador — soro sorológico/bioquímico',
    goldenTitle: 'Referência — tubo sorológico',
    goldenContent: 'SORO — TUBO COM GEL',
    rows: [
      { label: 'Sorologia/bioquímica', value: 'Ativador + gel separador (amarelo/vermelho)', badge: 'hot' },
      { label: 'Hemograma', value: 'EDTA roxo', badge: 'ok' },
      { label: 'Glicose', value: 'Fluoreto cinza', badge: 'ok' },
    ],
    goldenFooter: 'Gel separador = soro de qualidade',
    dangerTitle: 'PEGADINHAS — SOROLOGIA AVANÇASP',
    dangerItems: [
      { label: 'Letra A — EDTA', detail: 'Inibe coagulação por quelante.', correct: 'Hemograma/tipagem — não sorologia sérica de rotina.' },
      { label: 'Letra B — fluoreto', detail: 'Anti-glicólise.', correct: 'Glicose/lactato — não ureia/creatinina sorológica.' },
      { label: 'Letra C — heparina', detail: 'Plasma.', correct: 'Alguns exames usam plasma — mas E é resposta da banca para painel sorológico.' },
      { label: 'Letra D — soro seco', detail: 'Sem gel separador.', correct: 'Pode servir, mas E (gel separador) é alternativa correta pedida.' },
    ],
    dangerFooter: 'Sorologia = soro com gel',
  }),

  'cpcon-uepb-enfermagem-coleta-de-exames-laboratoriais-1779563225798-4': mcqPack({
    family: 'certo_errado',
    guideline: 'MS — pré-analítico: condições do PACIENTE (hemólise, jejum, exercício, lipemia); tubo/etiqueta é conduta técnica — EXCETO D',
    title: 'Pré-analítico — condições do paciente EXCETO',
    conceptItems: [
      { label: 'Comando EXCETO', detail: 'Condições do paciente para coleta eficaz — uma NÃO é condição do paciente.', icon: 'ClipboardList' },
      { label: 'Hemólise (A)', detail: 'Condição pré-analítica do paciente/amostra — correto.', icon: 'AlertTriangle' },
      { label: 'Atividade física (B)', detail: 'Evitar exercício pré-coleta — condição do paciente.', icon: 'Clock' },
      { label: 'Jejum (C)', detail: '8 h habitual — condição do paciente.', icon: 'Utensils' },
      { label: 'Lipemia (E)', detail: 'Estado metabólico do paciente — condição válida.', icon: 'Droplets' },
      { label: 'EXCETO D — tubos/etiqueta', detail: 'Conduta técnica de tubo soro/plasma — não é “condição do paciente”.', icon: 'Tag' },
    ],
    conceptFooter: 'EXCETO = D (tubo/etiqueta ≠ condição paciente)',
    steps: [
      'Comando: condições do PACIENTE para coleta eficaz — EXCETO.',
      'A hemólise, B exercício, C jejum, E lipemia = condições do paciente/amostra.',
      'D fala de tubo anticoagulante/soro e etiqueta — conduta técnica, não condição do paciente.',
      'Marcar D — EXCETO.',
      'Em similares: EXCETO separa condição do paciente × técnica de coleta.',
    ],
    logicFooter: 'D = EXCETO — tubo/etiqueta',
    goldenTitle: 'Referência — pré-analítico',
    goldenContent: 'CONDIÇÃO PACIENTE × TÉCNICA',
    rows: [
      { label: 'Paciente', value: 'Jejum, exercício, lipemia, hemólise', badge: 'ok' },
      { label: 'Técnica', value: 'Tubo soro/plasma + identificação', badge: 'hot' },
    ],
    goldenFooter: 'EXCETO pega conduta técnica fora do enunciado',
    dangerTitle: 'PEGADINHAS — CPCON EXCETO',
    dangerItems: [
      { label: 'Letra A — hemólise', detail: 'Condição do paciente/amostra.', correct: 'Hemólise significativa altera enzimas — condição válida, não EXCETO.' },
      { label: 'Letra B — exercício', detail: 'Condicionar coleta ao repouso.', correct: 'Atividade física prévia altera analitos — condição do paciente.' },
      { label: 'Letra C — jejum', detail: '8 h / 4 h especial.', correct: 'Jejum reduz turbidez pós-prandial — condição do paciente.' },
      { label: 'Letra D — tubo e etiqueta', detail: 'Conduta correta mas categoria errada.', correct: 'Escolha de tubo soro/plasma é técnica — EXCETO pedido.' },
      { label: 'Letra E — lipemia', detail: 'Interfere métodos.', correct: 'Lipemia do paciente interfere colorimetria — não EXCETO.' },
    ],
    dangerFooter: 'Ler “condições do paciente” no enunciado',
  }),

  'cpcon-uepb-enfermagem-processo-de-enfermagem-1780003868364-3': mcqPack({
    family: 'legis',
    branch: 'coleta_generico',
    guideline: 'CME/Anvisa — materiais críticos: cânula perfusão aramada = crítico (perfurocortante/esterilização)',
    title: 'CME — separar material crítico',
    conceptItems: [
      { label: 'Centro de Material e Esterilização', detail: 'Técnica separa materiais para envio ao CME no plantão.', icon: 'Package' },
      { label: 'Material crítico', detail: 'Cânula para perfusão aramada — invasivo reprocessável.', icon: 'Syringe' },
      { label: 'Tubo coleta sangue', detail: 'Descartável — não classificação crítica CME.', icon: 'TestTube' },
      { label: 'Cateter epidural / sensor PIC', detail: 'Dispositivos específicos — pegadinhas de classificação.', icon: 'Stethoscope' },
      { label: 'Sonda nasogástrica', detail: 'Semicrítico/descartável conforme política.', icon: 'Activity' },
    ],
    conceptFooter: 'Crítico = cânula perfusão aramada (C)',
    steps: [
      'Comando: material para envio ao CME como crítico.',
      'Cânula para perfusão aramada = crítico (invasivo, reprocessável).',
      'Eliminar tubo coleta (descartável), cateter epidural, sensor, sonda NG como gabarito.',
      'Marcar C.',
    ],
    logicFooter: 'C = cânula perfusão aramada',
    goldenTitle: 'Referência — classificação CME',
    goldenContent: 'CRÍTICO × DESCARTÁVEL',
    rows: [
      { label: 'Crítico', value: 'Cânulas, pinças, instrumental invasivo', badge: 'hot' },
      { label: 'Descartável', value: 'Tubos, agulhas — descarte perfurocortante', badge: 'ok' },
    ],
    goldenFooter: 'Tubo coleta não é crítico CME',
    dangerTitle: 'PEGADINHAS — CME CPCON',
    dangerItems: [
      { label: 'Letra B — tubo coleta', detail: 'Descartável.', correct: 'Não reprocessa no CME — eliminar.' },
      { label: 'Letra A — cateter epidural', detail: 'Invasivo descartável em geral.', correct: 'Não é gabarito C desta questão.' },
      { label: 'Letra D — sensor PIC', detail: 'Dispositivo específico UTI.', correct: 'Classificação própria — não cânula perfusão.' },
      { label: 'Letra E — sonda NG', detail: 'Semicrítico/descartável.', correct: 'Cânula aramada (C) é crítica.' },
    ],
    dangerFooter: 'Crítico ≠ descartável de coleta',
  }),

  'educa-pb-enfermagem-coleta-de-exames-laboratoriais-1779562768558-6': mcqPack({
    branch: 'coleta_tecnica_venosa',
    guideline: 'CLSI — torniquete breve (<1–2 min) evita hemoconcentração e hemólise',
    title: 'Torniquete — coleta venosa',
    conceptItems: [
      { label: 'Comando', detail: 'Cuidado CORRETO antes da coleta de sangue.', icon: 'Clock' },
      { label: 'Torniquete breve (C)', detail: 'Evita hemoconcentração, hemólise e alteração de resultados.', icon: 'Timer' },
      { label: 'Pegadinha líquidos', detail: 'Jejum não proíbe água em geral — A falsa.', icon: 'Droplets' },
      { label: 'Identificação', detail: 'Etiqueta antes/durante coleta — B errada se “após”.', icon: 'Tag' },
      { label: 'Anticoagulados', detail: 'Podem coletar com orientação — D absoluta é falsa.', icon: 'Pill' },
    ],
    conceptFooter: 'Torniquete breve = C',
    steps: [
      'Comando: alternativa correta sobre cuidados pré-coleta.',
      'Torniquete prolongado altera exames — uso breve é conduta correta.',
      'Eliminar A (proibir líquidos), B (identificar após), D (vetar anticoagulados), E (horário irrelevante).',
      'Marcar C.',
    ],
    logicFooter: 'C = torniquete breve',
    goldenTitle: 'Referência — torniquete',
    goldenContent: 'TORNIQUETE — REGRA',
    rows: [
      { label: 'Tempo', value: 'O mais breve possível (<1–2 min)', badge: 'hot' },
      { label: 'Risco', value: 'Prolongado → hemólise/hemoconcentração', badge: 'warn' },
    ],
    goldenFooter: 'Soltar garrote assim que sangue flui',
    dangerTitle: 'PEGADINHAS — EDUCA PB',
    dangerItems: [
      { label: 'Letra A — zero líquido', detail: 'Jejum absoluto de água.', correct: 'Água geralmente permitida — afirmativa incorreta.' },
      { label: 'Letra B — identificar após', detail: 'Etiqueta tardia.', correct: 'Identificação é pré/por coleta — erro.' },
      { label: 'Letra D — vetar anticoagulado', detail: 'Proibição absoluta.', correct: 'Coleta possível com protocolo — falso.' },
      { label: 'Letra E — horário irrelevante', detail: 'Não registrar.', correct: 'Horário pode ser relevante — falso.' },
    ],
    dangerFooter: 'Garrote breve protege analitos',
  }),

  'fafipa-enfermagem-coleta-de-exames-laboratoriais-1779563165114-4': mcqPack({
    guideline: 'CLSI — glicose em jejum: tubo cinza (fluoreto de sódio) inibe glicólise',
    title: 'Glicose jejum — tubo cinza',
    conceptItems: [
      { label: 'Comando', detail: 'Tampa para glicose em jejum.', icon: 'FlaskConical' },
      { label: 'Cinza (D)', detail: 'Fluoreto preserva glicose in vivo.', icon: 'Droplet' },
      { label: 'Roxo', detail: 'EDTA — hemograma.', icon: 'TestTube' },
      { label: 'Vermelho/amarelo', detail: 'Soro — glicólise altera glicose.', icon: 'AlertTriangle' },
    ],
    conceptFooter: 'Glicose jejum → cinza',
    steps: [
      'Comando: cor do tubo para glicose em jejum.',
      'Glicose exige inibição da glicólise — fluoreto (cinza).',
      'Eliminar roxa, amarela, rosa, vermelha.',
      'Marcar D — cinza.',
    ],
    logicFooter: 'D = tampa cinza',
    goldenTitle: 'Referência — glicemia',
    goldenContent: 'GLICOSE — TUBO',
    rows: [
      { label: 'Jejum/glicose', value: 'Cinza — fluoreto', badge: 'hot' },
      { label: 'HbA1c', value: 'EDTA ou tubo específico lab', badge: 'ok' },
    ],
    goldenFooter: 'Fluoreto anti-glicólise',
    dangerTitle: 'PEGADINHAS — GLICOSE FAFIPA',
    dangerItems: [
      { label: 'Letra A — roxa', detail: 'EDTA.', correct: 'Hemograma — não glicemia de rotina.' },
      { label: 'Letra B — amarela', detail: 'Soro gel.', correct: 'Sem fluoreto — glicose cai pós-coleta.' },
      { label: 'Letra C — rosa', detail: 'Variante soro.', correct: 'Não é padrão glicose jejum.' },
      { label: 'Letra E — vermelha', detail: 'Soro seco.', correct: 'Glicólise altera resultado — exige cinza.' },
    ],
    dangerFooter: 'Cinza = glicose preservada',
  }),

  'fgv-enfermagem-coleta-de-exames-laboratoriais-1779562780466-2': mcqPack({
    guideline: 'MS — glicose pós-prandial: 2 h após início da refeição (ou 2–3 h conforme protocolo)',
    title: 'Glicose pós-prandial — timing',
    conceptItems: [
      { label: 'Comando', detail: 'Afirmativa CORRETA sobre coleta de materiais.', icon: 'Clock' },
      { label: 'Glicose PP (E)', detail: 'Coleta 2 h (ou 2–3 h) após refeição — curva glicêmica.', icon: 'Utensils' },
      { label: 'Ordem tubos', detail: 'B descreve sequência — verificar se é alternativa correta isolada.', icon: 'ListOrdered' },
      { label: 'Urocultura/RT-PCR', detail: 'Itens A e C — condutas específicas.', icon: 'Microscope' },
      { label: 'Colesterol', detail: 'Jejum 9–12 h — D.', icon: 'Heart' },
    ],
    conceptFooter: 'Glicose PP = 2 h após refeição (E)',
    steps: [
      'Comando: afirmativa correta FGV sobre coleta.',
      'Glicose pós-prandial: amostra 2 horas após início da alimentação.',
      'Eliminar A (RT-PCR swab), B se incorreta na ordem, C (urocultura), D (colesterol jejum).',
      'Marcar E.',
    ],
    logicFooter: 'E = glicose PP 2 h pós-refeição',
    goldenTitle: 'Referência — timing glicose',
    goldenContent: 'GLICOSE — HORÁRIO',
    rows: [
      { label: 'Jejum', value: '8–12 h', badge: 'ok' },
      { label: 'Pós-prandial', value: '2 h após início da refeição', badge: 'hot' },
      { label: 'Colesterol/TG', value: 'Jejum 9–12 h', badge: 'ok' },
    ],
    goldenFooter: 'Glicose pós-prandial coleta 2 h após refeição',
    dangerTitle: 'PEGADINHAS — FGV COLETA',
    dangerItems: [
      { label: 'Letra A — swab RT-PCR', detail: 'COVID swab.', correct: 'Protocolo respiratório — não afirmativa correta geral.' },
      { label: 'Letra C — urocultura manhã', detail: 'Jato médio matinal.', correct: 'Verdade parcial — E responde glicose PP.' },
      { label: 'Letra D — colesterol', detail: 'Jejum prolongado.', correct: 'Conduta correta isolada — E é gabarito desta.' },
      { label: 'Letra B — ordem tubos', detail: 'Sequência vácuo.', correct: 'Pode ser correta — mas E é resposta oficial.' },
    ],
    dangerFooter: '2 h após comer = glicose PP',
  }),

  'fgv-enfermagem-coleta-de-exames-laboratoriais-1779563225798-7': mcqPack({
    family: 'vf',
    guideline: 'CLSI/Potter — veias basílica/cefálica; gel separador antes coagulação; transferência seringa→vácuo não exige puncionar rolha com pressão no êmbolo',
    title: 'Coleta sangue — V/V/F FGV',
    conceptItems: [
      { label: 'Coleta de sangue', detail: 'Durante assistência — orientações FGV sobre exames laboratoriais.', icon: 'Syringe' },
      { label: 'I — veias basílica/cefálica', detail: 'Basílica mediana preferida; cefálica mais hematoma — Verdadeira.', icon: 'Activity' },
      { label: 'II — gel separador × coagulação', detail: 'Tubos sem aditivo antes dos de coagulação — Verdadeira.', icon: 'TestTube' },
      { label: 'III — transferência seringa', detail: 'Puncionar rolha e pressionar êmbolo 1/3 — Falsa.', icon: 'XCircle' },
      { label: 'Sequência', detail: 'Gabarito B: V – V – F respectivamente.', icon: 'ListChecks' },
    ],
    conceptFooter: 'B = V – V – F',
    steps: [
      'Comando: analise afirmativas sobre coleta de sangue — V ou F na ordem.',
      'I veias basílica mediana vs cefálica — Verdadeira (V).',
      'II gel separador interfere coagulação — tubos secos antes — Verdadeira (V).',
      'III transferência seringa puncionando rolha com pressão — Falsa (F).',
      'Marcar B — V – V – F.',
      'Em similares: sistema vácuo múltiplo — soro seco antes de citrato/coagulação.',
    ],
    logicFooter: 'B = V – V – F',
    goldenTitle: 'Referência — coleta FGV',
    goldenContent: 'TRÊS AFIRMATIVAS',
    rows: [
      { label: 'I veias', value: 'Basílica mediana > cefálica (hematoma)', badge: 'ok' },
      { label: 'II ordem', value: 'Sem aditivo antes coagulação', badge: 'hot' },
      { label: 'III seringa', value: 'Não puncionar rolha à pressão — F', badge: 'warn' },
    ],
    goldenFooter: 'Transferência seringa segue protocolo sem puncionar rolha',
    dangerTitle: 'PEGADINHAS — V/V/F FGV',
    dangerItems: [
      { label: 'Letra A — F-V-F', detail: 'Nega I.', correct: 'Basílica/cefálica é V — sequência errada.' },
      { label: 'Letra C — F-F-F', detail: 'Nega I e II.', correct: 'Primeiras duas verdadeiras.' },
      { label: 'Letra D — V-V-V', detail: 'Aceita III.', correct: 'III é F — técnica seringa incorreta.' },
      { label: 'Letra E — F-V-V', detail: 'Inverte I.', correct: 'B = V-V-F.' },
    ],
    dangerFooter: 'III falsa = transferência seringa',
  }),

  'fgv-enfermagem-exames-laboratoriais-1779563646977-3': mcqPack({
    guideline: 'CLSI — hemograma (EDTA roxo) + TOTG/glicose (cinza fluoreto): dois tubos distintos',
    title: 'Hemograma + TOTG — tubos',
    conceptItems: [
      { label: 'Comando', detail: 'Hemograma completo + teste tolerância glicose — quais tubos.', icon: 'TestTube' },
      { label: 'Roxo + cinza (B)', detail: 'EDTA hemograma + fluoreto glicose/TOTG.', icon: 'Layers' },
      { label: 'Azul + verde', detail: 'Citrato/heparina — outros analitos.', icon: 'Droplet' },
      { label: 'Branco + vermelho', detail: 'Não combina hemograma + glicose.', icon: 'XCircle' },
    ],
    conceptFooter: 'Hemograma roxo + glicose cinza = B',
    steps: [
      'Comando: tubos para hemograma completo + TOTG.',
      'Hemograma → EDTA (roxa).',
      'TOTG/glicose → fluoreto (cinza).',
      'Eliminar A, C, D, E.',
      'Marcar B — roxa e cinza.',
    ],
    logicFooter: 'B = roxa + cinza',
    goldenTitle: 'Referência — dois analitos',
    goldenContent: 'HEMOGRAMA + GLICOSE',
    rows: [
      { label: 'Hemograma', value: 'EDTA roxo/lilás', badge: 'hot' },
      { label: 'TOTG/glicose', value: 'Fluoreto cinza', badge: 'hot' },
      { label: 'Ordem', value: 'Seguir CLSI se coleta sequencial', badge: 'warn' },
    ],
    goldenFooter: 'Dois exames = dois tubos',
    dangerTitle: 'PEGADINHAS — FGV TOTG',
    dangerItems: [
      { label: 'Letra A — azul e verde', detail: 'Citrato/heparina.', correct: 'Coagulação/plasma — não hemograma+TOTG.' },
      { label: 'Letra C — verde e amarela', detail: 'Plasma/soro.', correct: 'Não substitui EDTA+fluoreto.' },
      { label: 'Letra D — branca e vermelha', detail: 'Combinação atípica.', correct: 'Roxo+cinza (B) é padrão.' },
      { label: 'Letra E — vermelha e roxa', detail: 'Soro + EDTA.', correct: 'TOTG exige cinza — B completa.' },
    ],
    dangerFooter: 'Nunca unificar hemograma e glicose no mesmo tubo',
  }),
};

runHandcraftLote(LOTE, REVIEWER, SPECS);
