/**
 * Converte ThemeColors (legado cyber) para tokens editoriais claros (Opção B).
 */
import type { ThemeColors } from '@/components/slides/core/themeGenerator';

type EditorialTokens = Omit<ThemeColors, 'name' | 'accent'>;

const EDITORIAL_TOKENS: Record<string, EditorialTokens> = {
  indigo: {
    primary: 'from-indigo-50 to-white',
    secondary: 'from-indigo-100 to-indigo-50',
    glow: 'rgba(99, 102, 241, 0.08)',
    bgGradient: 'from-indigo-50/90 to-white',
    borderColor: 'border-indigo-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-indigo-50',
    iconText: 'text-indigo-600',
    iconHoverBg: 'group-hover:bg-indigo-100',
    iconHoverText: 'group-hover:text-indigo-700',
    glowGradient: 'from-indigo-100/70',
  },
  emerald: {
    primary: 'from-emerald-50 to-white',
    secondary: 'from-emerald-100 to-emerald-50',
    glow: 'rgba(16, 185, 129, 0.08)',
    bgGradient: 'from-emerald-50/90 to-white',
    borderColor: 'border-emerald-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-emerald-50',
    iconText: 'text-emerald-600',
    iconHoverBg: 'group-hover:bg-emerald-100',
    iconHoverText: 'group-hover:text-emerald-700',
    glowGradient: 'from-emerald-100/70',
  },
  rose: {
    primary: 'from-rose-50 to-white',
    secondary: 'from-rose-100 to-rose-50',
    glow: 'rgba(225, 29, 72, 0.08)',
    bgGradient: 'from-rose-50/90 to-white',
    borderColor: 'border-rose-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-rose-50',
    iconText: 'text-rose-600',
    iconHoverBg: 'group-hover:bg-rose-100',
    iconHoverText: 'group-hover:text-rose-700',
    glowGradient: 'from-rose-100/70',
  },
  amber: {
    primary: 'from-amber-50 to-white',
    secondary: 'from-amber-100 to-amber-50',
    glow: 'rgba(245, 158, 11, 0.08)',
    bgGradient: 'from-amber-50/90 to-white',
    borderColor: 'border-amber-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-amber-50',
    iconText: 'text-amber-600',
    iconHoverBg: 'group-hover:bg-amber-100',
    iconHoverText: 'group-hover:text-amber-700',
    glowGradient: 'from-amber-100/70',
  },
  violet: {
    primary: 'from-violet-50 to-white',
    secondary: 'from-violet-100 to-violet-50',
    glow: 'rgba(139, 92, 246, 0.08)',
    bgGradient: 'from-violet-50/90 to-white',
    borderColor: 'border-violet-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-violet-50',
    iconText: 'text-violet-600',
    iconHoverBg: 'group-hover:bg-violet-100',
    iconHoverText: 'group-hover:text-violet-700',
    glowGradient: 'from-violet-100/70',
  },
  cyan: {
    primary: 'from-cyan-50 to-white',
    secondary: 'from-cyan-100 to-cyan-50',
    glow: 'rgba(6, 182, 212, 0.08)',
    bgGradient: 'from-cyan-50/90 to-white',
    borderColor: 'border-cyan-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-cyan-50',
    iconText: 'text-cyan-600',
    iconHoverBg: 'group-hover:bg-cyan-100',
    iconHoverText: 'group-hover:text-cyan-700',
    glowGradient: 'from-cyan-100/70',
  },
  fuchsia: {
    primary: 'from-fuchsia-50 to-white',
    secondary: 'from-fuchsia-100 to-fuchsia-50',
    glow: 'rgba(217, 70, 239, 0.08)',
    bgGradient: 'from-fuchsia-50/90 to-white',
    borderColor: 'border-fuchsia-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-fuchsia-50',
    iconText: 'text-fuchsia-600',
    iconHoverBg: 'group-hover:bg-fuchsia-100',
    iconHoverText: 'group-hover:text-fuchsia-700',
    glowGradient: 'from-fuchsia-100/70',
  },
  sky: {
    primary: 'from-sky-50 to-white',
    secondary: 'from-sky-100 to-sky-50',
    glow: 'rgba(14, 165, 233, 0.08)',
    bgGradient: 'from-sky-50/90 to-white',
    borderColor: 'border-sky-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-sky-50',
    iconText: 'text-sky-600',
    iconHoverBg: 'group-hover:bg-sky-100',
    iconHoverText: 'group-hover:text-sky-700',
    glowGradient: 'from-sky-100/70',
  },
  lime: {
    primary: 'from-lime-50 to-white',
    secondary: 'from-lime-100 to-lime-50',
    glow: 'rgba(132, 204, 22, 0.08)',
    bgGradient: 'from-lime-50/90 to-white',
    borderColor: 'border-lime-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-lime-50',
    iconText: 'text-lime-600',
    iconHoverBg: 'group-hover:bg-lime-100',
    iconHoverText: 'group-hover:text-lime-700',
    glowGradient: 'from-lime-100/70',
  },
  teal: {
    primary: 'from-teal-50 to-white',
    secondary: 'from-teal-100 to-teal-50',
    glow: 'rgba(20, 184, 166, 0.08)',
    bgGradient: 'from-teal-50/90 to-white',
    borderColor: 'border-teal-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-teal-50',
    iconText: 'text-teal-600',
    iconHoverBg: 'group-hover:bg-teal-100',
    iconHoverText: 'group-hover:text-teal-700',
    glowGradient: 'from-teal-100/70',
  },
  orange: {
    primary: 'from-orange-50 to-white',
    secondary: 'from-orange-100 to-orange-50',
    glow: 'rgba(249, 115, 22, 0.08)',
    bgGradient: 'from-orange-50/90 to-white',
    borderColor: 'border-orange-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-orange-50',
    iconText: 'text-orange-600',
    iconHoverBg: 'group-hover:bg-orange-100',
    iconHoverText: 'group-hover:text-orange-700',
    glowGradient: 'from-orange-100/70',
  },
  blue: {
    primary: 'from-blue-50 to-white',
    secondary: 'from-blue-100 to-blue-50',
    glow: 'rgba(37, 99, 235, 0.08)',
    bgGradient: 'from-blue-50/90 to-white',
    borderColor: 'border-blue-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-blue-50',
    iconText: 'text-blue-600',
    iconHoverBg: 'group-hover:bg-blue-100',
    iconHoverText: 'group-hover:text-blue-700',
    glowGradient: 'from-blue-100/70',
  },
  purple: {
    primary: 'from-purple-50 to-white',
    secondary: 'from-purple-100 to-purple-50',
    glow: 'rgba(168, 85, 247, 0.08)',
    bgGradient: 'from-purple-50/90 to-white',
    borderColor: 'border-purple-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-purple-50',
    iconText: 'text-purple-600',
    iconHoverBg: 'group-hover:bg-purple-100',
    iconHoverText: 'group-hover:text-purple-700',
    glowGradient: 'from-purple-100/70',
  },
  pink: {
    primary: 'from-pink-50 to-white',
    secondary: 'from-pink-100 to-pink-50',
    glow: 'rgba(236, 72, 153, 0.08)',
    bgGradient: 'from-pink-50/90 to-white',
    borderColor: 'border-pink-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    iconBg: 'bg-pink-50',
    iconText: 'text-pink-600',
    iconHoverBg: 'group-hover:bg-pink-100',
    iconHoverText: 'group-hover:text-pink-700',
    glowGradient: 'from-pink-100/70',
  },
};

const FALLBACK_EDITORIAL = EDITORIAL_TOKENS.indigo;

/** Aplica skin editorial (Opção B) mantendo nome/accent e glow variável do hash. */
export function toEditorialTheme(theme: ThemeColors): ThemeColors {
  const tokens = EDITORIAL_TOKENS[theme.name] ?? FALLBACK_EDITORIAL;
  return {
    ...theme,
    ...tokens,
    glow: theme.glow,
  };
}
